Feature/#84 컨퍼런스 같이 가고싶어요 요청 api 구현
woowacourse-teams/2023-emmsale pull request #109
Opened 2023-07-26 12:30 UTC by hong-sile

## #️⃣연관된 이슈
- #84 

## 📝작업 내용
- 이벤트에 값을 추가하는 기능 추가

## 💬리뷰 요구사항
- service에서 추가하는 흐름을 한 번 봐주셨으면 합니다.

2023-07-26 13:01 UTC, Hyeonjae-K commented on backend/emm-sale/src/docs/asciidoc/index.adoc
> +=== `POST` : 컨퍼런스에 함께가기 요청(컨퍼런스에 함께 까는 멤버에 등록)
"함께 까는"에 오타가 있네요 ^^;

2023-07-26 13:23 UTC, hong-sile commented on backend/emm-sale/src/docs/asciidoc/index.adoc
> +=== `POST` : 컨퍼런스에 함께가기 요청(컨퍼런스에 함께 까는 멤버에 등록)
zㅋㅋㅋㅋ 감사합니다.

2023-07-26 13:42 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +  private static void validateMemberNotAllowed(final Long memberId, final Member member) {
아마 메서드 추출을 하다가 붙은 것 같네요.
특별한 기준은 없고, 꼭 지워야 한다는 생각도 없습니다.

2023-07-26 13:42 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +      assertThatThrownBy(() -> eventService.participate(인프콘.getId(), 2L, member))
좋은 생각이네요 반영할게요

2023-07-26 13:43 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +  class participate {
단락으로 구분해서 괜찮을 거라 생각했는데 다음부터 추가해보도록 할게요

2023-07-26 15:56 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +  private static void validateMemberNotAllowed(final Long memberId, final Member member) {
물론 private 여서 다른 곳에서 사용할 수는 없지만, 다른 곳에서 사용하지 않을 뿐더러 private 면 static 붙은 의미가 없을 것 같아서요. 사용할 필요가 없다면 지우는게 좋지 않을까 싶습니다! 만약 정적 메서드에서 사용하여 static 을 붙여야 하는 경우를 제외하고는요

2023-07-26 15:56 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
>    public ResponseEntity<EventDetailResponse> findEventById(@PathVariable final String id) {
바로 Long으로 안 받으시는 이유가 있으신가요??

2023-07-26 15:56 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +    if (!memberId.equals(member.getId())) {
아까 isNotMe 이거 사용하지 않으셨나여?? 아직 수정되지 않은 것 같아서 말씀드립니다 !

2023-07-26 15:56 UTC, java-saeng commented on backend/emm-sale/src/main/resources/data.sql
> +insert into event (id, created_at, updated_at, end_date, information_url, location, name,
처음 data.sql 수정한 이후로는 data.sql 을 수정하지 않는 것으로 이해했는데, 혹시 제가 잘못이해하고 있었을까요??

상대방의 테스트가 깨질 것을 염려해서 각자 테스트 안에서 만들자고 기억이 나는 것 같아서요

2023-07-26 15:56 UTC, java-saeng commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +    void Success() {
메서드 대문자!

2023-07-26 15:56 UTC, java-saeng commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +  class participate {
클래스 소문자!(Nested 는 해도 되나요? 진짜 몰라서요)

2023-07-26 15:56 UTC, java-saeng commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +      final Event 인프콘 = eventRepository.save(eventFixture());
ㅋㅋ ^^

2023-07-26 15:56 UTC, java-saeng commented
고생하셨습니다~~ 내일 현장 리뷰에서 얘기해봐여

2023-07-27 04:28 UTC, amaran-th requested changes

2023-07-27 06:12 UTC, amaran-th approved these changes

2023-07-27 06:15 UTC, merged

2023-07-27 08:25 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
>    public ResponseEntity<EventDetailResponse> findEventById(@PathVariable final String id) {
되는줄 몰랐네요 수정할게요