Feature/#100 오픈채팅 프로필 url 등록 기능 구현
woowacourse-teams/2023-emmsale pull request #110
Opened 2023-07-26 12:59 UTC by Hyeonjae-K

## #️⃣연관된 이슈
- #100 

close: #100 

## 📝작업 내용
- 오픈 프로필 URL 업데이트 기능 구현
- RestDocs 및 .http 추가

## 예상 소요 시간 및 실제 소요 시간
2시간 / 3시간

2023-07-26 13:42 UTC, amaran-th requested changes
수고하셨습니다!
몇 가지 누락된 것으로 보이는 코드가 있어서 코멘트 남겼습니다!
반영 부탁드려요~~!

2023-07-26 13:42 UTC, amaran-th commented on backend/emm-sale/src/main/resources/static/docs/index.html
> +</html>
'career', '커리어'로 검색하니 수정되지 않은 부분이 많이 남아있는 것 같아요!
당장 급한 건은 아니지만 이왕 바꾸는 거 마저 수정해주시면 좋을 것 같아요.

2023-07-26 13:42 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
> +    return ResponseEntity.ok().build();
ok() 대신 noContent()를 사용해도 좋을 것 같아요!

2023-07-26 13:42 UTC, amaran-th commented on backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
> +  private MemberUpdateService memberUpdateService;
현재 코드에서 사용되고 있지 않은 것 같습니다!

2023-07-26 16:10 UTC, java-saeng reviewed
고생하셨습니다~~

테스트 하실 때, 테스트 코드도 물론 중요하지만 로컬에서 해당 API 를 한번 호출해보고 직접 눈으로 확인하는 것도 좋은 방법이지 않을까 생각합니다!

낼 현장 리뷰에서 뵙죠~~

수정하고 다시 request 주십셔

2023-07-26 16:10 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
> +    return ResponseEntity.ok().build();
ㅇㅈ

2023-07-26 16:10 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/member/application/dto/OpenProfileUrlRequest.java
> +  @Pattern(regexp = "(https://open.kakao.com/).*")
지리구요

2023-07-26 16:10 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/member/application/MemberUpdateService.java
> +  public void updateOpenProfileUrl(
JPA에서는 변경감지를 통해서 데이터를 수정해주는데 @Transactinoal 이 없으면 변경 감지가 동작 안하는 것으로 알고 있습니다,,
혹시 http 테스트를 하고 데이터가 변경되었는지 확인하셨는지 궁금합니다 !!

저도 트랜잭션 어노테이션 사용안해서 수정 안됐던 기억이,,

2023-07-26 16:10 UTC, java-saeng commented on backend/emm-sale/src/test/java/com/emmsale/member/application/MemberUpdateServiceTest.java
> +    assertThat(member.getOpenProfileUrl()).isEqualTo(newOpenProfileUrl);
이 테스트가 성공한 이유는 데이터베이스에 있는 member가 아닌 자바 객체의 member의 프로퍼티를 검사하고 있어서 성공한 것 같아요. 

아마 update 하고 나서 DB에서 직접 조회해오면 테스트가 실패할 것 같아요~~ 아래 참고해주십셔

![image](https://github.com/woowacourse-teams/2023-emmsale/assets/62413589/459c7d8c-220d-4966-86c8-6c234a4e08b5)

2023-07-27 00:54 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/resources/static/docs/index.html
> +</html>
이 부분은 제가 이 이슈에서 수정할 부분이 아닌 것 같아요^^;
나중에 이슈를 파서 수정해야 할 것 같습니다.

2023-07-27 00:58 UTC, Hyeonjae-K commented on backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
> +  private MemberUpdateService memberUpdateService;
`MemberApi` 클래스를 빈으로 실행시키기 위해 필요합니다.

2023-07-27 01:00 UTC, hong-sile approved these changes
Transactional 부분 말고는 걸리는 부분이 없네요. 수고하셨습니다.

2023-07-27 01:00 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/member/application/MemberUpdateService.java
> +public class MemberUpdateService {
혹시 MemberUpdateService라고 이름을 지은 이유가 있을까요? 
궁금해서요

2023-07-27 02:14 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/member/application/MemberUpdateService.java
> +public class MemberUpdateService {
개인적으로 클래스의 역할을 파악하기 쉽다고 느껴서 위와 같이 지었습니다.

2023-07-27 06:24 UTC, hong-sile approved these changes

2023-07-27 06:24 UTC, amaran-th approved these changes

2023-07-27 06:24 UTC, java-saeng approved these changes

2023-07-27 06:26 UTC, merged