Feature/#115 이벤트 cud 기능 구현
woowacourse-teams/2023-emmsale pull request #138
Opened 2023-07-29 06:08 UTC by Hyeonjae-K

## #️⃣연관된 이슈
- #115 

close #115 

## 📝작업 내용
- [x] 이벤트 Create 기능 구현
- [x] 이벤트 Update 기능 구현
- [x] 이벤트 Delete 기능 구현

### 스크린샷 (선택)
![localhost_63342_emm-sale_backend_emm-sale_src_main_resources_static_docs_index html__ijt=7fj6dgpnueh2o84f4sg0fg3vus _ij_reload=RELOAD_ON_SAVE](https://github.com/woowacourse-teams/2023-emmsale/assets/71651608/83023462-a3ac-40f6-9e0e-976bb3a32c8e)

![localhost_63342_emm-sale_backend_emm-sale_src_main_resources_static_docs_index html__ijt=7fj6dgpnueh2o84f4sg0fg3vus _ij_reload=RELOAD_ON_SAVE (1)](https://github.com/woowacourse-teams/2023-emmsale/assets/71651608/c64259c8-95ca-4840-818c-95ae4079010a)

![localhost_63342_emm-sale_backend_emm-sale_src_main_resources_static_docs_index html__ijt=7fj6dgpnueh2o84f4sg0fg3vus _ij_reload=RELOAD_ON_SAVE (2)](https://github.com/woowacourse-teams/2023-emmsale/assets/71651608/210eba04-165e-4d85-93d5-5b19b0a008a0)

## 예상 소요 시간 및 실제 소요 시간
6시간 / 8시간

2023-07-30 11:35 UTC, amaran-th approved these changes
수고하셨습니다~! 코드가 전체적으로 가독성이 좋아서 술술 잘 읽히네요
코멘트 확인 후 반영부탁드립니다~!
미리 approve할게요!

2023-07-30 11:35 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +  }
NIT: 이 메서드에서 사용된 saveNewEvent() 메서드와 findAllPersistTagsOrElseThrow() 메서드는 순서 상 addEvent 바로 다음에 오면 코드를 읽기 더 쉬울 것 같습니다!

2023-07-31 06:54 UTC, java-saeng requested changes
고생하셨습니다 !!

코멘트에 대해 제리 생각 한번 써주시고 재요청 주세요

2023-07-31 06:54 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
> +  @OneToMany(mappedBy = "event", fetch = FetchType.EAGER, cascade = CascadeType.PERSIST)
EAGER를 쓰신 이유가 있을까요?

2023-07-31 06:54 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/GlobalControllerAdvice.java
> +    log.warn("[WARN] MESSAGE: " + message);
위와 마찬가지입니다.

2023-07-31 06:54 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +    final Event updatedEvent = event.updateEventContent(request.getName(), request.getLocation(),
매번 존재했던 태그들을 삭제하고 저장하는 방식인가요?

모든 태그들을 저장하는게 List 여서, 굳이 for문을 돌지 않고 바로 addAll 하는게 어떤가 해서요

2023-07-31 07:37 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/GlobalControllerAdvice.java
> +    log.warn("[WARN] MESSAGE: {}", message);
저는 개인적으로 warn 단계 적당하다고 생각합니다. 
info라고 하기에는 일반적이지 않은 상황이고,
error라고 하기에는 예측한 에러 상황이니까요.

이에 대해서 한번 이야기를 해볼 수 있을 것 같아요.

2023-07-31 07:38 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
> +  @OneToMany(mappedBy = "event", fetch = FetchType.EAGER, cascade = CascadeType.PERSIST)
저도 이 부분은 궁금하네요.

2023-07-31 07:39 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
> +    validateStartBeforeOrEqualEndDateTime(startDate, endDate);
👍

2023-07-31 07:57 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
> +      addEventTag(tag);
혹시 이 부분 N+1문제 안 나나요?
궁금해서요

2023-07-31 07:58 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/event/domain/EventTest.java
> +        () -> assertEquals(newTags.size(), event.getTags().size())
태그는 사이즈 말고 더 정확한 방식으로 검증하면 어떨까요?

2023-07-31 08:00 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
> +      addEventTag(tag);
추가적으로 이런식으로 작성하면 기존에 있는, EventTag들은 테이블에서 다 지워지나요?
안 지워지고 남아있을수도 있을 것 같다는 생각이 들어서요

2023-07-31 08:12 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +
컨벤션이나 기능상 문제가 있는건 아닌데 혹시 되돌려야 하는 이유가 있을까요?

2023-07-31 08:17 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/event/domain/EventTag.java
> +  @ManyToOne(fetch = FetchType.EAGER)
가장 큰 이유는 `EventServiceTest`에서 이벤트에 태그가 정상적으로 생성/업데이트 되었는지 확인하기 위함입니다.
`EventDetailResponse`와 `EventResponse`를 보았을 때 모두 태그를 반환하고 있어 이벤트와 태그는 항상 같이 조회되므로 사실상 EAGER로 했을 때 불필요한 조회가 일어나지 않을 것으로 예상되어 EAGER로  설정하고 테스트했습니다.

2023-07-31 08:17 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
> +  @OneToMany(mappedBy = "event", fetch = FetchType.EAGER, cascade = CascadeType.PERSIST)
https://github.com/woowacourse-teams/2023-emmsale/pull/138#discussion_r1278942293

2023-07-31 08:19 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/GlobalControllerAdvice.java
> +    log.warn("[WARN] MESSAGE: {}", message);
저도 warn이 적당하다고 생각했으나 info로 해도 괜찮지 않을까 싶기도 하네요.
어디까질 warn, 어디부턴 info를 나누는 기준이 명확하지 않아  다같이 얘기해보면 좋을 것  같습니다.
혹시 의견 있으시면 남겨주세요.

2023-07-31 08:35 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +    final Event updatedEvent = event.updateEventContent(request.getName(), request.getLocation(),
네, 매번 모든 태그를 지우고  새로 등록합니다.
업데이트가 일어날 때 기존 이벤트에 등록된 태그를 확인해서 중복되는 것은 남겨두고 존재하지 않는 것은 지우고 새로운 것은 등록하는 것 보다 모두 지우고 새로  등록하는게 로직상 복잡도를 낮추고 업데이트가 자주 일어나는 일이 아니므로 괜찮을 것이라 생각하여 위와 같이 구현했습니다.
혹시 이에 대한 경험이 있으시면 공유해 주세요.

addAll 방식으로 리팩터링 완료 했습니다.

2023-07-31 08:35 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
> +      addEventTag(tag);
https://github.com/woowacourse-teams/2023-emmsale/pull/138#discussion_r1278962822

2023-07-31 08:40 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +
먼저 해당 메서드가 static으로 선언되어야 할 이유가 없는 것 같고, 제가 public 메서드 다음에 private 메서드를 작성하는 것이 코드 흐름을 따라가기 편하다고 생각해서 그렇게 요청 드렸었습니다!

2023-07-31 13:02 UTC, merged