Feature/#48 프로필 화면 구현
woowacourse-teams/2023-emmsale pull request #139
Opened 2023-07-30 04:48 UTC by ki960213

## #️⃣연관된 이슈
>  #48 

## 📝작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
내 프로필 화면 구현

### 스크린샷 (선택)
![image](https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/dd8138e0-2de3-433e-ac0b-fe586cbb3e5c)

## 예상 소요 시간 및 실제 소요 시간
> 이슈의 예상 소요 시간과 실제 소요된 시간을 분 or 시간 or 일 단위로 작성해주세요.
> 
> 예상시간/걸린시간 => 1일/2일

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
데이터 모델이 애매해서 일단 클래스 명을 Activity1, Member1 이렇게 만들었습니다.

2023-07-31 06:58 UTC, tmdgh1592 requested changes
프로필 화면 구현하시느라 고생하셨습니다 👍

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
> +        val activitiesResponseDeferred = async { memberService.fetchActivities() }
fetchActivities()도 좋지만, fetchMemberActivities()라고 작성하면 조금 더 명확할 것 같습니다!
처음에 fetchActivities()만 보고, `memberService에서 액티비티 목록들을 반환하는건가..?` 라는 혼동이 잠깐 있었습니다.

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +data class MemberActivitiesBindActivityTypeApiModel(
`MemberActivitiesBindActivityTypeApiModel`에서 **BindActivity**는 무엇을 의미하는건가요??

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +            else -> throw IllegalStateException("회원의 활동 Json 데이터를 도메인 모델로 매핑하는 데 실패했습니다. 서버와 Api 스펙을 다시 상의해보세요.")
예외 메시지가 명확해서 보기 좋네요 👍

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +            else -> throw IllegalStateException("회원의 활동 Json 데이터를 도메인 모델로 매핑하는 데 실패했습니다. 서버와 Api 스펙을 다시 상의해보세요.")
ActivityType에게 역할을 부여해도 좋을 것 같습니다!
`ActivityType`이 바뀌어도 `MemberActivitiesBindActivityTypeApiModel`는 변경될 필요가 없어집니다!

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +    val memberActivityResponses: List<MemberActivityApiModel>,
이건 선택이지만, @SerialName(...)을 설정해두면, 혹시 나중에 프로퍼티명이 실수나 고의로 변경된다고 하더라도, 역/직렬화 이름은 그대로 유지되기 때문에 버그가 발생하는 상황을 방지할 수 있습니다!

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginActivity.kt
>      }
MainActivity로 이동한 후에는, 로그인 화면이 더 이상 남아 있을 필요가 없을 것 같아요!
finish() 메서드를 호출하여 불필요한 Activity는 제거하는 건 어떨까요?

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +        val bnvMain = binding.bnvMain
xml에서는 크게 상관없지만, 코드를 작성할 때에는 이름이 명확해도 좋을 것 같습니다.
`val mainBottomNavigationView = binding.bvnMain`

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +        supportFragmentManager.beginTransaction().replace(R.id.fcv_main, fragment).commit()
fragment ktx 라이브러리가 이미 추가되어 있기 때문에, 아래와 같이 작성하여 가독성을 높일 수도 있습니다.
```kotlin
supportFragmentManager.commit { 
    replace(R.id.fragment_container, MainFragment())
}
```

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +                R.id.mi_main_home -> changeFragment(EventsFragment())
탭을 선택할 때마다 매번 Fragment를 새로 생성하고 있습니다.

EventsFragment는 매번 새로운 데이터를 불러오기 위함일 수 있지만,
`MyProfileFragment`처럼 서버에서 가져오는 값이 항상 동일한 경우에는 매번 생성할 필요가 없다고 생각해요!

혹시 위와 같이 구현하신 이유가 있을까요?

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +        }
아래와 같이 한 줄에 작성해도 좋을 것 같아요~!
```kotlin
fun startActivity(context: Context) {
    startActivity(Intent(context, MainActivity::class.java))
}
```

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileFragment.kt
> +    }
livedata를 observe할 때에는 setupXxx() 라는 네이밍을 사용하기로 한 컨벤션이 있습니다.
컨벤션을 참고해서 코드를 작성해주세요 : )

<img width="399" alt="스크린샷 2023-07-31 오후 3 24 44" src="https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/d3e98743-bd71-4680-b20a-fa989aaf76a6">

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
> +                ?: throw IllegalStateException("로그인을 하지 않은 상태로 이 화면에 올 수 없습니다. 로그인 로직을 다시 살펴보세요.")
token이 null이라면, 예외를 던져서 앱을 강제 종료시키는 것보다 로그인 화면으로 이동하는 것이 좋다고 생각해요!

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/ActivitiesAdapter.kt
> +    }
areItemsTheSame()과 areContentsTheSame()에서 반환하는 값이 서로 바뀌었습니다.
areItemsTheSame()은 Item의 고유성을 나타낼 수 있는 값이 같은지 반환해야 합니다. (ex. id)

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/ActivitiesAdapter.kt
> +class ActivityViewHolder(
Adapter와 ViewHolder를 별도로 분리해보는 것도 좋아 보입니다!

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/ActivitiesAdapter.kt
> +@BindingAdapter("myprofile_activities")
모든 RecyclerView가 공통적으로 사용할 수 있는 속성에 대해서만 BindingAdapter로 작성해야 한다고 생각합니다.
이 속성은 모든 RecyclerView에서 접근할 수 있지만, 실질적으로는 ActivityUiState 리스트만 전달받을 수 있습니다.

이후에 RecyclerView에 보여져야 할 데이터의 종류가 추가될 때마다 RecyclerView의 속성이 계속해서 늘어나야 할까요?!

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/JobsAdapter.kt
ActivitiesAdapter 코드 리뷰와 동일합니다 : )

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/itemDecoration/ActivitiesAdapterDecoration.kt
> +        fun getInstance() = instance
함수 시그너처로 반환 타입을 작성해주시면 좋을 것 같습니다 : )

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/uiState/MyProfileScreenUiState.kt
> +    val events: List<ActivityUiState>
프로퍼티가 엄청 많군요 😱

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/bindingadapter/ImageViewBindingAdapter.kt
> +        .into(imageView)
지금은 에러 이미지가 없지만, 나중에 만약 이미지를 불러오지 못하는 상황에서는 어떤 이미지를 보여줄 지도 함께 고려해보면 좋을 것 같아요!

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_myprofile_activities.xml
> +            android:id="@+id/iv_myprofile_activitynamedecorator"
이 부분은 팀 내에서 정한 컨벤션이지만, 언더바(_)가 없으니 확실히 읽기 힘들어지네요 🥲
이후에 컨벤션 수정이 시급해보입니다..!! 🙏

2023-07-31 06:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/menu/menu_main_bottomnavigationview.xml
> +        android:icon="@drawable/ic_main_menuitemsetting" />
여기서도 팀 컨벤션을 유지하려다 보니 읽기 힘든 파일명이 생겨버렸네요..!

2023-07-31 07:05 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/Member1.kt
> +        activities[activityType] ?: listOf()
생각해보니 그게 더 나은 것 같네요! 반영하겠습니다.

2023-07-31 07:08 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
> +        val activitiesResponse = activitiesResponseDeferred.await()
오 생각해보니 memberResponseDeferred.await()를 호출하면 값이 반환될 때까지 activitiesResponseDeferred.await()가 실행되지 않는군요! 반영하겠습니다.

2023-07-31 07:17 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepository.kt
> +
좋은 것 같아요! 동의합니다. Repository와 Service의 fetchXxx() 메서드 명을 전부 getXxx()로 바꾸면 좋을 것 같습니다.

2023-07-31 07:23 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
> +        val activitiesResponseDeferred = async { memberService.fetchActivities() }
저는 memberService.fetchActivities(memberId: Long) 이런 시그니처가 좋다고 생각했습니다. memberId와 관련있는 Activities를 가져온다는 의미를 담을 수 있기 때문입니다. 그리고 실제로 가져오는 것도 Activity라는 것을 가져오기 때문입니다. 하지만 memberId를 토큰으로 대체했기 때문에 memberId 매개변수가 필요없어서 저렇게 만들었습니다.
만약 fetchMemberActivities()라고 선언한다면 MemberActivity라는 데이터를 요청하는 건 줄 알았는데, 정작 가져오는 데이터는 MemberActivity가 아닌 Activity이기 때문에 혼동이 있지 않을까요?
결론은 fetchXxx()에서 Xxx에 들어갈 것은 받을 데이터의 종류, fetchXxx()의 매개변수는 데이터들을 필터링, 정렬과 같은 것으로 정의하는 것이 명확하다고 생각합니다!

2023-07-31 07:26 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +data class MemberActivitiesBindActivityTypeApiModel(
활동 타입으로 묶인 회원의 활동 목록입니다! 이름이 이상하군요!
클래스 명을 ActivitiesAssociatedByActivityTypeApiModel로 바꾸는 게 나을까요?

2023-07-31 07:36 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +            else -> throw IllegalStateException("회원의 활동 Json 데이터를 도메인 모델로 매핑하는 데 실패했습니다. 서버와 Api 스펙을 다시 상의해보세요.")
Api 요청 시 반환되는 값 중 "activityType": "동아리" 이러한 값들은 서버와 협상한 일종의 신호라고 생각합니다.
"동아리라는 코드는 활동 중 동아리 타입이야." 이런 식으로... 동아리가 아니라 "c"라는 값이 동아리 타입이라고 할 수도 있습니다. 즉, 이러한 서버와의 협상에 사용되는 신호가 ActivityType이라는 도메인 로직을 담당하는 데이터 모델에 포함되면 안된다고 생각합니다.
ActivityType은 도메인 로직을 위한 코드이고, MemberActivitiesBindActivityTypeApiModel이라는 서버와 통신하기 위한 dto로서의 코드라는 점을 고려해본다면 협상 신호를 데이터 모델로 매핑하는 일은 데이터 모델이 할 일은 아니라고 생각합니다. 데이터 모델이 비즈니스 로직이 아닌 서버 통신을 위한 로직을 담당하는 것은 좋지 않다고 생각합니다!

2023-07-31 07:39 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +    val memberActivityResponses: List<MemberActivityApiModel>,
dto는 딱 외부 서비스와의 통신을 위한 데이터 묶음이므로 프로퍼티 명을 외부 서비스와 관련 없는 이름으로 선언할 필요가 없다고 생각합니다.
따라서 나중에 프로퍼티 명을 변경할 이유가 없다고 생각합니다...! 그냥 외부 서비스에서 제공하는 이름 그대로 선언하는 것이 생각하기에도 편하다고 생각합니다.

2023-07-31 07:39 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginActivity.kt
>      }
이 부분은 생각 못했네요! 감사합니다. 반영하겠습니다.

2023-07-31 07:45 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +        val bnvMain = binding.bnvMain
그렇네요! bvn이 뭔지 안떠오를 수도 있을 때, 명확한 이름을 보면 bvn이 뭔지 더 잘 기억할 수 있겠네요.

2023-07-31 07:46 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +                R.id.mi_main_home -> changeFragment(EventsFragment())
이때 당시 새로고침 기능을 구현하지 않아서 프래그먼트를 매번 생성하도록 했습니다. 지금은 새로고침 기능을 구현했으니 show/hide로 바꾸겠습니다!

2023-07-31 07:47 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
> +                ?: throw IllegalStateException("로그인을 하지 않은 상태로 이 화면에 올 수 없습니다. 로그인 로직을 다시 살펴보세요.")
그렇네요! 감사합니다!

2023-07-31 07:48 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/ActivitiesAdapter.kt
> +    }
몰랐네요! 감사합니다.

2023-07-31 07:50 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/ActivitiesAdapter.kt
> +class ActivityViewHolder(
제 경험 상 리사이클러 뷰의 로직을 수정할 때 Adapter와 ViewHolder를 같이 봐야 하는 경우가 많아서 한 파일에 모아뒀는데, 생각해보니 여러 파일을 한 번에 띄울 수 있으니 별도로 분리하는 게 더 좋을 것 같군요!

2023-07-31 07:51 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/bindingadapter/ImageViewBindingAdapter.kt
> +        .into(imageView)
아직 에러 이미지로 무엇을 보여줄 지 결정하지 않아서 일단 에러 이미지를 띄우는 기능을 넣지 않았는데, 임시로 넣어두겠습니다!

2023-07-31 08:02 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/ActivitiesAdapter.kt
> +@BindingAdapter("myprofile_activities")
"myprofile_"과 같은 접두사를 붙이면 RecyclerView에서 사용할 수 있는 속성이 늘어나지만, 잘못 사용할 일이 생기지 않을 거라 판단했습니다. 그런데 다시 생각해보니 뷰의 속성이 어떤 화면에서 보여지느냐에 따라 사용 가능 여부가 달라지는 게 말이 안되는 것 같습니다. BindingAdapter를 지우고 Fragment에 선언하겠습니다!

2023-07-31 08:03 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/uiState/MyProfileScreenUiState.kt
> +    val events: List<ActivityUiState>
로딩, 에러, 성공 시 필요한 프로퍼티가 다르긴 하지만, 데이터 바인딩을 할 땐 위와 같은 방법이 더 편하기 때문에 위의 방법을 선택했습니다 😢

2023-07-31 08:51 UTC, chws0508 requested changes

2023-07-31 08:51 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepository.kt
> +
오케이 좋습니다

2023-07-31 08:51 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +data class MemberActivitiesBindActivityTypeApiModel(
제생각엔 이거 저희가 처음 말했던 
```
data class Activity(
id:Long.
type: ActivityType
name:String
)
```
이 데이터 모델을 공통으로 쓰는게 좋아보이긴 합니다... 
만약 이렇게 바꾸는게 이번 스프린트때는 힘들다면 다음 스프린트때 바꾸는게 좋아보여요. 지금 ActivitiesAssociatedByActivityTypeApiModel 이것만 봐도 항상 네이밍 짓기가 되게 힘들 것 같아요.

2023-07-31 08:51 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +    val memberActivityResponses: List<MemberActivityApiModel>,
저도 개인적으로 부나와 같은 의견으로 명시해주는게 좋아보이긴 합니다. 
만약 명시를 안한다고 해도, 저희 3명이 모두 명시를 안한다거나, 모두 명시를 한다거나 하는식으로 통일을 해야할 것 같습니다. (저도 명시를 해주고 있습니다)

2023-07-31 08:51 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/itemDecoration/ActivitiesAdapterDecoration.kt
> +        fun getInstance() = instance
getInstance 함수를 만든 이유가 있을까요...? 저는 instance 의 pirvate 을 빼고 아래 함수를 지우는 것이 좋아보입니다

2023-07-31 08:51 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/ActivitiesAdapter.kt
> +@BindingAdapter("myprofile_activities")
저도 부나 의견에 동의합니다. BindingAdpater로 함수를 만드는 행위가 비용이 크다고 생각하고, 추후에 가면 코드에 혼란을 불러 일으킬 것 같아서, 해당 클래스 내에 구현하는 것이 좋을 것 같습니다.

2023-07-31 08:51 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/bindingadapter/ImageViewBindingAdapter.kt
> +        .into(imageView)
```
    @BindingAdapter("imageUrl", "error")
    fun loadImage(view: ImageView, url: String?, error: Drawable?) {
        Glide.with(view.context)
            .load(url)
            .error(error)
            .centerCrop()
            .into(view)
    }
```
이런식으로 bindingAdapter 함수를 생성하면 xml 에서 어떤 에러미이지를 보여줄지 선택할 수 있습니다

2023-07-31 08:54 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +        val bnvMain = binding.bnvMain
bvn 이 뭔지 노션에 적어주세요! 나중에 이름 충돌날 수 있어요

2023-07-31 08:55 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +                R.id.mi_main_home -> changeFragment(EventsFragment())
ViewPager 2를 이용하면 더 쉽게 구현 가능할것 같아요! ViewPager 사기입니다

2023-07-31 10:14 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_myprofile_activities.xml
> +            android:id="@+id/iv_myprofile_activitynamedecorator"
저도 처음엔 위와 같은 네이밍이 단어 구분이 힘들어서 불편하다고 생각했는데, 수많은 파일이 모여있는 drawable 패키지를 볼 때 [what_where_description] 패턴이 아니라, 단어마다 언더바로 구분한다면 파일명이 모여있을 땐 보기 불편해질 것 같습니다.

2023-07-31 10:31 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
> +            Member1(
어떤 모델 클래스에서 책임지는 게 좋다고 생각하시나요?
우선 서버의 응답값을 데이터 모델로 생성하는 작업은 데이터 모델이 할 일은 아니라고 생각합니다. 비즈니스 로직이 아니기 때문입니다.
그리고 데이터 모델을 만드는 데 두 종류의 ApiModel이 필요합니다. 그래서 이 작업을 둘 중 하나에 맡긴다면 둘 중 하나는 다른 응답값에 의존하기 때문에 좋지 않다고 생각합니다. 두 ApiModel은 서로 다른 서버와의 통신에 필요하기 때문에 하나의 통신이 다른 통신에 의존하는 형태는 좋지 않다고 생각합니다!

2023-07-31 10:58 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +data class MemberActivitiesBindActivityTypeApiModel(
네이밍 짓기가 힘들지만 ApiModel의 클래스명은 꽤 자세히 적어야 한다고 생각합니다. 왜냐하면 외부 서비스의 메세지 형태는 매우 다양해질 수 있기 때문입니다.

2023-07-31 11:00 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +    val memberActivityResponses: List<MemberActivityApiModel>,
혹시 @SerialName의 값과 ApiModel의 속성명이 달라지는 경우가 있나요?
외부 서비스의 응답값이 Json일 때, 속성명이 코틀린 언어에 맞지 않는 문법으로 되어있다면 어쩔 수 없이 @SerialName을 써야하지만, 그렇지 않은 경우에는 @SerialName을 쓰는 것은 불필요하다고 생각합니다!

2023-07-31 11:03 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
> +            Member1(
아 그렇네요 제가 착각했습니다 ㅎㅎ 아니면 private 함수로 따로 뺴도 좋을 것 같아요.

2023-07-31 11:08 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
> +            Member1(
아니면 
```
val member = memberApiModel.toData()
val activities = activitiesApiModel.associate { it.getActivityType() to it.toData() }
ApiSuccess(member,activities)
```
이런 방법은 어떤가요

2023-07-31 11:26 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +                R.id.mi_main_home -> changeFragment(EventsFragment())
화면을 스와이프해서 넘기는 기능은 사용하지 않을거고 탭을 클릭했을 때 다른 프래그먼트를 단지 숨기는 걸 원하는 데, ViewPager를 사용하는 게 더 나을까요? 궁금합니다 😕

2023-07-31 11:27 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/itemDecoration/ActivitiesAdapterDecoration.kt
> +        fun getInstance() = instance
instance를 쓸거면 object로 만드는 게 더 낫겠죠?

2023-07-31 13:32 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +data class MemberActivitiesBindActivityTypeApiModel(
두 분 다 맞는 말이예요!
저도 클래스명은 구체적으로 작성하는 것이 좋다고 생각합니다.
다만, 위 클래스명은 3자가 봤을 때 오히려 너무 길어서 파악하기 힘들어 보이기도 하네요 🥲

2023-07-31 13:33 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +data class MemberActivitiesBindActivityTypeApiModel(
> 활동 타입으로 묶인 회원의 활동 목록입니다! 이름이 이상하군요!
클래스 명을 ActivitiesAssociatedByActivityTypeApiModel로 바꾸는 게 나을까요?

사실 위 네이밍도 어떤 역할을 하는지 명확히 이해하기가 힘듭니다..!
조금 더 개선된 모델명이 있을까요?

2023-07-31 13:38 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +    val memberActivityResponses: List<MemberActivityApiModel>,
저의 경우, 서버에서 제공하는 변수명은 remaningDays이지만, 클라이언트에서는 dDay로 사용하고 싶은 경우가 있었습니다.
물론 이럴 떄에도 remainingDays라는 네이밍을 서버에 요청해서 dDay로 바꾸는 것은 어떤지 상의할 수 있지만,
협업에서는 이러한 단순한 작업 하나도 과정이 너무나도 길다는 것입니다.

그래서 클라이언트는 @SerialName 어노테이션을 통해 원하는 변수명으로 변환하여 사용하기도 합니다.
토마스가 사용하는 프로퍼티명이 서버에서 제공해주는 변수명과 비교했을 때 불편하지 않다면, 위 리뷰를 반영할지 여부는 선택사항입니다.

그 외에도 어노테이션을 사용하면 IDE에서 노란색으로 표기해주기 때문에 눈에 더 확 띈다는 점은 보너스이구요!

2023-07-31 13:41 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +                R.id.mi_main_home -> changeFragment(EventsFragment())
화면이 2개라면 ViewPager까지 사용해야 하나 싶네요.
개인적으로 지금 구현도 충분하다고 생각합니다 : )
자칫하다 오버 엔지니어링이 될 수도 있다는 생각이 들어요!

2023-07-31 13:44 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/itemDecoration/ActivitiesAdapterDecoration.kt
> +        fun getInstance() = instance
아! 스캇 리뷰를 보니까 의문이 생겼습니다.
단순 ItemDecoration까지 싱글톤으로 관리하시려는 이유가 있으신가요?

2023-07-31 13:44 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/activity/Activity1.kt
> +data class Activity1(
커디 프로젝트,,, 빠른 리팩토링이 시급합니다..

2023-07-31 13:45 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_myprofile_activities.xml
> +            android:id="@+id/iv_myprofile_activitynamedecorator"
저는 그런 상황에서도 불편하다고 생각하는데, 역시 사람마다 생각하는 것이 다르군요 🤔

2023-07-31 13:55 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +            else -> throw IllegalStateException("회원의 활동 Json 데이터를 도메인 모델로 매핑하는 데 실패했습니다. 서버와 Api 스펙을 다시 상의해보세요.")
현재 커디 프로젝트에는 도메인 모델이 없어서 ActivityType이 도메인 로직을 수행할 것이라고는 생각하지 못했네요!
도메인 로직은 도메인 모델이 수행해야 하지 않을까요?
지금은 서버에서 모든 로직을 처리해주고, 사실상 값만 전달해주기 때문에 데이터 모델로 보고 작업해주셔도 무방하다고 생각이 듭니다.

또한, 위와 같은 상황을 위해, 데이터 모델과 도메인 모델이라는 개념이 각각 존재하는 것이 아닐까 싶네요 : )

2023-08-01 01:38 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
> +        val activitiesResponseDeferred = async { memberService.fetchActivities() }
다시 생각해보니 ActivityRepository에서 Activity를 반환하는 게 더 좋아보이네요! 수정하겠습니다.

2023-08-01 01:46 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +data class MemberActivitiesBindActivityTypeApiModel(
저도 길면 가독성이 떨어진다는 것에 공감하지만, 짧으면서 ApiModel의 정확한 의미를 반영하는 이름이 떠오르지 않네요ㅠㅠ

2023-08-01 04:17 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesBindActivityTypeApiModel.kt
> +    val memberActivityResponses: List<MemberActivityApiModel>,
서버에서 제공하는 변수명이 무슨 뜻인지 알기 힘든 경우 @SerialName을 사용하는 것이 좋아보이네요!
이러한 경우에 대비하기 위해 @SerialName을 사용하는 것은 좋다고 생각이 들었습니다.
@SerialName을 사용하지 않았을 때  dto의 변수명을 바꾸려면 새로 @SerialName 애노테이션을 추가해야 하므로 처음부터 서버와 통신하기 위한 이름, 개발자가 쉽게 파악하기 위한 이름을 따로 구분하는 게 좋아보이네요 👍

2023-08-01 05:18 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
> +        }
인텐트를 생성하고 액티비티를 시작하는 두 작업을 한 줄에 작성하는 게 더 보기 좋을까요? ❓ 궁금하네요ㅠㅠ

2023-08-01 05:48 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/itemDecoration/ActivitiesAdapterDecoration.kt
> +        fun getInstance() = instance
여러 리사이클러 뷰에 같은 ItemDecoration 인스턴스를 설정하기 위함이었습니다.
생각해보니 싱글톤이 아니라 그냥 ItemDecoration을 생성하고 생성된 인스턴스를 설정해주면 되는 거였네요!

2023-08-01 08:59 UTC, chws0508 approved these changes

2023-08-01 09:06 UTC, merged