Feature/#217-행사 목록 조회 API 필터링 옵션 수정
woowacourse-teams/2023-emmsale pull request #218
Opened 2023-08-06 11:04 UTC by amaran-th

## #️⃣연관된 이슈
#217

## 📝작업 내용
- 진행 상황을 EventStatus의 리스트로 받아오고 필터 조건을 OR로 계산.
- 태그를 리스트로 받아오고 필터 조건을 OR로 계산.
- 날짜를 year, month 대신 startDate, endDate로 받고, 연/월 뿐만 아니라 일을 포함하게 함
- startDate만 입력하는 경우, 해당 일 이후의 행사들을 조회
- endDate만 입력하는 경우, 해당 일 이전의 행사들을 조회

## 예상 소요 시간 및 실제 소요 시간
4시간/3시간

## 💬리뷰 요구사항(선택)
혹시나 누락된 테스트가 보이거나, 추가적으로 검증했으면 좋겠다 싶은 로직이 있으면 코멘트 부탁드립니다.

2023-08-07 07:23 UTC, hong-sile requested changes
데모데이 끝나고 첫 리뷰라 이거저거 많이 썼네요 확인하고 반영부탁드립니다.

2023-08-07 07:23 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +    List<Tag> tags = tagNames.stream().map(tagName ->
이 부분은 in절로 조회할 수 있지 않을까요? 너무 많은 쿼리가 날아갈 것 같아요

2023-08-07 07:23 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +        .filter(event -> tagedEvents.contains(event)).collect(toList());
스트림을 사용했다면, 점 하나에 한번의 줄바꿈을 해주면 더 잘 보일 것 같아요

2023-08-07 07:23 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +  private List<Event> filterByTags(List<Event> events, final List<String> tagNames) {
final을 붙였다면 다 붙여주는 식으로 가면 어떨까요?

2023-08-07 07:23 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +    List<Event> tagedEvents = eventTagRepository.findEventTagsByTagIn(tags)
EventTag에서 다 조회하기 보다, 기존에 있는 events에서 필터링을 할 수 있지 않았을까요?

2023-08-07 07:23 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
> +        parameterWithName("statuses").description("필터링하려는 상태(option)").optional()
이 statuses가 이미 정해진 값인 걸로 아는데,
어떠한 값이 올수 있는지도 description에 적어주면 좋지 않을까요?

2023-08-07 07:23 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
>    }
제 테스트 코드 돌려주세요 어디간거죠

```java

  @Test
  @DisplayName("이미 Event에 멤버가 참여헀는지 확인할 수 있다.")
  void isAlreadyParticipate() throws Exception {
    //given
    final Long memberId = 2L;
    final Long eventId = 3L;
    given(eventService.isAlreadyParticipate(eventId, memberId)).willReturn(true);

    //when && then
    mockMvc.perform(
            get("/events/{eventId}/participants/already-participate?member-id={memberId}"
                , eventId, memberId)
        )
        .andExpect(status().isOk())
        .andDo(document("check-already-participate"));
  }
```

2023-08-07 07:23 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +          .comparingOnlyFields("name", "status")
혹시 두 상태만 비교하는 이유가 있을까요?

2023-08-07 07:23 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +          .comparingOnlyFields("name", "status")
요기도 이 상태만 비교하는 이유가 있을까요?

2023-08-07 09:51 UTC, amaran-th commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +          .comparingOnlyFields("name", "status")
행사들을 식별하는 데는 두 정보면 충분할 것이라 생각했기 때문입니다! status는 관련 연산이 정상적으로 이루어지는지 확인하기 위함이기도 하구요.

2023-08-07 09:52 UTC, amaran-th commented on backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
> +        parameterWithName("statuses").description("필터링하려는 상태(option)").optional()
반영했습니다!

2023-08-07 09:54 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +  private List<Event> filterByTags(List<Event> events, final List<String> tagNames) {
반영했습니다~

2023-08-07 10:44 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +    List<Event> tagedEvents = eventTagRepository.findEventTagsByTagIn(tags)
반영했습니다~

2023-08-08 01:15 UTC, hong-sile approved these changes
제 리뷰는 반영한 것 같아서 approve하겠습니다.

2023-08-08 01:17 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +          .comparingOnlyFields("name", "status")
아 이걸 못 봤네요. 지금 당장은 두가지 필드만 볼 수 있어도 나중에 eventResponse 에 대한 변경이 있을 때 그에 대한 검증도 할 수 있잖아요. 굳이 comparingOnlyFileds를 붙일 필요는 없는 것 같아요.

안 붙여도 잘 통과하는 테스트지 않나요?

2023-08-08 01:18 UTC, hong-sile reviewed
하나를 못 봤네요 남긴 의견은 제 개인적인 생각이고,
만약 아마란스가 납득이 안 된다 하시면 적용하지 않아도 괜찮습니다.
사실 중요하지 않은 NIT라서

2023-08-08 01:20 UTC, java-saeng requested changes
고생하셨습니다 !!

리뷰 반영하시고 다시 재요청 주세요!

2023-08-08 01:20 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +  private static boolean isExistFilterDate(final String startDate, final String endDate) {
아마 method extract 하면서 static 이 생긴 것 같은데 인스턴스 메서드에서 호출하는거면 굳이 static 을 붙이지 않아도 될 것 같은데 static 을 해주신 이유가 있을까요?

2023-08-08 01:20 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +  public List<EventResponse> findEvents(final EventType category, final LocalDate nowDate,
requestChange가 여기밖에 없어서 여기에 리뷰 남길게요

위에 

```java
throw new EventException(EventExceptionType.NOT_FOUND_PARTICIPANT);
```

중괄호가 필요없을 것 같습니다

2023-08-08 01:20 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +    if (isExistFilterDate(startDate, endDate)) {
모든 이벤트를 불러와서 여기서 필터링하는 것 같은데
DB에 쿼리를 날려서 가져올 수 있지 않을까요??

물론 행사들의 개수가 엄청 많을 것 같진 않지만 DB에서 먼저 걸러서 가져오면 코드 보기에도 편하고, 이렇게 많은 필터 코드들이 사라지지 않을까 생각듭니다.

2023-08-08 04:06 UTC, amaran-th commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +          .comparingOnlyFields("name", "status")
음 사실은 처음에 실제 결과와 비교할 Response 객체의 필드들을 일일이 정의해주기 번거로워서 행사 식별을 위한 최소한의 데이터만 비교해준 것이긴 합니다. status는 엔티티 필드가 아니고 직접 계산해주어야 하는 속성이라 추가했구요
홍실 말씀도 충분히 이해가 되지만 현재 지적해주신 테스트들은 특정 행사에 대한 기능이 아니라 행사 목록에서 정렬하고, 필터링하고, 그룹핑하는 로직을 검증하는 데 초점이 맞춰져있어서 당장은 name 외의 필드까지 비교할 필요는 없다고 생각이 듭니다!

2023-08-08 04:12 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +  private static boolean isExistFilterDate(final String startDate, final String endDate) {
아 말씀해주신대로 메서드 추출 과정에서 붙은 것 같습니다.
반영해서 static 키워드 제거하고 메서드 위치도 원래대로 돌려놓았습니다~!

2023-08-08 04:14 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +  public List<EventResponse> findEvents(final EventType category, final LocalDate nowDate,
확인하고 수정하려고 했으나 컴파일 에러가 발생하네요.
중괄호가 꼭 필요한 포맷인 것 같습니다!
![image](https://github.com/woowacourse-teams/2023-emmsale/assets/81465068/2360938a-5d96-4b6f-9bdf-11d1441d631e)

2023-08-08 04:27 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +    if (isExistFilterDate(startDate, endDate)) {
날짜, status같은 경우 DB 컬럼으로 정의되어 있지 않고 직접 연산해서 그룹핑/필터링하는 방식이라 DB에서 직접 필터링한다면 카테고리+태그 필터링만 쿼리문으로 대체할 수 있을 것 같아요.
하지만 태그는 행사 당 여러 개를 가질 수 있고, 필터링할 태그는 복수로 선택할 수 있기 때문에 쿼리가 필터링할 태그의 개수만큼 반복 호출될 것 같아요.
그래서 저는 성능적으로 봤을 때 기존 방식이 최선이 아니지 않을까 싶습니다!

2023-08-08 05:15 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +  public List<EventResponse> findEvents(final EventType category, final LocalDate nowDate,
아 Exception 던지는 건 있어야하나 봅니다. 하나 배웁니다~

2023-08-08 10:27 UTC, chws0508 commented
잘하셨어요

2023-08-08 10:35 UTC, java-saeng approved these changes
고생하셨습니다 !

2023-08-08 10:35 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
>  public class EventService {
해당 클래스에서만 사용하는 상수면 private 어떠신가요?

2023-08-08 10:35 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> -    final Long memberId = request.getMemberId();
약자보다는 의미있는 네이밍 사용하시는게 어떤가요?

2023-08-08 10:46 UTC, merged