Feature/#266 토마스 코드 리팩토링
woowacourse-teams/2023-emmsale pull request #267
Opened 2023-08-09 07:30 UTC by ki960213

## #️⃣연관된 이슈
> #266

## 📝작업 내용
> 댓글 화면 및 내 프로필 화면 관련 코드 리팩토링

### 스크린샷 (선택)

## 예상 소요 시간 및 실제 소요 시간
> 이슈의 예상 소요 시간과 실제 소요된 시간을 분 or 시간 or 일 단위로 작성해주세요.
> 
> 1시간/1시간

## 💬리뷰 요구사항(선택)

> ktlint 적용했지만 ConferenceFilterViewModel 코드만 ktlintcheck 실패했습니다. 이 부분은 무시해주세요!

2023-08-09 07:32 UTC, tmdgh1592 reviewed
`ConferenceFilterViewModel`은 제가 수정해서 올리도록 하겠습니다.

2023-08-09 08:30 UTC, chws0508 requested changes

2023-08-09 08:30 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentViewModel.kt
> +                _uiState.postValue(_uiState.value.copy(isNotLogin = true))
사실 현 상태에서 비로그인 기능을 생각하지 않았기 때문에 이코드는 지금 필요하진 않다고 생각합니다. 만약 로그인되지 않았다면 백엔드에서 로그인되지 않았다고 알려주고 앱을 터트리는게 좋을 것 같아요.

2023-08-09 08:30 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentViewModel.kt
> +                    loginMember = loginMember,
함수가 너무 길어서 분리가 필요해 보여요

2023-08-09 08:30 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
>          }
이것도 마찬가지로 나중에 비로그인 기능이 생겼을 때 추가하는게 좋아보입니다. 현재로서는 비로그인이라면 에러를 터트려야 할 것 같아요

2023-08-09 08:30 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentViewModel.kt
> +                    loginMember = loginMember,
이것도 함수 분리를 해야할 것 같아요

2023-08-09 08:31 UTC, tmdgh1592 requested changes
코드 수정하느라 고생하셨습니다!
리뷰를 남겼으니 확인 후에 다시 리뷰 요청해주세요~ 😃

2023-08-09 08:31 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/uiState/CommentsUiState.kt
> +    val isCommentDeletionError: Boolean,
ui의 에러에 대해 구체적으로 작성해주신 것이 인상적이예요! 👍

2023-08-09 08:31 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentViewModel.kt
> +            isCommentDeletionError = true,
메서드 분리하니까 훨씬 보기 깔끔하네요 👍

2023-08-10 06:31 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentViewModel.kt
>              @Suppress("UNCHECKED_CAST")
빌드할 때 경고문 띄우지 않으려고 붙혔습니당 😆

2023-08-10 06:38 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentViewModel.kt
> +                _uiState.postValue(_uiState.value.copy(isNotLogin = true))
앱을 사용하다가 로그아웃이 되는 경우는 충분히 일어날 수 있는 일이라고 판단한다면 로그인 화면으로 이동시키는 게 옳고, 절대 일어나지 않을 일이고 그게 의도한 거라면 앱을 터트리는 게 옳다고 생각합니다. 저는 로그아웃이 될 수 있다고 생각합니다. 지금은 그렇게 구현하지 않았지만, 이후에 보안을 위해 특정 기기에서 로그인했을 때 다른 기기가 로그아웃되도록 구현한다면 앱을 사용하다가 로그아웃 될 수 있기 때문에 로그인 화면으로 이동시키도록 구현했습니다. 스캇은 어떻게 생각하시나요?

2023-08-10 06:40 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
>          }
비로그인 기능이 생겼을 때를 대비하여 로그인 화면으로 이동하도록 구현했습니다. 비로그인일 때 로그인 화면으로 이동하도록 하나, 에러를 터트리도록 하나 저희가 의도한 대로 구현했다면 앱을 사용하다가 비로그인이 되는 일이 발생하지 않기 때문에, 미래를 고려해 로그인 화면으로 이동하도록 했습니다 😄

2023-08-10 06:41 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/uiState/ChildCommentsUiState.kt
>              childComments = listOf(),
타입 적으면 
<img width="707" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/f3eb29ad-bb43-42d5-8e43-e15434de37ba">
IDE가 지우길 권장하네요 😢

2023-08-10 06:51 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentFragment.kt
> +            context?.showToast(getString(R.string.comments_comments_deletion_error_message))
댓글을 가져오기가 실패한 상태와 댓글을 수정이 실패하는 상태가 독립적으로 바뀔 수 있다고 생각해서 함수를 분리하도록 구현하겠습니다 😄

2023-08-10 06:51 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileFragment.kt
> +            context?.showToast(getString(R.string.myprofile_profile_fetching_error_message))
위와 동일합니다 :)

2023-08-10 06:51 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
> +                    is ApiSuccess -> setMember(result.data)
몰랐네요 감사합니다 👍

2023-08-10 06:52 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
>          )
login이 되었는지에 대한 상태는 Profile 데이터와 상관없으므로 따로 분리했습니다 :)

2023-08-10 07:08 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
>              clubs = activities.getActivityUiStatesOf(ActivityType.CLUB),
ActivityUiState 클래스가 List<ActivityUiState>를 생성하도록 하는 것은 어색하다고 생각합니다 😢

2023-08-10 08:37 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
>              clubs = activities.getActivityUiStatesOf(ActivityType.CLUB),
흠.. 그럴 수 있겠네요!
단수가 복수를 만들어내는 느낌?ㅋㅋ
좋습니다.

2023-08-10 08:38 UTC, tmdgh1592 approved these changes
리뷰를 잘 반영해주셨네요~
전 더 리뷰를 남길 것이 없어서 먼저 approve 하겠습니다.

2023-08-10 10:22 UTC, chws0508 approved these changes

2023-08-10 10:22 UTC, merged