Feature/#265 부나 코드 리팩토링
woowacourse-teams/2023-emmsale pull request #270
Opened 2023-08-09 08:34 UTC by tmdgh1592

## #️⃣연관된 이슈
>  ex) #251 

## 📝작업 내용
> 컨퍼런스, 컨퍼런스 필터 코드를 리팩토링하였습니다.

### 스크린샷 (선택)

## 예상 소요 시간 및 실제 소요 시간
> 1시간 / 1시간
> ex) 예상시간/걸린시간 => 2시간/3시간

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2023-08-09 14:21 UTC, chws0508 requested changes
필터 화면에서 전체를 누르면 전체 태그 색깔이 안바끼는것 같습니다 ㅎㅎ

2023-08-09 14:21 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
>          fetchConference()
여러개의 Conference 들을 가져오는거라 복수형 붙여야 할 것 같아요

2023-08-09 14:21 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
> +    private fun updateFilterViews(eventFilters: ConferenceFiltersUiState) {
eventFilters -> conferenceFilters 로 네이밍 바꿔주시면 좋을 것 같아요. 약간 헷갈리네요

2023-08-09 14:21 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
> +    private fun updateConferenceStatuses(eventStatuses: List<ConferenceFilterUiState>) {
updateConferenceStatuses -> updateStatusFilters 가 나을것 같아요

2023-08-09 14:21 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
>      private fun updateConferenceTags(eventTags: List<ConferenceFilterUiState>) {
이것도 updateConferenceTags -> updateTagsFilters 가 나을 것 같아요

2023-08-09 14:21 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
> +        removeTagFiltersExcludingAllTag()
모든 태그를 제외하고 Tag Filters 를 삭제한다는 것이 잘 이해가 안가요 ㅠㅠ

2023-08-10 02:11 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
>          fetchConference()
반영 완료하였습니다!

2023-08-10 02:15 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
> +    private fun updateConferenceStatuses(eventStatuses: List<ConferenceFilterUiState>) {
좋습니다.
각각 `updateStatusFilters()`, `updateTagFilters()` 로 변경 완료하였어요!

2023-08-10 02:19 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
> +        removeTagFiltersExcludingAllTag()
`전체` 태그는 삭제되지 않는데 removeAllTagFilters()라고 하면 헷갈릴 수 있다고 생각해서 위와 같은 네이밍을 선택했습니다.

2023-08-10 02:23 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
> +                !eventsResult.isError -> {
앗 지금 보니까 코드에 문제가 조금 있네요.
!eventsResult.isError 뿐만 아니라, isLoading이 아닌지도 체크를 해야 할 것 같습니다.

2023-08-10 02:28 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
> +                !eventsResult.isError -> {
위 코드는 `if else`가 더 적절해보이는데, 아래 코드처럼 변경되면 when도 괜찮다고 생각해요!
```kotlin
when {
    !eventsResult.isLoading -> {
        eventAdapter.submitList(eventsResult.events)
        binding.tvEventsCount.text =
            getString(R.string.event_count_format, eventsResult.eventSize)
    }
}
```

2023-08-10 02:29 UTC, tmdgh1592 commented
> 필터 화면에서 전체를 누르면 전체 태그 색깔이 안바끼는것 같습니다 ㅎㅎ
혹시 의도하신 걸까요?

전혀 의도하지 않는 버그인데 캐치해주셔서 감사합니다.
수정하고 다시 리뷰요청 드릴게요!

2023-08-10 02:48 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
>      inner class ConferenceFilterOnBackPressedCallback : OnBackPressedCallback(true) {
UX 측면에서 확실히 필터 적용이 안 되는게 좋을 것 같아요!
그리고 뒤로가기할 때에는 Dialog로 한 번 더 물어봐도 좋을 것 같구요 : )

2023-08-10 02:57 UTC, ki960213 reviewed
필터링 쪽에서 처음에 이해하기 힘들었던 이유가 이름이 명확하지 않아서 그랬던 거 같습니다 😢 
필터링할 때 특정 데이터를 포함하도록 하는 어떤 조건을 filter라고 이름을 정의해서 약간 이해하기 힘들었습니다
그러한 조건들을 filter라는 이름보단 option이라는 이름으로 정하는 게 어떨까요?

2023-08-10 02:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferencesUiState.kt
> +        )
컨퍼런스 하나를 이용해서 ConferencesUiState를 만드는 게 어색해요 😢 
ConferenceUiState로 이름을 바꾸거나, 시그니처를 from(conferences: List<Conference>)로 바꾸면 좋을 것 같아요

2023-08-10 02:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
>              }
when 문은 위의 조건부터 차례차례 검증하기 때문에, 아래 조건들은 위의 조건을 만족하지 않아야만 실행될 수 있어요.
따라서 
```suggestion
            when {
                eventFilters.isError -> showToast(getString(R.string.all_data_loading_failed_message))
                !eventFilters.isLoading -> updateFilterViews(eventFilters)
            }
```
이렇게 써도 될 것 같아요!

2023-08-10 02:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
>      private fun updateConferenceTags(eventTags: List<ConferenceFilterUiState>) {
eventTags -> conferenceTags가 더 나을 것 같아요

2023-08-10 02:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
> +    val eventFilters: NotNullLiveData<ConferenceFiltersUiState> = _eventFilters
행사들을 조회할 때 필터링할 때 사용할 옵션들을 화면에서 나열하기 때문에 eventFilters가 아니라 conferenceFilterOptions라고 이름을 정하면 좀 더 명확할 것 같아요!

2023-08-10 02:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFilterUiState.kt
> +    fun toggleSelection(): ConferenceFilterUiState = copy(isSelected = !isSelected)
필터링 옵션의 선택 상태가 바뀐 **필터링 옵션을 반환**하는 함수이므로 toggleSelection -> toggledSelection으로 바꾸면 좋을 것 같아요

2023-08-10 02:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFiltersUiState.kt
> +    fun toggleFilterSelection(filterId: Long): ConferenceFiltersUiState = copy(
위처럼 toggledFilterSelection으로 바꾸면 좋을 것 같아요

2023-08-10 02:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFiltersUiState.kt
> +    fun resetSelection(): ConferenceFiltersUiState = copy(
위처럼 resetedSelection으로 바꾸면 좋을 것 같아요

2023-08-10 02:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
>      fun addSelectedTagFilterCount(count: Int) {
viewModel을 사용하는 Activity가 선택된 태그 옵션 개수를 갱신하는 게 아니라, viewModel에게 특정 태그 옵션을 선택 및 해제하도록 요청하면 viewModel이 스스로 선택된 태그 옵션 개수를 조정하는 게 더 좋은 책임 할당인 것 같아요

2023-08-10 02:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
>      }
외부에서 직접 UiState를 설정해주는 것은 잘못된 것 같아요.
이벤트가 발생하면 ViewModel이 그 이벤트에 맞게 UiState를 설정하는 게 더 좋을 것 같아요.

2023-08-10 03:37 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferencesUiState.kt
> +    val eventSize: Int = events.size
events.size로도 가능하지만, eventSize만 필요한 시점에서 events 전체를 get하는 것이 오히려 불필요하다고 생각합니다.

2023-08-10 03:41 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
> +        1002L -> ConferenceStatus.ENDED
아직 API가 없는 상태라 위와 같이 작성하였지만,
서버에서 받아온다고 가정하고 Repository로 만들어보겠습니다.

2023-08-10 04:14 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferencesUiState.kt
> +        )
> ConferenceUiState로 이름을 바꾸거나

이게 적당할 것 같습니다~

2023-08-10 04:19 UTC, tmdgh1592 commented
> 필터링할 때 특정 데이터를 포함하도록 하는 어떤 조건을 filter라고 이름을 정의해서 약간 이해하기 힘들었습니다
그러한 조건들을 filter라는 이름보단 option이라는 이름으로 정하는 게 어떨까요?

filter라고 하면 프로그래밍에서는 동사처럼 들리기도 하고, Collection의 filter가 생각나기도 해서 가독성이 떨어지는 단어 중 하나인 것 같습니다.
`option`이라는 워딩이 읽기에도 둥글둥글한 느낌이라 편하기도 하네요!

Activity를 제외하고는 관련 클래스 네이밍 수정을 진행하겠습니다.

2023-08-10 04:30 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
>      }
데모데이에 맞추어 빠르게 개발하다보니, UiState를 두 클래스에서 그대로 사용하도록 구현하였습니다.
저 또한, 각자의 화면 변경에 영향을 받지 않도록 구현하려면 UiState를 별도로 관리하는 것이 좋다고 생각합니다.
리팩토링 하도록 할게요~!

2023-08-10 04:33 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFiltersUiState.kt
> +    fun toggleFilterSelection(filterId: Long): ConferenceFiltersUiState = copy(
메서드명은 동사로 짓는 것이 가독성이 좋다고 생각합니다.
말씀하신대로 `toggledFilterSelection` 이라고 하려 한다면, 메서드보다는 프로퍼티일 때가 적절하겠습니다.

2023-08-10 04:33 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFiltersUiState.kt
> +    fun resetSelection(): ConferenceFiltersUiState = copy(
위와 동일한 의견입니다.

2023-08-10 04:37 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
>              }
사실 처음에는 가독 측면에서 두 조건을 추가했었습니다.
하지만 스캇 리뷰를 반영하면서, 이미 아래와 같이 변경되었습니다! 🤣

2023-08-10 04:41 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
>      private fun updateConferenceTags(eventTags: List<ConferenceFilterUiState>) {
스캇 코드 리뷰를 반영하면서, 조금 더 구체적인 네이밍인 `updateTagFilters()` 로 변경되었습니다.

2023-08-10 04:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
> +    val eventFilters: NotNullLiveData<ConferenceFiltersUiState> = _eventFilters
여러 사람들에게 여쭤보니, filter와 option이 결국 여기에서 같은 의미라고 느껴져서 함께 사용하는 것이 부자연스럽게 느껴진다고 합니다.
eventFilters를 `conferenceFilters`라고만 변경해도 이해하는데 크게 문제가 없다고 생각해요!

2023-08-10 05:13 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFilterUiState.kt
> +    fun toggleSelection(): ConferenceFilterUiState = copy(isSelected = !isSelected)
위와 동일한 리뷰입니다.
함수명은 동사로 네이밍하는 것이 좋다고 생각해요.

2023-08-10 06:16 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
> +        1002L -> ConferenceStatus.ENDED
서버에서 받아오지 않아도 데이터는 Repository에서 가져오도록 통일하면 좋을 것 같아요!

2023-08-10 06:19 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
> +    val eventFilters: NotNullLiveData<ConferenceFiltersUiState> = _eventFilters
이에 맞게 메서드 명이 filters로 정의된 것들을 filter 혹은 options라는 단어를 사용하도록 바꿔도 좋을 것 같아요!

2023-08-10 06:22 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFiltersUiState.kt
> +    fun toggleFilterSelection(filterId: Long): ConferenceFiltersUiState = copy(
메서드 명을 동사로 짓는 이유는 무언가 명령할 때 문장이 동사로 시작하기 때문입니다. 따라서 상태가 변한 객체를 반환하도록 한다면 
<img width="374" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/3d0ff26e-f7b8-44d3-86f9-dc1286d801e5">
이것처럼 네이밍 해도 괜찮을 것 같아요~

2023-08-10 06:35 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
>      fun addSelectedTagFilterCount(count: Int) {
addSelectedTagFilterCount() 말씀하시는 거겠죠??
저도 그렇게 생각합니다! 해당 메서드는 스캇 코드 리뷰 과정에서 제거되었습니다 : )

2023-08-10 06:38 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
>      fun addSelectedTagFilterCount(count: Int) {
추가로, 리뷰하시고자 하는 영역만 드래깅해주시면 좋을 것 같아요~
addSelectedTagFilterCount()를 리뷰하시고 싶으셨던 것 같은데, 리뷰 영역은 한 줄이고 나머지는 거진 10줄이라 처음에 글을 파악하기가 힘들었습니다. 😥
![11113](https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/bf8f1c9c-d990-45a6-a106-e5e7fc173e15)

2023-08-10 13:03 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
>      fun addSelectedTagFilterCount(count: Int) {
죄송합니당 ㅠㅠ 더 신경쓰겠습니다 😢

2023-08-10 15:51 UTC, ki960213 reviewed
괜히 혼란을 준 것 같아 죄송합니다ㅠㅠ
컨퍼런스 필터를 클래스로 표현해본다면
```
class ConferenceFilter {
    fun getFilteredConferences(conferences: List<Conference>, filteringCondition: ConferenceFilteringCondition): List<Conference> {
        return conferences.filter { conference -> conference.status in filteringCondition.statuses }
            .filter { conference -> filteringCondition.eventTags.all { it in conference.eventTags }
            .filter { conference -> conference.startDate in filteringCondition.duration }
    }
}

data class ConferenceFilteringCondition(
    val statuses: List<ConferenceStatus>,
    val eventTags: List<EventTag>,
    val duration: Duration
)

data class Duration(
    val startDate: LocalDateTime,
    val endDate: LocalDateTime,
) {
    operator fun contains(dateTime: LocalDateTime): Boolean = ...
```
이렇게 표현할 수 있을 것 같습니다. 하지만 시간이 없으니 이름 정하는 것은 조금 미뤄야 할 것 같아요ㅠㅠ

2023-08-10 15:51 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
> +    private val selectedEndDate: ConferenceFilteringDateOptionUiState? = null,
뷰모델을 생성할 때 선택된 날짜를 입력받는 이유가 뭔지 궁금합니다.
뷰모델을 생성하고 나서 선택된 날짜를 업데이트 해주어도 괜찮지 않을까요?

2023-08-10 23:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
> +                        getString(R.string.event_count_format, eventsResult.conferenceSize)
놓친 부분이네요!
수정하도록 하겠습니다 🙂

2023-08-10 23:51 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
>                  }
화면을 그려주는 Acticity는 어쩔 수 없이 ViewModel의 행동에 의존할 수 밖에 없습니다.
행동에 따라 UIState의 값이 달라지기 때문이죠.
또한 위 코드는 행동에 직접적으로 의존하고 있지도 않습니다.


> Activity가 ViewModel이 어떻게 동작할지(isError == false일 때 events와 eventSize가 변할거라는 사실) 알 필요는 없다고 생각합니다.

과연 그럴까 정말 의문이네요 🤔
그렇다면 isError, isLoading인 경우에도 화면에 로딩창을 띄워주기.. 에러 문구를 표시하기.. 또한 이루어질 수 없다고 생각합니다.

추가로 매번 상태가 달라질 때마다 화면을 새로 갱신(ViewGroup의 View를 모두 제거하고 다시 그리기) 하는 것이 정말 좋은 구현일까요?

2023-08-10 23:52 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
>                  }
만약 토마스가 말씀하신대로 구현해야 한다면, 이전에 말씀하신대로 View를 그리는 리스트를 그대로 유지하는 것이 아닌 emptyList()로 초기화해주는 것이 적절할 것 같아요.
그런 것이 아니라면 위 조건이 필요하다고 생각합니다 : )

2023-08-10 23:54 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
> +                    eventAdapter.submitList(eventsResult.conferenceItems)
위와 동일한 의견입니다.

2023-08-10 23:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
> +    private val selectedEndDate: ConferenceFilteringDateOptionUiState? = null,
기존 코드는 Testable한 ViewModel을 만들기 위해 시작, 종료날짜를 입력받았습니다.
하지만 지금은 각 항목별로 업데이트할 수 있는 메서드가 추가되었기 때문에 필요 없을 것 같아요!

2023-08-11 00:01 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
> +    )
기존에는 EventRepository였는데 코드를 한 번에 바꾸다가 실수로 이 부분도 바뀌어버린 것 같습니다 🥲
다시 EventRepository로 변경해야 할 것 같아요.

2023-08-11 02:05 UTC, chws0508 requested changes
고생하셨습니다^^ 아주 적은 몇가지 코멘트만 남겨놓았습니다^^

2023-08-11 02:52 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
>          binding.btnEventFilter.setOnClickListener { navigateToEventFilter() }
추천해주신 명확한 네이밍으로 변경하였습니다.

2023-08-11 02:52 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
> +    ) = conferenceRepository.getConferences(
놓친 부분이었는데 캐치해주셔서 감사합니다!

2023-08-11 02:54 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
> +    fun updateConferenceFilter(
좋습니다!
fetchFilteredConferences()로 변경하였어요 : )
내부적으로 서버로부터 fetch하는 과정이 있어서 update보단 fetchXxx 라는 네이밍이 좋을 것 같아요!

2023-08-11 03:06 UTC, chws0508 approved these changes
고생했어요^^

2023-08-11 04:21 UTC, ki960213 approved these changes
리뷰를 잘 반영하셔서 더 이상 리뷰 하고 싶은 부분이 보이지 않네요 👍

2023-08-11 04:25 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFilterUiState.kt
> +    fun toggleSelection(): ConferenceFilterUiState = copy(isSelected = !isSelected)
[논의 결과]
결론적으로 상태를 변환한 값을 반환하므로, `toggled()` or `toggledBy()`로 결정되었습니다.

2023-08-11 05:02 UTC, merged