Feature/#245 유저 게시글 신고하기 및 신고함 조회 기능
woowacourse-teams/2023-emmsale pull request #272
Opened 2023-08-09 11:52 UTC by amaran-th

## #️⃣연관된 이슈
#245

## 📝작업 내용
사용자 게시물 신고하기 API 및 신고 목록 조회 API 구현

## 예상 소요 시간 및 실제 소요 시간
3시간/3시간 30분

## 💬리뷰 요구사항(선택)
이 기능은 신고 정책이 명확해지고 차단기능 구현이 완료된 후에 한 번 더 작업하겠습니다.
지금 구현된 부분은 레거시로 봐주시면 될 것 같아요.
혹시 신고 정책 관련해서 의견이 있으시면 코멘트로 남겨주세요! 제가 정리해서 스크럼 때 이야기 꺼내보겠습니다.

2023-08-09 12:29 UTC, hyeonjerry approved these changes
크게 수정할 점은 보이지 않습니다.
나중에 신고하면 자동으로 차단도 할 것인지에 대해서도 논의해 보아야겠네요.
수고하셨습니다.

2023-08-09 12:29 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/report/application/dto/ReportResponse.java
> +  @JsonFormat(pattern = "yyyy:MM:dd:HH:mm:ss")
개인적인 의견입니다.
년/월/일과 시간이 모두 :로 구분되어 있으면 혹시 안드 입장에서 날짜와 시간을 따로 파싱하기 힘들지 않을까요?

2023-08-09 12:29 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/report/domain/Report.java
> +  private String content;
혹시 content를 받는게 아니라  ReportType이 있으니 id를 받는건 어떻게 생각하시나요?
예를 들어 id가 1이고 ReportType이 Comment면 1번 id의 comment를 찾을 수 있도록이요

2023-08-09 13:16 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/report/application/dto/ReportResponse.java
> +  @JsonFormat(pattern = "yyyy:MM:dd:HH:mm:ss")
제리 의견에 동의합니다!
하지만 해당 날짜 포맷은 다른 일부 dto에서도 공통적으로 사용하고 있는 양식이라, 제쪽에서만 수정하기보단 언제 한 번 백엔드분들과 논의를 해서 날짜 포맷을 통일시키고 일괄적으로 수정하는 작업을 하는 게 좋을 것 같습니다!
![image](https://github.com/woowacourse-teams/2023-emmsale/assets/81465068/76a4fccd-646d-4618-a715-81c9ce20917e)

2023-08-09 13:30 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/report/domain/Report.java
> +  private String content;
음음 저도 고민했던 방식인데 어느 방식이 더 나을지 확신이 잘 안서서, 추후 신고 정책 결정할 때 얘기해보겠습니다!

2023-08-10 05:25 UTC, hong-sile reviewed
신고관련된 부분은 논의를 해봐야하니까 나중에 이야기해보죠

2023-08-10 05:25 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/report/application/dto/ReportResponse.java
> +  @JsonFormat(pattern = "yyyy:MM:dd:HH:mm:ss")
이 부분에서 디자이너 분 포맷을 보니까 화면마다 필요한 포맷이 다르더라고요.

그 행사 일정 나타낼때는 yyyy:MM:dd HH:mm이 쓰이고.
다른 게시글에서 날짜 보여줄 때는 yyyy:MM;dd가 쓰이는 식으로

화면에 보여주는 형식 그대로 나타내면 될 것 같아요.

2023-08-11 01:15 UTC, hong-sile approved these changes

2023-08-14 08:31 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/report/application/ReportCommandService.java
> +  }
이 메서드부터 코드 중복이 많이 발생하는데, 이를 줄일 수 있는 방법이 있을까요?
혼자 고민해봤는데 마땅한 해결책이 떠오르지 않더라구요...
혹시 아이디어 있으면 알려주시면 감사하겠습니다!

2023-08-14 11:05 UTC, java-saeng requested changes
고생하셨습니다

커멘트에 남긴 글들 확인해주시고 재요청주세요~

2023-08-14 11:05 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/report/application/ReportCommandService.java
> +    if (!comment.getMember().getId().equals(reportRequest.getReportedId())) {
tell don't ask 를 한번 검색해보시는 것도 좋아보입니다

validateRecruitmentPost, validateRequestNotification 이거 포함해서요~

2023-08-14 11:05 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/report/application/ReportCommandService.java
> +  }
이건 어쩔 수 없을 것 같은데요? 타입마다 접근하는 repository가 달라서요 이게 최선일 것 같은데요?

2023-08-14 12:46 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/report/application/ReportCommandService.java
> +  }
흠,, 이건 type마다 다 다른 repository가 필요해서,, 어쩔 수 없을 것 같다는 생각이 듭니다,,

2023-08-14 13:27 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/report/api/ReportApi.java
> +  public ReportResponse create(@RequestBody final ReportRequest reportRequest, Member member) {
아! 마지막에 한 번 더 확인했어야했는데 깜빡했네요;;;
찾아주셔서 감사합니다...!

2023-08-14 13:39 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/report/application/dto/ReportRequest.java
> +public class ReportRequest {
오 알겠습니다! 전에도 리뷰해주셨던 내용인데 미처 생각을 못했네요,,,반영해서 ReportCreateRequest, ReportCreateResponse, ReportFindResponse로 변경했습니다

2023-08-14 13:42 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/report/application/dto/ReportResponse.java
> +  public static ReportResponse of(Report report) {
작성할 때 잠깐 헷갈렸던 것 같습니다.
수정했습니다, 감사합니다!

2023-08-14 13:54 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/report/application/ReportCommandService.java
> +    if (!comment.getMember().getId().equals(reportRequest.getReportedId())) {
오 이렇게 처리하는 걸 미처 생각하지 못했네요...!
덕분에 코드가 훨씬 깔끔해졌어요
감사합니다~

2023-08-14 15:01 UTC, java-saeng approved these changes

2023-08-15 11:57 UTC, hyeonjerry approved these changes
전에 리뷰를 한 줄 알았는데 안했었네요ㅠ
수고하셨습니다.

2023-08-15 11:57 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/report/application/ReportCommandService.java
> +  private void validateReporterMismatch(final Long reporterId, final Member member) {
개인적으로 이러한 검증의 경우 무조건 reporterId가 memberId여야 하는 경우이니 dto로 reporterId를 받지 않는건 어떻게 생각하시는지 궁금합니다.
저는 이러한 경우에 reporterId를 받지 않을 경우 검증 로직을 하나 줄일 수 있고 혹시 실수로 인해 검증이 빠졌을 경우 생길 수 있는 잠재적 위험도 줄일 수 있다는 장점이 있을 것 같아요.

2023-08-15 11:57 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/report/application/ReportCommandService.java
> +  }
저도 일단은 생각나는 방법이 없네요ㅠ

2023-08-15 11:57 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/report/application/ReportCommandService.java
> +  private void validateExistReportedMember(final Long reportedId) {
이건 제 영어실력 문제일 수 있는데 처음에 메서드 명만 보고 이미 신고된 사용자를 검증하는 메서드인 줄 알았습니다ㅎㅎ

2023-08-15 11:57 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/report/exception/ReportExceptionType.java
> +  REPORT_MYSELF(
개인적으로 예외이다 보니 `CAN_NOT_REPORT_MYSELF`와 같이 금지의 의미가 있으면 좋을 것 같아요.

2023-08-15 15:28 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/report/exception/ReportExceptionType.java
> +  REPORT_MYSELF(
오 그렇게 하면 가독성이 더 좋아지겠네요! CANNOT이라는 표현은 지양하기로 했던 것 같아서, FORBIDDEN_REPORT_MYSELF로 수정해주었습니다!

2023-08-15 15:32 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/report/application/ReportCommandService.java
> +  private void validateExistReportedMember(final Long reportedId) {
아 `validateAlreadyExistReport()` 메서드가 따로 있는 상황이라 의도가 혼동이 될 수 있겠네요...! 
`validateNotFoundReportedMember()`로 변경해주었습니다! 감사합니다~

2023-08-16 01:16 UTC, hyeonjerry approved these changes
수고하셨습니다~!

2023-08-16 03:44 UTC, merged