Feature/#249 행사 관심 태그 crd 구현
woowacourse-teams/2023-emmsale pull request #280
Opened 2023-08-10 07:51 UTC by amaran-th

## #️⃣연관된 이슈
#249

## 📝작업 내용
사용자가 행사 관심 태그를 설정할 수 있도록 CRD API를 구현하였습니다.

## 예상 소요 시간 및 실제 소요 시간
4시간/3시간 반

2023-08-10 08:16 UTC, hyeonjerry requested changes
몇가지 의견 남겼습니다.
확인 후 재요청 해주세요. 수고하셨습니다.

2023-08-10 08:16 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
> +  @GetMapping("/members/{member-id}/interest-tags")
여기에만 interest-tags 앞에 {member-id}가 있는게 좀 어색하게 느껴지네요.
interest-tags를 다른 컨트롤러로 분리하는건 어떻게 생각하시나요?

2023-08-10 08:16 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/member/application/dto/InterestTagResponse.java
> +  public static List<InterestTagResponse> from(final List<InterestTag> interestTags) {
개인적인 의견입니다.
from만 보아선 InterestTagsResponse가 반환될 것 같은데 List가 반환되고 있는게 저는 조금 어색하게 느껴져요.

2023-08-10 08:16 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/member/application/InterestTagService.java
> +    final List<Tag> tags = tagRepository.findAllById(tagIds);
이름만 보아선 findAllById에 하나의 id만 넘겨야 될 것 같은데 리스트를 넘겨도 되군요?!

2023-08-10 08:16 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/member/domain/InterestTag.java
> +public class InterestTag extends BaseEntity {
엔티티명이 변경되었는데 테이블에선 여전히 member_tag를 사용하고 있습니다.

2023-08-11 04:49 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
> +  @GetMapping("/members/{member-id}/interest-tags")
저두요 만약 interest-tags에서 member id가 필요하면 쿼리 파라미터로 받아도 된다고 생각되네요

2023-08-11 04:53 UTC, java-saeng requested changes
고생하셨습니다.

처음 정했을 때 http 문서도 같이 만드는 것으로 알고 있는데, http 파일 만들어주실 수 있으실까요?

코멘트 답변해주시고 다시 재요청 부탁드립니다.

2023-08-11 04:53 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
> +      @RequestBody final InterestTagRequest interestTagRequest
이건 확장성보다는 그냥 네이밍하는게 힘들어서 남기는 리뷰에요

InterestTagRequest는 너무 포괄적인 의미라고 생각들어요.
나중에 기획에서 다른 interestTag 관련된 요청이 생길 때, 네이밍 짓기가 너무 어려울 것 같아서 

InterestTagCreateRequest나 InterestTagDeleteRequest가 어떠신가요?

2023-08-11 04:53 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/member/application/InterestTagService.java
> +    final List<Tag> tags = tagRepository.findAllById(tagIds);
findAllById를 두번 호출하는데 DB 커넥션을 한번 더 줄이는게 좋지 않을까요? 

aaddInterestTag에서 tags를 조회하고 파라미터로 주는게 괜찮다고 생각듭니다

2023-08-11 04:53 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/member/application/InterestTagService.java
> +    return InterestTagResponse.from(
DELETE 할 때도 반환해 줄 필요가 있나? 라는 생각이 들어요

2023-08-11 05:55 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
> +  @GetMapping("/members/{member-id}/interest-tags")
반영했습니다!
MemberApi와 InterestTagApi를 별개의 컨트롤러로 분리하고,
조회 API의 경우 member id를 쿼리 파라미터로 받게 했습니다

2023-08-11 06:03 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
> +      @RequestBody final InterestTagRequest interestTagRequest
반영했습니다!

2023-08-11 06:06 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/member/application/InterestTagService.java
> +    return InterestTagResponse.from(
POST 할 때도 데이터가 추가되고 난 후의 데이터 리스트를 반환해주고 있어서 DELETE를 할 때도 똑같이 데이터가 삭제되고 난 후의 데이터 리스트를 반환하게 했습니다!
MemberActivity CRUD API도 같은 식으로 동작하더라구요.

2023-08-11 06:07 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/member/domain/InterestTag.java
> +public class InterestTag extends BaseEntity {
저도 홍실과 같은 생각이어서 이렇게 설계해주었습니다!

2023-08-11 07:11 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/member/application/dto/InterestTagResponse.java
> +  public static List<InterestTagResponse> from(final List<InterestTag> interestTags) {
제리 의견 반영했습니다!

2023-08-11 08:34 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/member/application/InterestTagService.java
> +    final List<Tag> tags = tagRepository.findAllById(tagIds);
반영했습니다!

2023-08-11 09:26 UTC, hong-sile approved these changes

2023-08-13 07:15 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/member/application/InterestTagService.java
> +    return InterestTagResponse.from(
POST는 새로 생기니까 반환해주는게 괜찮다고 생각하는데 Delete 는 잘 모르겠네요

다른 API 에서도 그렇게 구현되어있어서 똑같이하셨다는 말씀은 뭔가 설득되지 않는 것 같아요. 아마란스의 생각을 말씀해주시는게 어떠신가요?

2023-08-13 07:15 UTC, java-saeng approved these changes

2023-08-13 07:20 UTC, merged