Feature/#291 컨퍼런스 같이가요 거절 수락
woowacourse-teams/2023-emmsale pull request #299
Opened 2023-08-11 16:50 UTC by tmdgh1592

## #️⃣연관된 이슈
>  ex) #291 

## 📝작업 내용
> 컨퍼런스 같이가요 알림 목록을 불러오는 API 스펙 변경 반영
같이가요 수락시 오픈채팅방으로 가는 버튼 보여주는 기능 구현
거절시 동그란 UnRead 아이콘를 숨기고 서버로 읽음 처리 전송

### 스크린샷 (선택)
![Screenshot_20230812_005844](https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/d2ea50c4-fb25-4e39-9205-eca9c7057cd0)

## 예상 소요 시간 및 실제 소요 시간
> 이슈의 예상 소요 시간과 실제 소요된 시간을 분 or 시간 or 일 단위로 작성해주세요.
> 2시간 / 4시간
> ex) 예상시간/걸린시간 => 2시간/3시간

## 💬리뷰 요구사항(선택)

> 아직 API가 배포되지 않은 상태에서 시간 부족으로 제대로 테스트하고 올리지 못한 점 죄송합니다.
앱 버그 외적인 부분을 리뷰해주시면 감사하겠습니다.

2023-08-12 05:04 UTC, chws0508 requested changes
고생하셨어용 ktlint 적용해주세요~

2023-08-12 05:04 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxFragmentStateAdapter.kt
> +        else -> throw IllegalArgumentException("Invalid position: $position")
오류메세지 companoin object 에 정의해주세용

2023-08-12 06:38 UTC, ki960213 reviewed
부나의 코드를 보고 많이 배웠습니다. 😄 
커스텀 다이얼로그를 어떻게 만드는 지 궁금했는데, 덕분에 알 수 있을 것 같아요!

2023-08-12 06:38 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentNotificationBodyUiState.kt
> +    val otherUid: Long,
화면에 보여질 데이터는 알림을 보낸 사람의 아이디와 이름이므로 other 보단 sender라는 이름은 어떤가요?

2023-08-12 06:38 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/body/RecruitmentNotificationBodyClickListener.kt
> +    fun onRecruitmentReject(notificationId: Long)
클릭 이벤트를 처리하는 함수이므로
```suggestion
    fun onAcceptButtonClick(notificationId: Long)
    fun onRejectButtonClick(notificationId: Long)
```
이렇게 바꾸면 어떨까요? 혹은 사용자가 모집 수락이나 거절의 이벤트 발생을 추상화(예를 들어 ui를 클릭함으로써 이벤트를 발생시키는 건지 음성인식으로 이벤트를 발생시키는 건지는 감추도록) 하려면 리스너 명을 `RecruitmentNotificationBodyListener`라고 바꾸는 건 어떨까요? 저는 개인적으로 전자를 선호합니다! 안드로이드 의존성을 가진 곳, 즉 UI 로직을 실행하는 클래스에서 사용될 것이기 때문에, ui 이벤트를 추상화하지 않는 게 더 좋다고 생각해요

2023-08-12 06:38 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/body/RecruitmentNotificationBodyClickListener.kt
> +    fun onClickMore(notificationId: Long)
더보기 버튼이 클릭되었을 때 실행될 함수이므로 on[명사][동사] 컨벤션에 따라 onMoreButtonClick은 어떤가요?

2023-08-12 06:38 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_recruitment_notification_body.xml
> +            android:background="?attr/selectableItemBackgroundBorderless"
버튼을 클릭했을 때 동그랗게 물결이 치게 만들려면 이 속성을 사용하면 되는군요 👍

2023-08-13 04:55 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxActivity.kt
>      }
해당 함수는 TabLayout 인터페이스의 필수 구현 메서드라 오버라이드는 해주어야 해요!

2023-08-13 04:55 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxActivity.kt
>      }
제가 잘못 이해한 부분이 있다면 추가 코멘트 부탁드려요 😀

2023-08-13 04:56 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/otherNotification/PrimaryNotificationFragment.kt
> +class PrimaryNotificationFragment : BaseFragment<FragmentPrimaryNotificationBinding>() {
처음에 OtherNotificationFragment로 네이밍하였다가 변경하는 과정에서, 패키지명은 수정되지 않은 것 같네요!
리뷰 반영해놓겠습니다 : )

2023-08-13 04:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxActivity.kt
> +        binding.tbNotiBox.setNavigationOnClickListener { finish() }
훨씬 명확한 네이밍인 것 같아요!

2023-08-13 06:07 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationRepository.kt
> +    ): ApiResult<Unit>
좋습니다!
`RecruitmentNotificationStatus`를 만들었다는 사실을 깜빡했네요.
리뷰 반영하였습니다.

2023-08-13 06:10 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentNotificationBodyUiState.kt
> +    val message: String,
> `conference 보다는 event가 나을 것 같아요, 대회도 있을 거니까요`

동의합니다 : )

상대방의 uid를 나타내는 변수명이라 otherUid라고 명명하였는데, 조금 어색한가요?
senderUid는 어떤가요?

2023-08-13 06:12 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/RecruitmentNotification.kt
> +    val myUid: Long,
스캇 리뷰와 일부 비슷한 부분인 것 같아 한 번에 `senderUid`, `receiverUid`로 변경하였습니다 : )

2023-08-13 06:15 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxFragmentStateAdapter.kt
> +        else -> throw IllegalArgumentException("Invalid position: $position")
`INVALID_FRAGMENT_POSITION_MESSAGE`로 매직 리터럴을 제거하였습니다.

2023-08-13 06:18 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationFragment.kt
> +    }
넵, 아이콘 자체는 `더 보기` 모양이다보니 이렇게 네이밍 하였습니다.
추후에 신고 외에도 삭제 등의 기능이 추가될 가능성이 충분하다고 판단하였구요 : )

2023-08-13 06:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationFragment.kt
> +                uiState.isError -> requireContext().showToast(getString(R.string.notificationbox_recruitment_status_changing_failed))
지금 당장은 에러가 하나여서 isError라고 네이밍을 지었습니다!
그런데 이야기를 듣고 보니, 에러가 하나여도 어떤 에러인지 파악하기 쉽게 하기 위해서는 구체적으로 네이밍해도 좋을 것 같아요~
반영하겠습니다.

2023-08-13 06:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/body/RecruitmentNotificationBodyClickListener.kt
> +    fun onClickMore(notificationId: Long)
`더보기 버튼이 클릭되었을 때`이므로 on[명사][동사 과거형]() 컨벤션이 조금 더 적절할 것 같아요!
리뷰 반영하겠습니다 : )

2023-08-13 06:54 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/body/RecruitmentNotificationBodyClickListener.kt
> +    fun onRecruitmentReject(notificationId: Long)
지금 보니, ClickListener 인터페이스에서 onRecruitmentAccept() 라는 네이밍이 조금 어색한 것 같아요.
UI에 대한 Listener인데 비즈니스 로직을 수행할 것 같은..?

해당 리뷰도 반영하도록 하겠습니다 : )

2023-08-13 06:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_recruitment_notification_body.xml
> +            android:background="?attr/selectableItemBackgroundBorderless"
꿀팁입니당 👍

2023-08-13 07:02 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +                is ApiSuccess -> updateNotifications(notificationsResult)
좋은 의견이예요!
굳이 ApiResult 전체를 넘길 필요 없이, 필요한 인자만 넘기면 될 것 같습니다.

```kotlin
private suspend fun updateNotifications(
    recruitmentNotifications: List<RecruitmentNotification>,
)
```

2023-08-13 07:07 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +        }
List도 구조 분해가 가능하군요!
아래와 같이 작성하면 조금 더 코드가 깔끔할 것 같아요! 👍

2023-08-13 07:15 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +    private suspend fun getNotificationMemberAsync(userId: Long): Deferred<RecruitmentNotificationMemberUiState?> =
코루틴에서는 다음과 같은 네이밍 컨벤션이 있습니다.
> 비동기적으로 동작함을 명시하기 위해, 함수명 뒤에 Async 를 붙여준다.

위 네이밍을 통해 getNotificationMember라는 행위를 비동기적으로 한다는 사실을 알 수 있죠.
또한 반환 타입은 메서드 시그니처로 이미 명시되어 있기 때문에 불필요한 중복이라고 생각해요 : )

2023-08-13 07:15 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +        val conferenceName = getConferenceNameAsync(notification.eventId)
위와 동일한 의견입니다.

2023-08-13 07:15 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +    private suspend fun getConferenceNameAsync(conferenceId: Long): Deferred<String?> =
위와 동일한 의견입니다.

2023-08-13 07:18 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentNotificationBodyUiState.kt
> +    val message: String,
sender 좋아요

2023-08-13 07:27 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxActivity.kt
>      }
제가 잘못 이해했어용~

2023-08-13 07:29 UTC, chws0508 approved these changes
더이상 리뷰할게 없는것 같아요~ 고생하셨습니다!

2023-08-13 07:49 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxFragmentStateAdapter.kt
> +        else -> throw IllegalArgumentException("Invalid position: $position")
저는 개인적으로 오류 메세지는 companion object에 정의할 필요가 없다고 생각합니다.
매직 리터럴을 제거해야 하는 이유는 그 값 만으로 사용 목적을 파악할 수 없거나 중복을 제거하기 위함인데, 오류 메세지는 단지 특정 오류가 발생했을 때 쉽게 오류를 파악하기 위해 존재합니다.
다른 오류끼리 같은 오류 메세지를 보여주는 것은 거짓 중복이고, 오류 메세지는 값 만으로 사용 목적을 쉽게 파악할 수 있기 때문에 오류 메세지는 굳이 companion object에 정의하지 않아도 된다고 생각합니다!

2023-08-13 08:33 UTC, ki960213 reviewed
조금 늦었긴 했는데 알림 화면에서 모집에 대한 정보를 보여준다고 해서 `RecruitmentNotification`이라는 이름은 조금 이상한 것 같네요ㅠㅠ
사용자가 받은 모집 목록은 알림 화면이 아니라 다른 화면에서 보여줘도 어색하지 않죠...
하지만 너무 멀리 와버린 것 같은데 어떻게 생각하시나요?

2023-08-13 08:33 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationRepository.kt
>      ): ApiResult<Unit>
인자명이 `recruitmentStatus`라면 메서드명도 `updateRecruitmentStatus` 이렇게 줄여도 괜찮지 않을까요?

2023-08-13 08:33 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationRepository.kt
> +    ): ApiResult<Unit>
생각해보니 `RecruitmentNotificationStatus`라는 이름보단 `RecruitmentStatus`라는 이름이 더 명확하지 않을까요?
모집이라는 건 특정 사용자가 다른 사용자에게 함께 가자고 요청한 행위이고 그 행위의 상태는 총 세 가지(대기, 수락됨, 거절됨)가 있다고 생각합니다. 알림이라는 것은 그 모집이라는 행위를 받은 사용자에게 알려주는 일종의 표현 방식이라고 생각합니다. 극단적으로 알림이 아니라 커디의 관리자가 모집 받은 사람에게 전화로 수락할 건지 거절할 건지 물어봐서 모집 상태를 결정할 수도 있으므로 `RecruitmentStatus`라는 이름이 더 명확하다고 생각합니다!

2023-08-13 08:33 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferenceUiState.kt
>      val conferenceItems: List<ConferenceItemUiState> = emptyList(),
여러 컨퍼런스의 상태를 가지고 있는 클래스의 이름이 단수형인 게 어색해보입니다.
이전 레벨2에서 장바구니 미션 때 `Cart`와 `CartItems`라는 이름을 사용했던 이유는 "장바구니"라는 것은 "여러 개의 장바구니 아이템"을 담을 수 있기 때문에 `Cart`라는 이름을 사용해도 여러 개의 장바구니 아이템을 포함한다는 것을 알 수 있지만, `Conference`라는 이름은 확실히 단수형이기 때문에 차라리 `ConferencesUiState`, `ConferenceUiState` 이렇게 이름을 정하는 것이 더 좋다고 생각합니다 😢

2023-08-13 08:33 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +    private suspend fun getNotificationMemberAsync(userId: Long): Deferred<RecruitmentNotificationMemberUiState?> =
그런 네이밍 컨벤션이 있었군요!

2023-08-13 08:33 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +    }
사실은 알림을 신고하는 게 아니라 모집의 모집 메세지가 불건전해서 신고하는 거니까 `reportRecuitment`라는 이름이 더 좋을 것 같다는 생각이 드는데... 이미 너무 많이 와버렸으니 그냥 둬도 괜찮을 것 같아요 😢

2023-08-13 09:10 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationRepository.kt
>      ): ApiResult<Unit>
RecruitmentNotificationStatus 또한 RecruitmentStatus로 변경하였습니다.

2023-08-13 09:19 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferenceUiState.kt
>      val conferenceItems: List<ConferenceItemUiState> = emptyList(),
저번에 Filter vs Option 이야기를 나눌 때 토마스께서 UiState 클래스명에 s를 붙이는게 어색하다고 말씀하셨는데 생각이 바뀌신 걸까요?
저 또한 s를 붙이는게 더 자연스럽다고 생각하고 있지만, 의견을 따랐던 거였어요!
괜찮으시다면 s를 붙이도록 할게요.

2023-08-13 09:20 UTC, tmdgh1592 commented
> 조금 늦었긴 했는데 알림 화면에서 모집에 대한 정보를 보여준다고 해서 RecruitmentNotification이라는 이름은 조금 이상한 것 같네요ㅠㅠ
사용자가 받은 모집 목록은 알림 화면이 아니라 다른 화면에서 보여줘도 어색하지 않죠...
하지만 너무 멀리 와버린 것 같은데 어떻게 생각하시나요?

같이가요 알림 목록을 보여주는 화면에서 RecruitmentNotification이라는 단어가 전혀 이상하게 느껴지지 않습니다.
말씀해주신 것처럼 Recruitment만 사용하는 것이 오히려 혼동을 야기할 것 같아요 🥲

2023-08-13 09:21 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +    }
아무것도 구현되지 않은 메서드예요!
충분히 수정 가능합니다.

2023-08-13 09:22 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +    }
추가로, Recruitment를 신고한다기 보단, `사용자를 신고한다`는 것이 더 정확하겠네요!
reportMember()로 변경하도록 하겠습니다 : )

2023-08-13 09:40 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferenceUiState.kt
>      val conferenceItems: List<ConferenceItemUiState> = emptyList(),
아 제가 오해했었던 부분이네요!
Filter 안에 FilterOptions가 있기 때문에 별개의 클래스라고 생각하셔서 s를 붙이지 말자고 하셨던 거였군요.
커뮤니케이션이 이래서 중요한 것 같습니다 😢
클래스명은 이전처럼 복수형으로 바꾸었어요 : )

2023-08-13 09:52 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +    }
헉 신고 내용에는 회원 정보만 필요한 게 아니라 요청 메세지의 불건전함을 판단할 수 있도록 같이 가자는 요청 메세지가 필요할 것 같습니다. 따라서 차라리 바꾸기 전이 더 나아보입니다!

2023-08-13 10:07 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
> +    }
그런 의견이라면 처음 네이밍인 `알림을 신고한다`보다 맨 처음에 제안해주신 `reportRecuitment`가 더 적절할 것 같아요!

2023-08-13 10:22 UTC, ki960213 approved these changes
제 깐깐한 리뷰를 반영하느라 고생하셨습니다 👍

2023-08-13 11:25 UTC, merged