Feature/#268 댓글 화면 디자인 변경
woowacourse-teams/2023-emmsale pull request #305
Opened 2023-08-12 19:50 UTC by ki960213

## #️⃣연관된 이슈
>  ex) #268 

## 📝작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
댓글의 삭제 버튼을 메뉴 버튼으로 변경
커스텀 위험 다이얼로그, 커스텀 하단 메뉴 다이얼로그 구현

### 스크린샷 (선택)
<img width="292" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/6514f12a-4683-4a2a-a88a-41cba8eb9f88">
<img width="294" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/f0bef134-b902-4481-9eb3-907180a86d1c">

## 예상 소요 시간 및 실제 소요 시간
> 이슈의 예상 소요 시간과 실제 소요된 시간을 분 or 시간 or 일 단위로 작성해주세요.
> 
> 3시간/1일

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2023-08-13 11:49 UTC, tmdgh1592 requested changes
기능 구현하느라 고생하셨습니다 토마스!
리뷰 남겼으니 반영 후에 다시 요청해주세요!

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
>              }
handleError()라고 하면 어떤 UiState 관련 에러인지 파악하기 어려워요 🥲
이전에 저에게 리뷰를 남겨주신 isError 프로퍼티와 동일한 문제라고 생각합니다.
그리고 여러 에러를 다루고 있다면 복수형이 더 낫지 않을까요?

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentAdapter.kt
>      }
early return을 할 필요가 없어 보여요!
when 으로 처리하는 것이 더 깔끔해보입니다 👍

```kotlin
override fun onBindViewHolder(holder: RecyclerView.ViewHolder, position: Int) {
    when(holder) {
        is ParentCommentViewHolder -> ...
        is ChildCommentViewHolder -> ...
    }
}
```

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentRecyclerViewDivider.kt
> +    }
Nullable하게 해서 앱이 터지지 않게끔 구현한 이유가 있나요?
리소스를 찾지 못할 가능성도 희박하지만, 만약 찾지 못한다고 해도 크리티컬하지 않은 부분에서는 앱이 터져서 안 좋은 UX를 제공하는 것보다, Divider를 안 보여주는 것이 좋지 않을까요?

```kotlin
divider?.setBounds(...)
divider?.draw(c)
```

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentRecyclerViewDivider.kt
> +    }
+) 만약 그래도 에러를 던지고 싶으시다면 `리소스명`과 `에러 문구의 리소스명`을 통일해주세요.

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentRecyclerViewDivider.kt
> +        val right = parent.width - parent.paddingRight
paddingRight보단, paddingEnd를 사용해주세요.

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
> +        bottomMenuDialog.addReportButton()
RecyclerView에서 onBindViewHolder가 호출될 때마다 bind(...) 메서드가 호출되면서 Dialog를 계속해서 생성해내고 있어요.

성능 측면에서 `init { ... }` 블럭 안에서 ViewHolder가 감싸고 있는 View에 단 한 번만 Listener를 등록하고, 클릭하기도 전에 Dialog를 생성할 필요 없이, 클릭했을 때 생성해도 괜찮다고 생각해요.
ViewHolder에서 ClickListener를 등록하는 부분을 모두 init 초기화 블럭에서 하도록 변경해주세요 : )

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ParentCommentViewHolder.kt
> +
위 리뷰와 동일합니다.

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ParentCommentViewHolder.kt
> +    private val onCommentDelete: (Long) -> Unit,
여기서 조금 더 명확하게 작성하고 싶다면, `onCommentDelete: (xxxId: Long) -> Unit` 처럼 작성해도 좋아요.

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentRecyclerViewDivider.kt
> +    }
이 부분도 위에 남겼던 것과 동일하게 리소스명을 맞추어 주세요 : )

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentRecyclerViewDivider.kt
> +            val bottom = top + (divider.intrinsicHeight)
괄호를 작성하신 이유가 있으신가요?

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentRecyclerViewDivider.kt
> +        val right = parent.width - parent.paddingRight
paddingEnd를 사용해주세요.

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentViewHolder.kt
> +            BottomDialogMenuItem.DANGER,
코드를 보면서 든 생각인데, DANGER보단 그냥 명확하고 단순하게 색상으로 표현하는 게 좋지 않을까요?
ex. BottomDialogMenuItem.RED

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/drawable/img_bottomdialog_topdecoration.xml
> -        android:height="4dp" />
파일명을 `img_bottomdialog_top_decoration`으로 하는 건 어떤가요?

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/activity_child_comments.xml
> +            android:id="@+id/tb_childcomments_toolbar"
뒤에 toolbar는 필요 없어 보입니다!

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/dialog_bottom_menu.xml
> +            tools:layout_editor_absoluteX="17dp"
Design 탭에서 옮기다가 실수로 생긴 것 같아요.
지워주시면 좋겠습니다!

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/DangerDialog.kt
> +    private val title: String,
DangerDialog라는 네이밍이 조금 와 닿지 않네요..
이름만 들었을 땐 경고 다이얼로그처럼 느껴지지만 사실상 취소, 확인 버튼이 있네요.

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/values/colors.xml
> +    <color name="red">#FF2424</color>
red 컬러는 현재 커스텀 다이얼로그에서만 사용되고 있어요!
또한, 실제로 `#FF0000`도 아니구요.
이런 상황에서는 별도로 네이밍을 짓고 공통에서는 제외하는 것이 좋아 보여요!
다이얼로그의 red 색상을 바꾸려다가, red를 사용하고 있는 다른 코드에서도 의도치 않게 색깔이 조금씩 변경될 수 있으니까요 👍🏻

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_comments_comments.xml
contentDescription에서 menu_button으로 표기하였다면, id나 drawable도 menu_button으로 작성해주시면 좋을 것 같아요.

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/values/strings.xml
> +    <string name="all_deleteButtonLabel">삭제</string>
xml 네이밍 컨벤션은 `스네이크 케이스`입니다.

2023-08-13 11:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/values/strings.xml
> +    <string name="all_reportButtonLabel">신고하기</string>
위와 동일한 리뷰입니다.

2023-08-13 11:50 UTC, tmdgh1592 commented
이후에 ktlint를 돌리고 CI 통과하게끔 해주세요!

2023-08-13 12:14 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/BottomDialogMenuItem.kt
> +) : androidx.appcompat.widget.AppCompatTextView(context) {
둘 다 좋은 의견이군요! 반영했습니다 👍

2023-08-13 12:18 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/BottomDialogMenuItem.kt
> +        setPadding(0, 21.dp, 0, 21.dp)
그렇다면
```suggestion
        setTypeface(null, Typeface.BOLD)
        setTextSize(Dimension.SP, TITLE_TEXT_SIZE)
        setPadding(0, PADDING_TOP_DIMENSION, 0, PADDING_BOTTOM_DIMENSION)
```
이러한 코드가 더 파악하기 쉬울까요?

2023-08-13 12:28 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/BottomDialogMenuItem.kt
> +    }
처음엔 MenuItemType 이름만 보고 하단 메뉴 다이얼로그 안의 메뉴 아이템의 타입을 의미하는 걸 파악하기 힘들지 않을까 생각했는데, 생각해보니 bottomMenuDialog 패키지에 속한 MenuItemType이라면 의미를 파악할 수 있겠군요!

2023-08-13 12:30 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/BottomMenuDialog.kt
> +        if (binding.llBottommenudialogMenuitems.childCount > 0) {
저희의 아이디 네이밍 컨벤션은
<img width="544" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/f50ca55a-62f4-42b3-bff1-ad7d382b4eff">
이런데 `ll_bottom_menu_dialog_menu_items` 이렇게 이름 지어도 괜찮을까요?

2023-08-13 12:34 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/DangerDialog.kt
> +    }
예를 들어 화면의 크기가 제 노트북 화면의 크기일 때 width가 화면 크기의 80퍼센트라면 조금 이상할 것 같아서요ㅠㅠ
다이얼로그 안의 글자 크기에 따라 다이얼로그의 크기가 결정되어야 한다고 생각합니다.

2023-08-13 12:43 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
>              }
`handleError()` 라는 함수명은 해당 화면에서 발생한 모든 에러를 처리한다는 뜻으로 썼습니다.
그리고 그 안에 각각 다른 에러를 처리하도록 구현했구요.
확실히 `handleErrors()`라는 이름이 더 낫군요 👍

2023-08-13 13:05 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentRecyclerViewDivider.kt
> +    }
만약 코드 충돌을 해결하다가 R.drawable.bg_all_vertical_divider 리소스를 실수로 삭제하게 되었다면, 대댓글 화면에 들어갔을 때 에러가 터지고 에러 메세지를 보여준다면 더 쉽게 의도하지 않은 코드가 작성되었다는 것을 알 수 있지 않을까요?
저는 개발 단계에서는 의도하지 않은 코드가 작성되었다면 에러를 터트리는 게 더 좋다고 생각합니다!

2023-08-13 13:20 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
> +        bottomMenuDialog.addReportButton()
저도 처음에 뷰 홀더가 생성되면 다이얼로그를 생성하는 방법을 고민했습니다.
다이얼로그의 메뉴는 뷰홀더의 바인딩 된 commentUiState에 따라 달라져야 합니다.
즉, bind 되었을 때 메뉴 항목들을 추가해야 합니다.
그런데 이렇게 구현한다면 바인딩 될 때마다 메뉴 항목이 추가되기 때문에 그냥 바인딩 시 새로운 다이얼로그를 생성하도록 구현했습니다.
하지만 다시 한 번 생각해보니 바인딩 될 때마다 메뉴 항목을 초기화하고 다시 메뉴 항목을 추가하면 되겠군요!
그런데 궁금한 게 있습니다. BottomMenuDialog를 생성하는 비용과 BottomMenuDialog 안의 뷰들을 삭제하는 비용 중 어떤 게 더 클까요? ❓

2023-08-13 13:39 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ParentCommentViewHolder.kt
> +    private val onCommentDelete: (Long) -> Unit,
함수 타입을 선언할 때 함수의 파라미터에 이름을 선언할 수도 있군요! 👍

2023-08-13 13:45 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentRecyclerViewDivider.kt
> +            val bottom = top + (divider.intrinsicHeight)
코드를 어디서 가져왔다보니 이런 실수가... 😓

2023-08-13 14:01 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentViewHolder.kt
> +            BottomDialogMenuItem.DANGER,
저희 앱에서 다이얼로그를 사용하는 목적은 정해져있다고 생각합니다.
사용자가 어떤 행위를 하기 전에 단순히 정보를 알려주거나, 경고하거나, 위험하다고 알려주는 것 등등
저는 빨간 글씨를 사용하는 다이얼로그를 띄우는 이유는 위험하다고 알려주기 위함이라고 생각합니다.
하지만 하단 메뉴 다이얼로그에서 빨간 글씨로 보여주는 것은 위험하다고 알려주는 게 아닌 경우(신고하기)도 있으니 하단 메뉴 다이얼로그에서는 DANGER라는 이름은 좋지 않아 보이네요 👍 
그에 따라 이름도 변경했습니다!

2023-08-13 15:23 UTC, chws0508 requested changes
고생많으셨습니다. 부나가 많이 리뷰를 달아줘서 저는 많이 널널하게 했어요~

2023-08-13 15:23 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/values/colors.xml
> +    <color name="red">#FF2424</color>
동의합니다

2023-08-13 15:23 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentViewHolder.kt
> +            BottomDialogMenuItem.DANGER,
굳굳

2023-08-13 15:23 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
> +        bottomMenuDialog.addReportButton()
init 에서 하는것과 bind 에서 하는것의 차이는 setOnclickListener 를 처음 생성할 때만 해주냐 아니면 재생성 해주는 부분에도 해주냐 차이로 알고있습니다.

2023-08-13 15:23 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
> +        bottomMenuDialog.addReportButton()
initMenuButton 의 함수 내용을 모두 onClickListenr 로 넣어주면 어떨까요? 지금은 Click을 하지 않아도 bind 될때마다 로직이 실행되고 있는 것 같습니다. 그리고 onClickListener 를 달아주는 부분은 init 에서 실행하구요

2023-08-13 15:24 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/drawable/img_bottomdialog_topdecoration.xml
> -        android:height="4dp" />
넵 description은 스네이크 케이스를 사용하도록 하죠!

2023-08-13 15:25 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/activity_child_comments.xml
> +            android:id="@+id/tb_childcomments_toolbar"
이것만 description을 없애는 것이 조금 그래서... 😓

2023-08-13 15:30 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/DangerDialog.kt
> +    private val title: String,
DangerDialog 구현 의도는 사용자가 어떤 행위를 하기 전에 위험하다고 알려주는 용도로서 DangerDialog라고 네이밍했습니다.
사용자의 입장에서 그 위험한 행위를 하겠다고 선언하는 버튼인 positive button과 행위를 취소하는 버튼인 negative button이 존재합니다.
위험하다고 알려주는 것을 경고라고 생각한다면 WarningDialog라는 이름이 알맞을까요?

2023-08-13 16:58 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/values/colors.xml
> +    <color name="red">#FF2424</color>
부트스트랩에서는 아래의 사진처럼 특정 상황에서 쓰여야 하는 색상을 정해놨습니다.
<img width="627" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/6c3b1fbe-a2d2-4754-9749-931cca4df37d">
저도 이것처럼 우리 앱에서 특정 상황에 쓰여야 할 색상을 정하면 좋다고 생각합니다. 저희 앱에서 `#FF2424`를 경고를  표시하기 위한 색상으로 정의하면 어떨까요?

2023-08-13 17:09 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_comments_comments.xml
현재 그렇게 되어있지 않나요? ❓

2023-08-13 17:25 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
> +        bottomMenuDialog.addReportButton()
뷰 홀더에 바인드되는 `CommentUiState` 객체의 `isUpdatable` 속성과 `isDeletable` 속성에 따라 메뉴 항목이 바뀝니다.
만약 하단 메뉴 다이얼로그를 댓글 화면에 맞게 커스텀되었다면 하단 메뉴 다이얼로그의 메뉴 항목이 xml에 정해놓고 `CommentUiState` 객체의 속성에 따라 뷰의 visivility 속성을 변경하면 된다고 생각합니다. 하지만 하단 메뉴 다이얼로그에 메뉴 항목을 추가하는 방식으로 구현해서 어쩔 수 없이 바인드 할 때마다 메뉴 항목 뷰를 추가하고 있습니다.
저는 개인적으로 성능 상 별 차이가 없다고 생각해서
```
    private fun initMenuButton(comment: CommentUiState) {
        bottomMenuDialog.resetMenu()
        if (comment.isUpdatable) bottomMenuDialog.addUpdateButton()
        if (comment.isDeletable) bottomMenuDialog.addDeleteButton()
        bottomMenuDialog.addReportButton()

        binding.ivChildcommentMenubutton.setOnClickListener { bottomMenuDialog.show() }
    }
```
이렇게 구현하는 것을 선호하는 데, 스캇은 어떻게 생각하시나요?

2023-08-14 02:18 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/BottomMenuDialog.kt
> +        if (binding.llBottommenudialogMenuitems.childCount > 0) {
제시해주신 자료는 XML 리소스의 네이밍 컨벤션입니다.
IDS에 대한 컨벤션은 아래와 같이만 정한 것으로 알고 있어요.
또한 컨벤션과 별개로, llBottommenudialogMenuitems라고 변환되면 조금 읽기 어렵지 않을까요? 🥲

<img width="405" alt="스크린샷 2023-08-14 오전 11 16 20" src="https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/90fae99a-dd42-41fd-9efd-53b98ee91636">

2023-08-14 02:21 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/BottomDialogMenuItem.kt
> +        setPadding(0, 21.dp, 0, 21.dp)
현재 코드에서 한 쪽만 패딩을 다르게 할 일이 없으니, 변수명을 하나로 통일해서 사용하면 바꿔주신 것보다 읽기 편할 것 같아요.

2023-08-14 02:25 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
>          }
setupLoginUiLogin()
setupCommentsUiLogin()

라는 단어를 네이밍을 사용하면 되지 않을까요?

2023-08-14 02:27 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentRecyclerViewDivider.kt
> +    }
저도 개발 단계에서는 빨리 Crash 발생하기를 선호합니다.
다만 지금 커디 프로젝트는 개발 단계, 출시 단계가 명확히 구분되어 있지 않아요.
그랬던 것이라면 깃허브에도 release 브랜치가 추가되어야 할 거예요.

바로 데모데이가 끝나면 플레이스토어에 출시될 앱이라는 점을 기억해주세요 : )

2023-08-14 02:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
> +        bottomMenuDialog.addReportButton()
comment의 속성 값에 따라 Dialog가 달라지는군요.
그렇다면 그 부분은 제외하겠습니다.
스크롤하면서 새로운 RecyclerView의 자식 뷰가 보여질 때마다, 매번 Dialog를 생성하도록 하신 이유는 있나요?
Dialog 생성 대비, 클릭 비율이 현저히 낮을 것으로 예상이 되네요.

2023-08-14 02:39 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentViewHolder.kt
> +            BottomDialogMenuItem.DANGER,
넵 역할이 정해져 있다면 역할에 맞추어 네이밍 짓는게 좋아 보여요.
해당 다이얼로그를 위험한 상황이 아닌 경우에도 사용할 수 있을 것으로 보이는데, DANGER라고 작성해주셔서 남긴 리뷰였습니다 : )

다음에 리뷰 답변을 해주실 때에는 어떻게 이름을 변경했는지도 작성해주시면 좋을 것 같아요.

2023-08-14 02:45 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/values/colors.xml
> +    <color name="red">#FF2424</color>
Danger라는 워딩을 여기서 참고하셨던 거군요!
저희 앱에서 다이얼로그를 제외하고, Danger의 의미를 나타내는 `#FF2424` 색상을 사용할 일이 있을까요?

또한 있다고 하더라도, 현재 red라는 네이밍은 너무 모호합니다.
그 상황에 맞는 네이밍으로 변경이 필요해 보여요.

2023-08-14 02:46 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_comments_comments.xml
언더바(_)를 붙여 달라는 리뷰였습니다.
String 리소스 id에는 언더바를 붙이고, 다른 리소스 id에는 언더바가 없네요.

2023-08-14 03:21 UTC, chws0508 approved these changes

2023-08-14 03:26 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/BottomDialogMenuItem.kt
> +        setPadding(0, 21.dp, 0, 21.dp)
위와 같은 상황은 `textSize = MENU_ITEM_TEXT_SIZE`와 비슷한 상황이라 개인적으로 `textSize = 14.sp`가 더 읽기 편하다고 생각하지만, 리소스로 관리하면 좋다고 생각이 들어서 텍스트 크기와 패딩 수치를 dimens에 추가했습니다.

2023-08-14 03:33 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/BottomMenuDialog.kt
> +        if (binding.llBottommenudialogMenuitems.childCount > 0) {
<img width="360" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/9fb76dfb-224f-4d73-9c6e-33efbc940196">

위 IDS에 대한 컨벤션에 따르면 `ll_bottommenudialog_menuitems`가 맞다고 생각합니다. 이것이 바인딩 객체로 사용될 때는 `llBottommenudialogMenuitems` 이렇게 변환됩니다.
저는 개인적으로 `<what>_<where>_<description>`이 눈에 익어서 `ll_bottommenudialog_menuitems` 이게 더 잘 읽히긴 하지만 description만 예외적으로 스네이크 케이스를 적용한다면 `ll_bottommenudialog_menu_items` 이렇게 쓸 수 있겠네요. 변환되면 `llBottommenudialogMenuItems` 이렇게 변하구요.

2023-08-14 03:48 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentRecyclerViewDivider.kt
> +    }
만약 개발 단계, 출시 단계가 구분되어 있더라도 개발 단계에서는 앱을 터트리도록 코드를 작성하다가 출시 단계가 되면 Nullable 하게 코드를 변경하는 것도 말이 안된다고 생각합니다.
따라서 저는 출시 후에도 에러를 던지도록 구현하는 것이 좋다고 생각합니다. 앱을 한 번 실행시켜보고 테스트만 해봐도 무엇이 의도하지 않도록 코딩되었는지 바로 알 수 있기 때문입니다. 앱을 한 번도 테스트 하지 않고 출시하지는 않을테니까요.

2023-08-14 03:49 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
> +        bottomMenuDialog.addReportButton()
다이얼로그는 viewholder가 생성되었을 때 생성되도록 변경했습니다! 👍

2023-08-14 03:56 UTC, tmdgh1592 approved these changes

2023-08-14 04:15 UTC, merged