Feature/#306 프로필 조회 화면 구현
woowacourse-teams/2023-emmsale pull request #313
Opened 2023-08-13 09:02 UTC by ki960213

## #️⃣연관된 이슈
>  #306

## 📝작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

프로필 조회 화면 만들기

### 스크린샷 (선택)
<img width="289" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/6ce5981d-091d-41b3-9596-ddd4cd21fd27">

## 예상 소요 시간 및 실제 소요 시간
> 이슈의 예상 소요 시간과 실제 소요된 시간을 분 or 시간 or 일 단위로 작성해주세요.
> 
> 4시간/3시간

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

일단은 테스트를 위해 대댓글 화면에서 자식 댓글을 클릭하면 작성자의 프로필을 조회하도록 구현했습니당

2023-08-13 12:24 UTC, tmdgh1592 requested changes
프로필 조회 화면 구현하시느라 고생하셨습니다 토마스!
몇 가지 리뷰를 남겼으니 확인해주세요 : )

+ ProfileActivity는 상대방의 프로필을 조회하는 화면이겠죠?
지금 코드를 확인해보면, MyProfileActivity와 ProfileActivity가 존재해요.
둘의 네이밍을 확실히 정해주시면 좋겠습니다!

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/CategoryTag.kt
> +        background = ContextCompat.getDrawable(context, R.drawable.bg_profile_categorytag)
전에 데모데이 끝나고 이야기 나눴던 것처럼 <where> 부분을 제외하고는 언더바를 붙이는 것이 가독성을 높일 수 있을 것 같아요!

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentAdapter.kt
> +    private val onAuthorView: (Long) -> Unit,
onAuthorView라는 것은 프로필을 조회한다는 건가요?
처음에 보고 TextView와 같은 어떠한 View를 나타내는 네이밍인 줄 알았어요..!

`onProfileClick`이란 네이밍은 어떤가요?

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
> +            )
한 줄로 작성해도 됩니당 👍

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
>                  false,
아래 코드는 어떠신가요?

```kotlin
val binding = ItemChildcommentsChildcommentBinding
                .inflate(LayoutInflater.from(parent.context), parent, false
```

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileFragment.kt
>          }
어떤 UIState의 에러인지 메서드명을 명확하게 작성하면 더 좋을 것 같아요!

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileFragment.kt
> +        const val TAG = "TAG_MY_PROFILE"
`val TAG: String = MyProfileFragment::class.java.simpleName`는 어떤가요?
혹여나 Fragment명이 바뀐다고 하더라도, 해당 코드는 변경되지 않아도 된답니다.

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
> +    }
memberId를 Activity에서 프로퍼티로는 가지고 있을 필요는 없다고 생각해요!
viewModel.fetchMember() 하는 곳에서 일회성으로만 사용해도 된다고 생각합니다.

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
> +        binding.tbProfileToolbar.setNavigationOnClickListener { onBackPressedDispatcher.onBackPressed() }
finish()를 함수를 사용해도 충분합니다.

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
> +    }
버튼을 클릭할 때마다 매번 BottomMenuDialog를 생성할 필요가 있을까요?
by lazy 키워드로 지연 초기화를 하고, 한 번 생성한 이후에는 Dialog를 재사용하는 것을 추천드립니다.

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
> +
관찰하고 있는 ViewModel의 LiveData에 따라 함수를 분리해주면 좋을 것 같습니다.

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
> +    }
위와 동일한 리뷰예요!

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
> +        }
프로필 Activity를 CLEAR_TOP 플래그와 함께 사용하신 이유가 있나요?

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileViewModel.kt
> +    private fun setActivitiesState(activities: List<Activity>) {
프로퍼티처럼 메서드에도 State 프리픽스는 제외해도 괜찮아 보여요!

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/uiState/ProfileUiState.kt
> +    }
Loading일 때 기존 데이터들을 모두 빈 값으로 초기화 할 필요는 없다고 생각해요 : )
ProfileUiState에 기본 값을 설정하고, copy() 메서드를 사용하면 어떨까요?

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/activity_profile.xml
> +            android:keepScreenOn="true"
실수로 추가된 속성인 것 같은데 맞나요?

2023-08-13 12:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/activity_profile.xml
> +                        tools:text="가나다라마바사아자차카타파하가나다라마바사아자차카타파하가나다라마바사아자차" />
이런 문구보다는, Figma에 제시되어 있는 문구를 보여주는 것이 어떨까요?

2023-08-13 15:39 UTC, chws0508 requested changes
구현이 너무 힘들어서 코드리뷰 할 시간이 부족하네요 ㅠㅠ 일단 최대한 해보았습니다.

2023-08-13 15:39 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentAdapter.kt
> +    private val onAuthorView: (Long) -> Unit,
저는 개인적으로 showProfile 이라고 하는게 좋아보여요. 어떤 행동을 해야하는지를 넘겨야 하지 않을까 하는 생각입니다. onDelete 도 deleteComment 로 바꾸는것이 좋아보여요. ViewHolder 에서 setOnClickLister{ showProfile } 이런 형태가 더 가독성이 좋다는 의견입니다.

2023-08-13 15:39 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
> +        viewModel.fetchMember(memberId)
viewModel init 블럭으로 옮기는게 좋을 것 같아요. 화면이 회전 될때마다 이 로직을 실행해요.

2023-08-13 15:39 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
> +    }
동의합니다

2023-08-13 15:39 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
> +        }
저도 프로필 조회할 때 그냥 단순 생성하는게 좋을 것 같아요

2023-08-13 15:39 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileViewModel.kt
> +    private fun setActivitiesState(activities: List<Activity>) {
저는 개인적으로 State 가 있는게 가독성이 더 좋아보여요... 없으면 가독성이 떨어질 것 같습니다.

2023-08-13 15:39 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/uiState/ProfileUiState.kt
> +    }
동의합니다

2023-08-13 15:39 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/layout/activity_profile.xml
> +                        tools:text="가나다라마바사아자차카타파하가나다라마바사아자차카타파하가나다라마바사아자차" />
ㅋㅋㅋㅋㅋ

2023-08-13 19:13 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/CategoryTag.kt
> +        background = ContextCompat.getDrawable(context, R.drawable.bg_profile_categorytag)
일단은 이전의 컨벤션대로 진행해야 할 것 같아요. 바꿔야할 게 너무 많네요. 
그래서 지금 바꾸면 많은 파일이 바뀌었다고 뜰 것 같아요.
한 번에 바꾸면 좋을 것 같아요!

2023-08-14 03:21 UTC, chws0508 approved these changes

2023-08-14 03:56 UTC, tmdgh1592 approved these changes

2023-08-14 03:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentAdapter.kt
> +    private val onAuthorView: (Long) -> Unit,
자식 댓글 뷰 홀더에게 필요한 건 댓글 삭제하는 작업과 작성자 프로필을 조회하는 작업을 정의한 함수가 필요하지, 그 함수가 언제 실행되어야 할 지는 뷰 홀더 밖에서 알 필요가 없네요. 따라서  on[명사][동사] 보다 명령형의 함수명이 더 낫겠군요! 👍

2023-08-14 06:05 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
> +    }
현재는 프로필 정보를 가져올 때만 memberId가 필요합니다. 하지만 댓글 화면처럼 댓글 가져오기, 댓글 수정, 댓글 삭제, 대댓글 화면 이동 기능에서 eventId가 필요해서 CommentFragment의 멤버 변수로 eventId를 설정한 것처럼, ProfileActivity에서도 향후 추가될 코드에서 쉽게 사용하려면 memberId가 멤버 변수로 존재하는 것이 더 좋다고 생각합니다.

2023-08-14 06:17 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileViewModel.kt
> +    private fun setActivitiesState(activities: List<Activity>) {
다른 뷰모델 함수에서 `changeToProfileFetchingErrorState()`, `changeToNotLoginState()` 이러한 네이밍을 사용하고 있는 것처럼 맞췄습니다 😢

2023-08-14 06:24 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/uiState/ProfileUiState.kt
> +    }
```
        ProfileUiState(
            isLoading = true,
            isFetchingError = false,
            isLoginMember = false,
            memberId = -1,
            memberName = "",
            description = "",
            memberImageUrl = "",
            fields = listOf(),
            educations = listOf(),
            clubs = listOf(),
        )
```
이러한 기본 값들은 사실 "처음 로딩중 상태"라는 의미를 담고 있기 때문에, 저는 "처음 로딩중 상태"를 생성하는 정적 팩토리 메서드를 사용하는 것이 좋다고 생각합니다.기본 생성자만 보면 "처음 로딩중 상태"를 생성한다는 것을 알 수 없기 때문입니다.

2023-08-14 07:00 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/activity_profile.xml
> +                        tools:text="가나다라마바사아자차카타파하가나다라마바사아자차카타파하가나다라마바사아자차" />
디자인 툴을 사용할 때 글자 수가 많을 때 어떻게 보여지는 지 쉽게 알기 위해 저렇게 설정했습니다 👍

2023-08-14 07:06 UTC, merged