Feature/#42 저장된 활동들을 전체 조회
woowacourse-teams/2023-emmsale pull request #43
Opened 2023-07-17 11:08 UTC by java-saeng

## #️⃣연관된 이슈
- #42 

## 📝작업 내용
- data.sql, schema.sql 를 통해 mock data 생성
- application.yml 에서 sql.init.mode always로 변경
- careers.http 생성
- 처음 사용자가 정보를 등록하기 위해서 필요한 "선택 정보들" 조회하는 API 구현

### 스크린샷
![image](https://github.com/woowacourse-teams/2023-emmsale/assets/62413589/ff1dd0fa-4298-4c70-b2eb-9e54cd862c68)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

close #42

2023-07-17 11:32 UTC, Hyeonjae-K approved these changes
코드 라인 수도 적고 깔끔하게 구현해 주셨네요👍
수고하셨습니다!

2023-07-18 03:29 UTC, amaran-th requested changes
수고하셨습니다~!
2가지 리뷰 남겼으니 필요에 따라 반영해주시고 다시 리뷰 요청 부탁드립니다!

2023-07-18 03:29 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/career/application/CareerService.java
> +
개인적인 생각으로 API가 항상 일정한 형식의 데이터를 주면 좋을 것 같아서 Map을 정렬해주면 좋을 것 같아요!
정렬 작업은 아래처럼 EnumMap으로 만들고 sort() 메서드로 수행해주면 될 것 같아요.
> 3.7. Map를 다른 타입으로 리턴하기
> ```java
>EnumMap<OrderType, List<Order>> collect9 = 
>   orders.stream().collect(groupingBy(Order::getOrderType, () -> new EnumMap<>(OrderType.class), toList()));
> ```
> 마지막으로 위의 모든 예제는 Map타입으로 리턴을 하고, 대부분 groupingBy의 classfier, downStream 예제만 살펴봤다. 이번에는 mapFacotry를 통해서 Map타입이 아닌 EnumMap타입으로 리턴하는 예제를 살펴보자.

[EnumMap이란](https://hudi.blog/java-enum-map/)
[group by](https://umanking.github.io/2021/07/31/java-stream-grouping-by-example/)

2023-07-18 03:29 UTC, amaran-th commented on backend/emm-sale/src/main/resources/application.yml
> +      mode: always
혹시 이 설정은 왜 추가해 주신 건가요??
MySQL 서버를 사용하게 되면 해당 설정은 없어도 괜찮을 것 같습니다!

2023-07-18 03:44 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/career/application/CareerService.java
> +
감사합니다 ! EnumMap 사용하고, 활동 이름을 통해 정렬하여 일정한 형식의 데이터를 반환하도록 했습니다!

2023-07-18 03:49 UTC, amaran-th approved these changes
확인했습니다~~!

2023-07-18 03:51 UTC, merged