Feature/#145 태그 활동 생성 api 구현
woowacourse-teams/2023-emmsale pull request #511
Opened 2023-09-01 06:48 UTC by amaran-th

## #️⃣연관된 이슈
#145

## 📝작업 내용
관리자 페이지에 연동시킬 태그 생성 API와 활동 생성 API를 추가하였습니다.

## 예상 소요 시간 및 실제 소요 시간
예상: 9/1=>실제: 9/1

2023-09-01 08:28 UTC, hyeonjerry approved these changes
크게 수정할 점은 보이지 않았으나 몇 가지 의견과 질문 남겼습니다.
한 번 확인 후 머지해 주세요.

2023-09-01 08:28 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/activity/api/ActivityApi.java
> +    return ResponseEntity.ok(activityCommandService.addActivity(request));
201 CREATED가 더 잘 어울리는 것 같아요!

2023-09-01 08:28 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/activity/application/ActivityCommandService.java
> +    validateAlreadyExist(name);
activity 객체를 생성하기 전에 validate를 두어도 좋을 것 같습니다.

2023-09-01 08:28 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/config/CorsConfig.java
> +        .allowedHeaders("*");
제가 잘 몰라서 그러는데 혹시 `allowedOrigins`가 없으면 와일드카드로 들어가게 되나요? 만약 그렇다면 `allowedOrigins`에 테스트를 위한 localhost:3000과 prod.kerdy.kro.kr만 허용하는게 좋을 것 같아요.

2023-09-01 08:28 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/tag/api/TagApi.java
> +    return ResponseEntity.ok(commandService.addTag(tagRequest));
여기도 status code를 201 CREATED로 바꾸는거 한 번 생각해 주세요.

2023-09-02 02:15 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/activity/application/ActivityCommandService.java
> +    validateAlreadyExist(name);
감사합니다! 반영하겠습니다~~

2023-09-02 03:14 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/config/CorsConfig.java
> +        .allowedHeaders("*");
오 실험해봤는데 그런 것 같습니다!
의견 반영해서 allowedOrigins()로 어드민 페이지 url만 허용하도록 했습니다.
다만 어드민 페이지 url은 외부로부터 숨기는 편이 좋을 것 같아, 로컬 application.yml에 data.admin-url 값으로 localhost:3000을, 서브모듈의 yml 파일들에는 실제 배포된 어드민페이지의 url을 설정해주었습니다.
좋은 의견 감사합니다!

2023-09-02 03:42 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/activity/api/ActivityApi.java
> +    return ResponseEntity.ok(activityCommandService.addActivity(request));
반영했습니다!

2023-09-02 03:42 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/tag/api/TagApi.java
> +    return ResponseEntity.ok(commandService.addTag(tagRequest));
반영했습니다~!

2023-09-03 12:20 UTC, hong-sile approved these changes
전체적으로 자잘한 작업이네요 수고하셨습니다.

2023-09-03 12:20 UTC, hong-sile commented on backend/emm-sale/src/documentTest/java/com/emmsale/ActivityApiTest.java
> +    when(activityCommandService.addActivity(any())).thenReturn(response);
이건 개인적인 건데, moking할 때 단순하게 any로 매칭하지말고, any(AcitivityAddRequest.class)나 request 객체 자체를 넣어보는 건 어때요?

조금 더 검증을 잘 할 수 있을 것 같아요.

2023-09-03 12:20 UTC, hong-sile commented on backend/emm-sale/src/documentTest/java/com/emmsale/TagApiTest.java
> +    when(tagCommandService.addTag(any())).thenReturn(response);
요것도! 위랑 같습니다. 한 번 고민해보시고, 답해주세요

2023-09-03 12:20 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/activity/api/ActivityApi.java
> +  public ResponseEntity<ActivityResponse> addActivity(
저희 이런 activity를 추가하는 admin만 접근하는 api의 경우 endPoint를 분리하는 것은 어떤가요?

2023-09-03 12:20 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/tag/api/TagApi.java
> +  public ResponseEntity<TagResponse> addTag(@RequestBody final TagRequest tagRequest) {
NIT: addTag보다 create 어떠신가요? add라고 하니까 멤버에 추가하는 느낌?이라서 그렇습니다.

2023-09-03 12:20 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/config/CorsConfig.java
> +        .allowedHeaders("*");
별도로 숨기는 거 좋은 것 같아요! 👍

2023-09-04 16:13 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/activity/api/ActivityApi.java
> +  public ResponseEntity<ActivityResponse> addActivity(
저도 찬성합니다,,

나중에 filter나 interceptor를 통해서 /admin/** 를 통해 아무도 접근하지 못하도록 쉽게 막을 수 있을 것 같아서요

2023-09-04 16:14 UTC, java-saeng requested changes
고생하셨습니다 !!

저는 관리자 관련 API는 /admin 으로 시작하는게 어떤가 싶어서 의견 나누고자 Request changes 보내겠습니다!!

왜냐하면 나중에 /admin/** 이런 식으로 와일드카드를 통해서 관리자 외 사람들의 접근을 막을 수 있을 것 같아서요!!

2023-09-06 06:41 UTC, amaran-th commented on backend/emm-sale/src/documentTest/java/com/emmsale/ActivityApiTest.java
> +    when(activityCommandService.addActivity(any())).thenReturn(response);
반영했습니다!

2023-09-06 08:15 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/tag/api/TagApi.java
> +  public ResponseEntity<TagResponse> addTag(@RequestBody final TagRequest tagRequest) {
오 말씀을 듣고 보니 그렇게 보이네요!
반영하겠습니다~

2023-09-06 08:26 UTC, amaran-th commented on backend/emm-sale/src/documentTest/java/com/emmsale/TagApiTest.java
> +    when(tagCommandService.addTag(any())).thenReturn(response);
말씀하신대로 매개변수의 타입을 명시적으로 지정해주는 것 좋아보입니다!
반영할게요~~

2023-09-06 08:31 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/activity/api/ActivityApi.java
> +  public ResponseEntity<ActivityResponse> addActivity(
오 좋은 의견인 것 같습니다! 그럼 혹시 그 작업의 경우 admin 계열 API를 리스트업한 뒤에 별도의 이슈로 진행해도 괜찮을까요??
지금 바로 admin 페이지를 사용하려면 이 PR을 머지해서 CORS 이슈가 해결되어야 해서요...!
해당 PR 머지 후 admin API의 권한을 제한하는 작업을 할 예정인데, 그 떄 admin 패키지를 분리하는 작업을 같이 해주면 될 것 같습니다!

2023-09-07 01:35 UTC, java-saeng approved these changes

2023-09-07 01:41 UTC, merged