Feature/#499 피드 crud 기능 구현
woowacourse-teams/2023-emmsale pull request #517
Opened 2023-09-05 09:32 UTC by hyeonjerry

## #️⃣연관된 이슈
- #499 

close #499 

## 📝작업 내용
- 피드 Create api 구현
- 피드 Read api 구현
- 피드 Update api 구현
- 피드 Delete api 구현
- 차단된 사용자의 피드 차단 기능 구현

## 예상 소요 시간 및 실제 소요 시간
4일 / 5일

2023-09-06 23:45 UTC, amaran-th approved these changes
수고하셨습니다~~!! 크게 변경할 내용은 없는 것 같아요.
코멘트를 하나 남겨뒀는데 확인 부탁드려요!
미리 approve해두겠습니다!

2023-09-06 23:45 UTC, amaran-th commented on backend/emm-sale/src/main/resources/schema.sql
> +alter table comment rename column event_id to feed_id;
feed CRUD를 테스트할 수 있는 http 파일도 추가해주시면 좋을 것 같아요~!!

2023-09-13 02:19 UTC, java-saeng requested changes
많은 기능  +  기존 코드 변경하시느라 고생 많으셨습니다

리뷰가 꽤 되는 것 같은데 반영하시고 다시 Request Changes 부탁드립니다!!

2023-09-13 02:19 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
> +        .collect(Collectors.toMap(FeedCommentCount::getFeed, FeedCommentCount::getCount));
Feed에 EQ&HC가 정의되어있지 않은데 해시맵을 통해 맵핑해줄 때, 문제가 생길 수 있지 않나요??

2023-09-13 02:19 UTC, java-saeng commented on backend/emm-sale/src/main/resources/schema.sql
> +alter table comment rename column event_id to feed_id;
동의합니다

2023-09-13 02:39 UTC, amaran-th approved these changes
지난번에 리뷰한 이후 갱신된 내용에 대해 리뷰 완료했습니다!
전체적으로 다른 분이 언급해주신 내용 제외하고 크게 수정할 부분은 없어보여요.
다만 코멘트 하나 남겨두었으니 확인 부탁드립니다.
미리 Approve해둘게요!

2023-09-13 02:39 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
> +        .collect(Collectors.toList());
혹시 Feed 리스트의 순서 보장은 어떻게 이루어지나요?
createdAt을 기준으로 정렬하는 코드가 필요할 것 같은데 혹시 제가 못 찾은 거라면 알려주세요

2023-09-13 04:46 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/feed/api/FeedApi.java
> +  @GetMapping("/{id}")
제가 잘 이해를 못했는데 혹시 38번 라인의 `@GetMapping("/{id}")`을 위에 케밥케이스 형태와 같이 `GetMapping("/{feed-id}")`로 수정하라는 말씀이실까요?

2023-09-13 05:21 UTC, hong-sile requested changes
제리 사이즈가 크다보니 평소보다 조금 코멘트가 많네요.

한 번 확인 부탁드려요!

2023-09-13 05:21 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedCommandService.java
> +    validateFeedOwner(member, feed);
피드 같은 경우 softDelete를 하는데, 이것도 한번 논의를 해봐야할 것 같긴하네요

혹시 softDelete로 구현하신 이유가 있을까요?

2023-09-13 05:21 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
> +    validateDeletedFeed(feed);
이 valdateDeletedFeed가 계속 쓰인다면, 개인적으로 findById에서 쿼리로 isDelete옵션이 true인 것만 가져오도록 하는 것도 괜찮을 것 같아요.

2023-09-13 05:21 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
> +        feedCommentCountMap.put(feed, DEFAULT_COMMENT_COUNT);
이 코드는 취향차이일 수 있어요.
```java
feedCountMap = feeds.stream()
.collect(toMap
  feed -> feed,
  feed -> DEFAULT_COMMENT_COUNT
)

feedCountMap.putAll(feedCommentCountMap);
```
처럼 구성하는건 어떤가요.

저는 람다에서, 외부값을 변경하는 코드를 작성하는게 그렇게 좋지 못하다고 생각해서요.

한번 보고, 적당하게 반영할만한거 반영해주시면 될 것 같아요.

2023-09-13 05:21 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/feed/application/FeedCommandServiceTest.java
> +  }
여기서 actual을 actual을 검증하고 있네요. 수정해주세요...

2023-09-13 05:21 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/feed/application/FeedCommandServiceTest.java
> +      feedRepository.save(피드);
혹시 삭제했다가 저장하는 이유가 있나요..?
아 혹시, Transaction 범위 때문에 변경감지가 안먹어서 이렇게 하신건가요?

2023-09-13 05:29 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/feed/api/FeedApi.java
> +  public FeedDetailResponse findDetailFeed(@PathVariable final Long id) {
저도 우르가 말씀하신걸 듣고 나니 추상적인 네이밍은 지양해야 겠다는 생각이 드네요.
반영했습니다.

2023-09-13 06:08 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedDetailResponse.java
> +    final WriterProfileResponse writerResponse = WriterProfileResponse.from(feed.getWriter());
저도 기존에는 우르가 말씀하신 것과 같이 불필요한 depth라 생각하여 대체로 데이터를 하나의 depth에 나열하는 방식으로 구현했습니다.
하지만 최근에 톰켓 미션을 진행하며 쿼리 파라미터를 파싱하고 맵으로 저장하는 과정을 겪어보니 그동안 json의 장점 중 하나인 구조화된 데이터의 전달을 잘 활용하지 못하고 있다는 생각이 들었습니다.
따라서, 위와 같이 연관된 데이터끼리 묶어서 구조적으로 전달하므로써 api를 분석하고 사용하는데 드는 인식 비용을 줄일 수 있다고 생각하여 위와 같이 구현했습니다.

2023-09-13 06:21 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
> +        .collect(Collectors.toMap(FeedCommentCount::getFeed, FeedCommentCount::getCount));
위의 경우에는 운이 좋게도  문제가 발생하지 않을 것 같습니다.
왜냐하면 36번 라인에서 모든 피드를 가져와 jpa에 로드가 되어있는 상태이므로 피드의 동일성이 보장됩니다. 따라서, 같은 주소값을 보장하므로 문제가 발생하진 않습니다.
하지만 우르가 말씀하신 것처럼 jpa 컨텍스트에 의존하여 굳이 EQ&HC를 재정의하지 않을 이유는 없을 것 같습니다.
반영하겠습니다.

2023-09-13 06:24 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
> +        .collect(Collectors.toList());
테스트에서는 정렬해서 검증 해놓고 순서 보장이 되지 않는다는걸 깜빡했네요ㅠㅠ 감사합니다.
스캇과 얘기해본 결과 최신순으로 정렬하여 반환하는 것으로 얘기했습니다!!

2023-09-13 06:33 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/feed/domain/Feed.java
> +  private List<Comment> comments;
처음에 엔티티를 설계할 때 Feed에 달린 Comment를 직접 참조할 것으로 예상되어 OneToMany 단방향 참조를 생각했으나 OTM 단방향 참조는 여러 문제를 야기할 수 있으므로 OTM, MTO 양방향 참조로 구현하게 되었습니다.
하지만 구현을 하다 보니 api가 분리되어 피드에서 직접 댓글을 가져올 일이 없어졌네요,, 간접 참조로 수정하겠습니다.

2023-09-13 06:35 UTC, hyeonjerry commented on backend/emm-sale/src/documentTest/java/com/emmsale/FeedApiTest.java
> +    doNothing().when(feedCommandService).deleteFeed(any(), any());
역시 테스트의 왕

2023-09-13 07:09 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedSimpleResponse.java
> +    final Feed feed = entry.getKey();
이 부분 관련해서는 구현할 당시에 뷰가 나오지 않아 당근 뷰로 하기로 하여 당근 뷰를 참고하여 구현했습니다.
당근 뷰를 보시면 아시다시피 작성자에 대한 정보는 나오지 않더라구여,,

2023-09-13 07:55 UTC, hyeonjerry commented on backend/emm-sale/src/test/java/com/emmsale/feed/application/FeedCommandServiceTest.java
> +      feedRepository.save(피드);
피드의 `delete`는 db에서 해당 피드를 삭제하는 것이 아닌 피드의 isDeleted를 `true`로 바꾸는 메서드입니다.

2023-09-13 10:45 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedCommandService.java
> +    validateFeedOwner(member, feed);
피드를 hardDelete하면 댓글만 삭제할 경우 softDelete, 피드를 삭제할 경우 hardDelete를 해야 하고 자신이 달았던 댓글도 자신의 의지와 상관없이 삭제되므로 정책적으로 충분한 토의가 진행되지 않아 일단 softDelete 방식으로  구현했습니다.

2023-09-13 10:46 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
> +    validateDeletedFeed(feed);
이건 사용자가 삭제된 피드를 상세 조회할 경우 예외처리를 위해 위와 같이 구현했는데 혹시 홍실이 이해하신 코드의 동작을 첨언해 주실 수 있나요?

2023-09-15 01:04 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/feed/api/FeedApi.java
> +  @GetMapping("/{id}")
네넵!! 맞습니다

2023-09-15 03:21 UTC, amaran-th approved these changes
수정사항 반영된 것 확인했습니다! 수고하셨습니다~!

2023-09-18 05:00 UTC, hong-sile approved these changes
리뷰를 잘 반영해주셨군요. 코멘트 하나 남겼으니 확인 부탁드려요.

미리 approve해두겠습니다.

2023-09-18 05:00 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/feed/domain/Feed.java
> +  public boolean equals(final Object o) {
Entity의 equals, hashcode의 경우에는 인텔리제이가 기본으로 제공해주는 포맷을 썼을 때 문제가 발생할 수 있습니다.

https://tecoble.techcourse.co.kr/post/2022-10-17-jpa-hibernate-proxy/

해당 글을 한번 참고하고 변경해보시면 좋을 것 같아요.

2023-09-18 05:05 UTC, java-saeng approved these changes
리뷰 반영하시느라 고생 많으셨습니다 !!

2023-09-18 08:22 UTC, merged