Feature/#507 쪽지함에서 쪽지방 목록 조회
woowacourse-teams/2023-emmsale pull request #523
Opened 2023-09-08 05:55 UTC by java-saeng

## #️⃣연관된 이슈
- #507

## 📝작업 내용

쪽지 목록함 조회하는 기능입니다.
최근 메시지 1개만을 보여주기 때문에 모든 메시지를 조회해서 애플리케이션 내에서 처리하는게 비효율적인 것 같아서,
native query 를 사용하여 조회했습니다.

엔티티 설계는 Room 과 Message가 있습니다.
Room 은 복합키로 (room_id, member_id)를 가지고 있습니다.
room_id는 UUID이구요.

Message는 room_id를 참조하고 있습니다.

이렇게 한 이유는 다대다 관계인데 1:N, N:1로 맵핑해도 Room이 가지는 칼럼이 id밖에 없습니다.
그래서 굳이 다대다를 풀 필요가 없다고 생각하여 이렇게 설계를 했습니다.

### 스크린샷 (선택)
![image](https://github.com/woowacourse-teams/2023-emmsale/assets/62413589/a6e0a897-b023-41c8-8ef5-0d4446a7171b)
![image](https://github.com/woowacourse-teams/2023-emmsale/assets/62413589/2c6c0a74-3af2-41fb-b236-df3ec50e5629)

2023-09-11 08:33 UTC, hong-sile requested changes
요구사항이 조금 복잡해서 양이 많네요. 질문 몇개 남겼으니 확인 부탁드려요.

2023-09-11 08:33 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +        messageOverviews,
혹시 각각의 라인마다 어떤 동작을 하는지 설명해주실 수 있나요..?

어떤 동작을 의도했는지 모르겠어요.

2023-09-11 08:33 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/infrastructure/persistence/dto/MessageOverview.java
> +}
메시지 오버뷰에서, 해당 메시지의 sender까지 반환하게 할 수 있지 않을까요?

2023-09-11 08:33 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/infrastructure/persistence/dto/MessageOverview.java
> +}
DAO에서 m2.sender를 추가할 수 있을 것 같아요.

2023-09-11 18:34 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/infrastructure/persistence/dto/MessageOverview.java
> +}
sender를 반환해야하는 이유가 무엇인지 여쭤볼 수 있을까요?

2023-09-11 18:37 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +        messageOverviews,
Room에는 현재 참여하고 있는 ID가 두 개 존재하는데, 이때 이 ID가 login한 사용자인지 상대방 ID인지 알 수 없습니다.
그래서 groupingPartnerIdByRoom를 통해 Room UUID를 key로, value로는 Room에 참여하고 있는 사용자 ID 중 로그인 한 사용자의 ID를 제외한 상대방의 ID를 가지고 있습니다.

만약 어떤 식으로 동작하는지 모르겠다가 또 있으시면 "어느 부분에서 어느 것이 이해안된다"라고 말씀해주시면 더 설명해드리기 좋을 것 같습니다.

2023-09-11 18:37 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/infrastructure/persistence/MessageDao.java
> +    sqlBuilder
어느 부분이 이해가 안되실까요?

2023-09-12 01:28 UTC, hong-sile requested changes
몇몇 추상적인 코멘트에 대한 답변을 남겼고, 코드 하나에 대해서 리뷰를 남겼어요 확인 부탁드립니다.

2023-09-12 01:28 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +        .flatMap(messageOverview -> findInterlocutorInRoom(messageOverview, loginMemberId))
여기서, room 하나당 조회를 한 번씩 하고 있어요.

RoomUUID List를 List<MessageOverView>에서 뽑아 낼 수 있으니, In절로 한번에 조회할 수 있지 않을까요?

2023-09-12 01:28 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/infrastructure/persistence/dto/MessageOverview.java
> +}
아 생각을 해보니 메시지를 보여줄 때 sender에 대한 정보가 아니라, 그냥 상대방에 대한 정보가 필요하네요.

반환되는 메시지 형태에 sender에 대한 정보를 보여줄거라 생각해서, 남긴 코멘트였는데 반환형태에 대해 잘못 이해했던 것 같아요.

2023-09-12 01:28 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +        messageOverviews,
용어 자체가 생소해서 그랬던 것 도 있고, depth가 조금 있어서 정확하게 저 메서드가 어떤 의도를 가지고 만들었는지를 제가 이해를 잘 못했던 것 같아요.

2023-09-12 06:42 UTC, hyeonjerry approved these changes
수고하셨습니다~!
몇 가지 궁금한 점이 있어서 코멘트 남겼어요.
로직상 문제될 점은 없어 보여서 Approve 하겠습니다.

2023-09-12 06:42 UTC, hyeonjerry commented on backend/emm-sale/src/test/java/com/emmsale/message_room/application/RoomQueryServiceTest.java
> +    final List<RoomResponse> expect = roomQueryService.findAll(loginMember, loginMember.getId());
이게 actual이고 위에 변수가 expect 아닌가요?

2023-09-12 06:42 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +    return roomRepository.findByUUID(messageOverview.getRoomUUID())
Jpa Repository에 `findByUUIDAndMemberId`와 같이 멤버 아이디를 함께 받아 해당하는 하나의 방만 반환하도록 할 수 있지 않을까요?

2023-09-12 06:42 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +        .flatMap(messageOverview -> findInterlocutorInRoom(messageOverview, loginMemberId))
혹시 flatMap을 사용하신 이유가 있으신가요? `findInterlocutorInRoom` 메서드를 보면 (roomUUID, loginMemberId)와 동일한 Room은 하나밖에 존재하지 않으니 `Stream<Room>`을 반환하고 있지만 사실상 `Room`과 다르지 않을 것 같아서요.
또한, `findInterlocutorInRoom` 메서드에서 roomRepository에 `findByUUIDAndMemberId`와 같이 멤버 아이디를 함께 받아 해당하는 하나의 방만 반환하는 메서드를 정의하여 `findInterlocutorInRoom` 메서드를 사용하지 않고 해결할 수 있을 것 같은데 어떻게 생각하시나요?

2023-09-12 06:48 UTC, amaran-th approved these changes
오프라인으로 기능 설계에 대해 잘 설명해주신 덕에 더 의문스러운 점은 없는 것 같습니다!
수정할만한 부분도 크게 없어서, approve하겠습니다~

2023-09-12 06:48 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +  private Map<String, Long> groupingPartnerIdByRoom(
NIT: '대화하고 있는 상대'라는 의미가 드러나도록 grouopingInterlocutorIdByRoom()으로 메서드명을 지어줘도 좋을 것 같아요

2023-09-12 06:50 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/infrastructure/persistence/MessageDao.java
> +    sqlBuilder
현장 리뷰 완료요~

2023-09-12 06:50 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +        messageOverviews,
현장 리뷰 완료요~

2023-09-12 06:50 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/infrastructure/persistence/dto/MessageOverview.java
> +}
현장 리뷰 완료요~

2023-09-12 06:52 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/dto/RoomResponse.java
> +  private final Long interlocutorId;
저도 변수명 지을 때 고민을 많이 했었습니다,, 후,,

일단 제 의견을 말씀드리자면 제리가 말씀해주신 senderID를 고민했었는데, 
여기에서 ID와 Name은 메시지를 보낸 사람이 아니라 현재 쪽지방 목록을 조회했을 때 대화 상대이기 때문에
interlocutor 를 사용했습니다!!

2023-09-12 06:54 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +    final Long loginMemberId = loginMember.getId();
validation 이 잘되면 memberId와 loginMember가 같다는 말씀 동의합니다.

그런데 뭔가 파라미터로 받는 값보다 직접 DB에서 가져온 값이 더 끌렸습니다,, ㅋㅋㅋ

2023-09-12 06:57 UTC, java-saeng commented on backend/emm-sale/src/test/java/com/emmsale/message_room/application/RoomQueryServiceTest.java
> +    final List<RoomResponse> expect = roomQueryService.findAll(loginMember, loginMember.getId());
매의 눈이십니다 바 로 수정하겠습니다

2023-09-12 07:03 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +    return roomRepository.findByUUID(messageOverview.getRoomUUID())
이 로직은 같은 쪽지방에 참여하고 있는 상대방 ID를 조회하기 위한 로직이어서, 
find할 때 필요한 MemberId를 구할 방법이 없어보입니다,,

혹시 생각하신 다른 방법이 있을까요?

2023-09-12 07:05 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +        .flatMap(messageOverview -> findInterlocutorInRoom(messageOverview, loginMemberId))
[이전 대답](https://github.com/woowacourse-teams/2023-emmsale/pull/523#discussion_r1322543342)

이전 대답과 유사하긴 하지만 여기서 로직은 현재 UUID의 방에서 상대방의 ID를 구하기 위함입니다. loginMemberId는 현재 대화방에 참여하고 있고, 그 대상 쪽지방에서의 상대방 ID를 구하기 위한 로직입니다.

혹시 다른 방법이 있을까요??

2023-09-12 07:19 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/dto/RoomResponse.java
> +  private final Long interlocutorId;
아아 이해했습니다.
어렵네요,,

2023-09-12 07:27 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +        .flatMap(messageOverview -> findInterlocutorInRoom(messageOverview, loginMemberId))
오,, 이렇게 하니까 Stream을 반환하는게 필요 없어지네요 반영했습니다

2023-09-12 07:44 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +    return roomRepository.findByUUID(messageOverview.getRoomUUID())
현장에서 얘기 들어보니 다른 방법이 없네요😓

2023-09-12 07:44 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +        .flatMap(messageOverview -> findInterlocutorInRoom(messageOverview, loginMemberId))
위와 동일합니다😓

2023-09-12 07:57 UTC, merged