Feature/#510 room에 쪽지 보내는 기능
woowacourse-teams/2023-emmsale pull request #525
Opened 2023-09-08 06:19 UTC by hong-sile

## #️⃣연관된 이슈
- #510 

## 📝작업 내용
- 

## 예상 소요 시간 및 실제 소요 시간
- 9/6             9/8

## 💬리뷰 요구사항(선택)
- 쪽지 보내는 로직 한번 확인 부탁드립니다.

그리고 아마 아마란스랑 제리는 Room 형태에 대해서 이해가 안 되실 수도 있어요. 일반적인 구조랑 달라서,
한 번 물어보러 오시죠

2023-09-11 18:46 UTC, java-saeng requested changes
기능에 대해 리뷰 남겨보았습니다  !

이번 PR에서는 홍실의 바쁨이 느껴졌습니다,, 미션과 프로젝트를 병행하다보니 어쩔 수 없다고 생각해요.
고생하셨습니다

2023-09-11 18:46 UTC, java-saeng commented on backend/emm-sale/src/documentTest/java/com/emmsale/MockMvcTestHelper.java
> +  protected MessageCommandService messageCommandService;
👍

2023-09-11 18:46 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/api/MessagesApi.java
> +  public ResponseEntity<Void> sendMessage(final MessageSendRequest request, final Member member) {
`@RequestBody`가 빠진 것 같은데여,,?

2023-09-11 18:46 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/api/MessagesApi.java
> +  public ResponseEntity<Void> sendMessage(final MessageSendRequest request, final Member member) {
+ 축약어보다는 길어도 클래스 이름은 어떠신가여

2023-09-11 18:46 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
> +  public void sendMessage(final MessageSendRequest request, final Member member) {
여기도 축약어가 있습니다

2023-09-11 18:46 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
> +    final RoomId senderRoomId = new RoomId(roomId.toString(), request.getSenderId());
UUID를 계속 string으로 변환할텐데 33번째 줄에서 처음부터 바로 String형 UUID를 받는게 어떠신가요?

2023-09-11 18:46 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageExceptionType.java
> +    return null;
null..?

2023-09-12 00:48 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageExceptionType.java
> +    return null;
오 이건 좀 쉽지 않네요.

2023-09-12 00:55 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/api/MessagesApi.java
> +  public ResponseEntity<Void> sendMessage(final MessageSendRequest request, final Member member) {
추가하겠습니다. 이게 빠져버렸네요.

2023-09-12 00:56 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
> +    final RoomId senderRoomId = new RoomId(roomId.toString(), request.getSenderId());
그러네요 변환하는 로직이 세군데 있으니까, 바로 String으로 반환하도록 수정하겠습니다.

2023-09-12 07:13 UTC, amaran-th approved these changes
수고하셨습니다~~!
자잘한 코멘트 2개정도 남겼는데 확인해주시고 판단해주세요~
미리 approve할게요!

2023-09-12 07:13 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageExceptionType.java
> +      "로그인한 사용자와 메세지를 보내는 사용자가 다릅니다.");
사소하지만 `HttpStatus.FORBIDDEN` 앞에도 줄바꿈이 있으면 좀더 보기좋을 것 같습니다!

2023-09-12 07:59 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
> +    saveRooms(request, roomId);
인정 두개 드리겠습니다. 검증하는 것이 필요하긴 하겠네요.

2023-09-12 08:08 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
> +    saveRooms(request, roomId);
반영했어요!!

2023-09-12 08:17 UTC, java-saeng approved these changes

2023-09-12 09:14 UTC, hyeonjerry approved these changes
수고하셨습니다~!
크게 수정할 점은 보이지 않네요.

2023-09-13 02:11 UTC, merged