Feature/#502 이미지 처리 구현
woowacourse-teams/2023-emmsale pull request #529
Opened 2023-09-10 12:13 UTC by amaran-th

## #️⃣연관된 이슈
#502

## 📝작업 내용
이미지를 S3에 업로드하는 기능과 삭제하는 기능을 구현하였습니다.

## 예상 소요 시간 및 실제 소요 시간
예상 - 9/9(토요일)
실제 - 9/10(일요일)

## 💬리뷰 요구사항(선택)
Controller 코드는 추후 삭제할 예정이니 무시해주세요~~
[submodule 파일](https://github.com/java-saeng/kerdy-submodule)도 수정했으니 함께 확인해주시면 좋을 것 같습니다!

2023-09-12 06:32 UTC, java-saeng requested changes
이미지 저장 구현하시느라 고생 많으셨습니다!!

반영하시고 다시 리뷰 요청 부탁드려요!!

2023-09-12 06:32 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +    if (extensionIndex == -1 || !ALLOWED_FILE_EXTENSIONS.contains(
이건 제 개인적인 의견이라 반영하지 않으셔도 됩니다!!

앞에 ! 붙이는게 어떻게 보면 안보일 수도 있어서(가독성 측면) 저는 최대한 안쓰려고 합니다.

그래서 먼저 제대로 된 조건을 if문에 작성해서 early return 하고 if 분기를 만족하지 못하면 throw를 하시는게 어떠신가여?

그러면 if(extensionIndex >= 0 && ALLOWD~~) 이렇게 될 수 있을 것 같아요
이 if문 안의 조건을 의미있는 이름과 함께라면 더 가독성이 올라갈 수 있다고 생각합니다.

2023-09-12 06:56 UTC, hong-sile requested changes
리뷰 몇몇개 남겼어요. 조금 반영할 게 있긴한데 확인해보시고 적용해주세요.

2023-09-12 06:56 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/image/api/ImageTestController.java
> +   * */
요거 삭제해주시겠다고 해주셨어요.

굳이 새 이슈에서 삭제할 필요 없이 정상동작 확인했다면 지금 삭제해주시는게 좋을 것 같아요.

2023-09-12 08:46 UTC, hyeonjerry requested changes
이미 앞선 리뷰들 모두 공감하고 좋은 의견들이라 추가로 낼 의견은 없었습니다.
다만, 전체적으로 `final` 키워드가 빠진 부분이 있고 restDocs가 작성되지 않은 부분이 있었습니다.
수고하셨습니다.

2023-09-13 03:21 UTC, amaran-th commented on backend/emm-sale/src/test/java/com/emmsale/image/application/ImageServiceTest.java
> +  void uploadImages_fail_extension() {
반영했습니다! verify는 많이 안 써봤었는데 덕분에 어떤 상황에서 쓰면 될지 파악할 수 있었던 것 같습니다~

2023-09-13 03:32 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/api/ImageTestController.java
> +   * */
삭제했습니다!

2023-09-13 03:32 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +      final String fileExtension = extractFileExtension(file);
의견 반영해서 리팩토링 완료했습니다.

2023-09-13 03:33 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +      fileNameList.add(newFileName);
오 forEach가 이런 특징이 있었군요... 저도 앞으로 지양하도록 하겠습니다.
리뷰 감사합니다!
stream().map()으로 수정하니 코드도 더 깔끔해졌네요.

2023-09-13 04:12 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +  private static List<String> ALLOWED_FILE_EXTENSIONS = List.of(".jpg", ".png", ".jpeg");
반영했습니다!

2023-09-13 04:12 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +  private String extractFileExtension(MultipartFile file) {
반영했습니다!

2023-09-13 04:13 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +  public static final String EXTENSION_DELIMITER = ".";
헉 수정하는 걸 깜빡했네요;
반영했습니다!

2023-09-13 04:29 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +public class ImageService {
오 훨씬 적절한 명칭인 것 같네요! 반영하겠습니다~~!

2023-09-13 04:30 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +    if (extensionIndex == -1 || !ALLOWED_FILE_EXTENSIONS.contains(
좋은 의견인 것 같습니다! 메서드 분리해주면서 말씀하신대로 처리했습니다~

2023-09-13 04:42 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +      fileNameList.add(newFileName);
아 이거, Stream.forEach가 아니라 그냥 Collections의 forEach군요.
Collections의 forEach는 내부에서 Exception이 터져도 해당 요소까지 동작하고 다음 element를 가진 않아요.
(이 부분은 잘못 알려드렸네요)

그래도, 저는 내부 메서드가 너무 길기도 했고, Stream.map이 더 상황에 맞기도 하고 충분히 대체할 수 있는 부분이라고 생각했어요.

2023-09-13 04:42 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +      fileNameList.add(newFileName);
기능 외적으로도, forEach 같은 곳에서 다른 데에 영향을 줄 수 있는 사이드 이펙트가 발생할 수 있도록 짜는건 좋지 않은 것 같아요. 추후 디버깅 하기 어려우니까요

2023-09-13 05:15 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +  private String extractFileExtension(MultipartFile file) {
아마란스 혹시 final 이 이 부분 말고 다른 곳에도 있는 곳 같아서요 작성했던 코드들 보시면서 final 확인해주실 수 있으실까요?

2023-09-13 05:18 UTC, java-saeng approved these changes
고생하셨습니다 아마란스 !!

우리가 이전에 final 컨벤션을 정했어서, 같이 정한 컨벤션인만큼 지켜주셨으면 좋겠습니다!! 
저번 리뷰, 이번 리뷰에서도 final 을 언급한 것 같아서, 신경써주셨으면 좋겠습니다.

2023-09-13 05:18 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +    if (extensionIndex >= 0 && ALLOWED_FILE_EXTENSIONS.contains(
extensionIndex >= 0 이 무슨 뜻인가요? 매직넘버도 있어서 상수화 시키는게 낫지 않을까요?

미션 1,2 때 했던 것들이 반영되지 않아서 조금 아쉽습니다!

2023-09-13 05:18 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +  private static void validateExtension(int extensionIndex, String originalFileName) {
static 을 붙이신 이유가 있으신가요?

2023-09-13 06:29 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +  private static void validateExtension(int extensionIndex, String originalFileName) {
아이고 또 실수했네요;; private으로 변경하였습니다!

2023-09-13 06:30 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +    if (extensionIndex >= 0 && ALLOWED_FILE_EXTENSIONS.contains(
의견 반영해서 상수화시켜주었습니다! 이런 사소한 걸 자꾸 놓치게되네요;;
앞으론 더 신경쓰겠습니다.

2023-09-14 01:25 UTC, hong-sile approved these changes
전체적으로 잘 수정해주신 것 같아요. 몇몇 코멘트 남겼으니 확인해주세요. 이만 approve하겠습니다.

2023-09-14 01:25 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
> +    final ObjectMetadata objectMetadata = configureObjectMetadata(file);
별도로 분리해주신거 좋은 것 같아요 가독성이 올라갔네요.

2023-09-14 01:25 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
>  public class ImageService {
현재 커밋부분에서 ImageService가 남아있는 것 같아 보이는데, S3Client로 변경한거면, 클래스를 삭제하는건 어떨까요?

2023-09-14 01:31 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/ImageService.java
>  public class ImageService {
아 다음 PR에서 DB에 저장하는 ImageService에 구현하려고 틀을 잡아놓고 스태시해둔 상태인데, 그 과정에서 삭제하는 커밋이 올라가지 않은 것 같네요...! 삭제해서 커밋했습니다!

2023-09-14 01:40 UTC, hyeonjerry approved these changes
수고하셨습니다~!

2023-09-14 01:40 UTC, merged