Feature/#528 쪽지방 조회 api
woowacourse-teams/2023-emmsale pull request #540
Opened 2023-09-12 00:13 UTC by java-saeng

## #️⃣연관된 이슈
- #528 
- 
## 📝작업 내용

Room UUID로 Room을 조회하는 기능
Room 참여자 ID들을 통해 Room을 조회하는 기능

여기서 Room을 조회하는 것은 쪽지방 대화 내용들을 조회하는 것입니다.

## 예상 소요 시간 및 실제 소요 시간
예상 시간 9/13
실제 소요 시간 9/12

2023-09-12 08:03 UTC, amaran-th approved these changes
수고하셨습니다~! 크게 수정할만한 부분은 없는 것 같아서 approve하겠습니다!

2023-09-12 08:19 UTC, hyeonjerry approved these changes
수고하셨습니다.
몇 가지 궁금한 점이 있어 코멘트 남겨두었습니다.

2023-09-12 08:19 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/dto/MessageResponse.java
> +  private final Long senderId;
뷰가 없어서 잘은 모르겠지만 메시지를 전송한 사용자의 이름은 없어도 될까요?
자신의 닉네임이라면 구할 수 있지만 상대방의 닉네임은 안드로이드에서 구하기 어려울 것 같아서요.

2023-09-12 08:19 UTC, hyeonjerry commented on backend/emm-sale/src/test/java/com/emmsale/message_room/application/RoomQueryServiceTest.java
> +    final Member loginMember = memberRepository.findById(1L).get();
테스트 간의 중복되는 변수가 있는 것 같아요.
시간 나신다면 필드 변수로 빼면 테스트 코드의 로직에 더울 잘 집중할 수 있을 것 같아요.

2023-09-13 02:06 UTC, hong-sile requested changes
id 기준으로 room을 조회하는 것을 잘 짜주신 것 같아요. 몇몇 부분에 대한 리뷰 남겼으니 확인 부탁드립니다.

2023-09-13 02:06 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/fixture/MessageFixture.java
> +  public static Message create(
이거는 저도 궁금해요. Fixture로 보통 빼면 파라미터는 안 받고, 실제 값들을 다 넣은 상태로 반환하는데, 이 메서드는 단순하게 생성자를 바이패싱해주는 것 같아요.

2023-09-13 02:06 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/fixture/MessageFixture.java
> +  public static Message create(
근데, 메시지 같은 경우에는 senderId와 roomUUID 와 같은 외래키값이 있고, LocalDateTime같은 제어하기 힘든 요소가 있어서,
애당초 픽스쳐로 좀 만들기 빡센 친구인 것 같긴하네요.

2023-09-13 02:06 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/member/MemberFixture.java
> +  ) {
요거 픽스쳐로 만든건 괜찮네요. 픽스쳐를 이용해서, 프로덕션엔 필요없지만 테스트에선 유용한 name을 받는 생성자를 만드셨군요.

2023-09-13 04:06 UTC, java-saeng commented on backend/emm-sale/src/documentTest/asciidoc/index.adoc
> +/rooms/{room-id}?member-id=1
쿼리 스트링이랑 path 변수가 있어서 헷갈리지 마시라고 한번 적어보았습니다

2023-09-13 04:06 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/api/RoomApi.java
> +  public List<MessageResponse> findByInterlocutorIds(
맞습니다 1:1 쪽지 보내기 이런게 있을 것 같다고 하셔서, 안드분들과 얘기 나눴었습니다

2023-09-13 04:09 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/dto/MessageResponse.java
> +  private final Long senderId;
여기서 상대방의 닉네임을 구해야하는 이유가 어떤 걸까요?

현재 MessageResponse는 `하나의 메시지`를 의미하는데, 누가 보냈는지만 알면 된다고 생각했습니다.
그리고 그 ID만을 전달한 이유는 쪽지방이 1:1, 즉, senderId가 두개 존재하게 되는데 ID를 통해서 구분한다고 하시더라구요

사용자 프로필이나 이름 정보는 이제 API 를 통해서 조회하신다고 하셨습니다!

2023-09-13 04:10 UTC, java-saeng commented on backend/emm-sale/src/test/java/com/emmsale/fixture/MessageFixture.java
> +  public static Message create(
처음에는 new 로 하게 되면 Message 도메인이 변경되면 모든 테스트에 있는 생성자를 바꿔야하는데, Fixture 사용하면 편하다고 생각했어요

그런데 결국 파라미터 변수 똑같으면 변경해야할 것은 똑같네요,,,, ㅋㅋㅋ결국 다 변경되야하는 값이니까 Fixture는 지우는게 나을 듯 해보이네요,,

2023-09-13 04:28 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
> +  ) {
![image](https://github.com/woowacourse-teams/2023-emmsale/assets/62413589/27ba67e7-6731-4203-aa19-94f0675bb1c4)

맞습니다 ㅋㅋ 요런식으로 수정했습니다요

2023-09-13 06:31 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/dto/MessageResponse.java
> +  private final Long senderId;
저는 결국에 안드로이드 측에서 채팅뷰를 그릴 때 결국엔, 이미지랑 닉네임이 필요해서 
해당 API에서 한번에 보내줄지,
아니면, 두 번 요청해서 안드로이드가 그릴지를 생각했는데

이미 논의가 되있다면 괜찮은 것 같습니다.

2023-09-13 06:33 UTC, hong-sile approved these changes
확인했습니다. approve할게요

2023-09-13 06:35 UTC, merged