Feature/#524 쪽지 보낼 때 푸시 알림 보내는 기능
woowacourse-teams/2023-emmsale pull request #541
Opened 2023-09-12 05:24 UTC by hong-sile

## #️⃣연관된 이슈
- #524 

## 📝작업 내용
- 쪽지 보낼 때 푸시 알림 보내는 기능 구현

## 예상 소요 시간 및 실제 소요 시간
- 09.07/ 09.12

## 💬리뷰 요구사항(선택)
- 이벤트 리스너를 써봤는데, 이게 올바른 형태인지는 잘 모르겠어요. 
푸시 알림과 이벤트 리스너를 중점적으로 리뷰해주시면 감사하겠습니다.

2023-09-12 08:39 UTC, amaran-th approved these changes
수고하셨습니다~! 크게 수정할 부분은 없는 것 같아서 바로 approve하겠습니다~!

2023-09-12 08:39 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/GlobalControllerAdvice.java
> +    log.debug("stackTrace : ", e);
👍👍👍

2023-09-12 08:39 UTC, amaran-th commented on backend/emm-sale/src/test/java/com/emmsale/message_room/application/MessageCommandServiceTest.java
> +          () -> verify(firebaseCloudMessageClient, times(1))
👍👍

2023-09-12 10:46 UTC, hyeonjerry approved these changes
수고하셨습니다~!

2023-09-13 02:34 UTC, java-saeng requested changes
팀원 코드 이해하시느라 고생하셨습니다 !

이벤트 발행하는 부분만 코드 수정하시고 다시 리뷰 요청 주세요!

2023-09-13 02:34 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
> +  private final NotificationEventListener notificationEventListener;
이벤트 부분은 CommentCommandService#create 부분을 한번 참고해보시면 좋을 것 같습니다.

EventListener는 Event를 듣는 객체일 뿐입니다. publisher를 통해서 이벤트를 발행하게 되면 파라미터에 맞게 EventListener가 해당 Event를 Listen 하게 됩니다

2023-09-13 02:34 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageException.java
> +public class MessageException extends BaseException {
오우.. 저랑 Exception Type이 달라버리네요 

혹시 제가 이전에 머지했던 코드들 pull 하셨을까요?

이 부분은 상의를 한번 해야할 것 같습니다!

2023-09-13 02:34 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageExceptionType.java
> +public enum MessageExceptionType implements BaseExceptionType {
이 부분도 같이 얘기해봐요!

2023-09-13 02:34 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/notification/application/generator/MessageNotificationMessageGenerator.java
> +  private final MessageNotificationEvent event;
축약어 의도하셔서 사용하신걸까요?

2023-09-13 02:34 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationEventListener.java
> -
불필요한 공백이 생겼습니다 !

2023-09-13 06:36 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationEventListener.java
> -
불필요한 공백이 있어서 지운부분입니다!

2023-09-13 06:36 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/notification/application/generator/MessageNotificationMessageGenerator.java
> +  private final MessageNotificationEvent event;
네 저는 이 정도는 굳이 전체를 나타낼 필요는 없다고 생각했어요.

2023-09-13 06:37 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageException.java
> +public class MessageException extends BaseException {
같이 설계했던 부분만 pull해서 다른 것 같네요

2023-09-13 06:37 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
> +  private final NotificationEventListener notificationEventListener;
요거는 조금 심각하게 잘못짰네요.
EventListener로 변경했습니다.

2023-09-14 01:55 UTC, java-saeng approved these changes
고생고생하셨슴다

2023-09-14 03:06 UTC, merged