Feature/#535 행사 상세화면 상세정보 탭 구현
woowacourse-teams/2023-emmsale pull request #556
Opened 2023-09-15 16:37 UTC by chws0508

## #️⃣연관된 이슈
>   #535 

## 📝작업 내용
> 행사 상세정보 탭 구현 했습니다

### 스크린샷 (선택)

https://github.com/woowacourse-teams/2023-emmsale/assets/76036731/d9246435-3298-4665-9f3a-b70514919cbd

## 예상 소요 시간 및 실제 소요 시간
4시간 / 10시간

## 💬리뷰 요구사항(선택)
기관은 데이터가 없어서 화면에 표시되지 않았습니다.

이번에 EventChip 과 LocalDateTime 관련 BindingAdpater 함수를 추가했습니다.

2023-09-17 05:42 UTC, tmdgh1592 requested changes
행사 상세화면 디자인 반영하시느라 고생하셨어요 스캇! 👍
몇 가지 리뷰를 남겨놓았으니, 확인 후 `반영` or `답변` 해주세요 : )

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/model/EventDetail.kt
> +    val posterImageUrl: String,
포스터가 없는 경우가 있기 때문에 posterImageUrl이 충분히 Nullable할 수도 있다고 생각해요!
반드시 NotNull 하게 구현하신 이유가 있나요?

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultRecruitmentRepository.kt
> +            is ApiException -> ApiException(response.e)
현재 `ApiResult` 클래스에서 개선된 `ApiResponse`가 있습니다.
`ApiResponse`로 통일 부탁드립니다 😃

Ref - [ApiResponse](https://github.com/woowacourse-teams/2023-emmsale/wiki/CallAdapter-%EB%A7%88%EC%9D%B4%EA%B7%B8%EB%A0%88%EC%9D%B4%EC%85%98#4%EA%B0%80%EC%A7%80-%EC%9D%91%EB%8B%B5-%EC%83%81%ED%83%9C)

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultScrappedEventRepository.kt
> +            .map(List<ScrappedEventResponse>::toData)
변경된 형식(ApiResponse)을 잘 반영해주셨네요 👍
깔끔합니다!

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultScrappedEventRepository.kt
> +        return scrappedEventService.scrapEvent(scrappedEventCreateRequest)
크리티컬한 리뷰는 아니지만 고민해보면 좋을 것 같아서 리뷰남깁니다!
변수명과 클래스 이름이 동일하기도 하고, 클래스명만 보더라도 바로 흐름을 파악할 수 있을 것 같아요!
변수를 생성하지 않는, 아래와 같은 코드는 어떠신가요?
제 눈에는 조금 더 코드가 간결해지는 것 같아요 😃

```kotlin
return scrappedEventService.scrapEvent(
    ScrappedEventCreateRequest(eventId)
)
```

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultScrappedEventRepository.kt
>                  DEFAULT_HEADER,
Success에는 기본 헤더가 있기 때문에, 필요한 헤더가 아니라면 DEFAULT_HEADER는 지워도 됩니다!

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/FetchResultUiState.kt
> +}
> 데이터를 가져오는 UiState 를 FetchResultUiState 추상 클래스로 나타내었습니다.

질문이 있어 코멘트 남깁니다.
1. 앞으로 `Remote`로부터 어떤 값을 가져온다면 `FetchResultUiState`를 사용하면 되나요?

WIKI에 문서화 해주시면 좋을 것 같아요. 👍

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ChipGroupBindingAdapter.kt
> +    addEventTags(tags ?: emptyList())
기본적으로 권장되는 방식은 BindingAdapter의 속성명과 함수명을 맞추어주는 것입니다.
`app:eventChips`라면 함수명은 `ChipGroup.setEventChips`이 권장됩니다.

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ChipGroupBindingAdapter.kt
> +fun ChipGroup.chips(tags: List<String>?) {
`tags: List<String>?`에서 타입이 Nullable한 이유가 있나요?

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/LocalDateTimeBindingAdapter.kt
> +    localDateTime: LocalDateTime? = null,
함께 작업한 내용이라 저는 리뷰를 생략하겠습니다.

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/EventTagChip.kt
> +class EventTagChip : AppCompatTextView {
`EventTag` -> `EventTagChip`
명확한 네이밍 좋습니다. 👍

가능하다면 통일성을 위해 다른 커스텀 Chip View의 네이밍도 변경해주실 수 있나요?

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/EventDetailActivity.kt
> +            handleEvent(event)
`viewModel.scrapUiEvent.observe(this, ::handleEvent)` 로도 작성해볼 수 있지 않을까요?

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/EventDetailActivity.kt
> +            EventInfoUiEvent.SCRAP_DELETE_ERROR -> binding.root.showSnackBar("스크랩 삭제 불가")
하드코딩 대신 strings.xml을 사용해주세요 : )

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetailInfo/EventInfoFragment.kt
> +    //         } else {
사용하지 않는 코드/주석은 제거해주셔도 좋을 것 같아요 : )

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetailInfo/EventInfoViewModel.kt
>                  else -> _isError.value = true
특정 UIState에 대한 에러 상태가 밖에 존재하고 있네요.
여기에서는 `FetchResultUiState`를 사용하지 않은 이유가 있나요?

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_conference.xml
> +            app:eventChips="@{event.tags}"
이런식으로 사용할 수도 있겠군요 👍
Activity의 코드가 훨씬 줄어들 것 같네요!

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/values/date_time_patterns.xml
> +    <string name="date_range" translatable="false">%s ~ %s</string>\
끝에 `\` 오탈자를 지워주세요.

2023-09-17 05:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/values/strings.xml
>      <string name="eventdetail_apply_date">접수 기간</string>
event detail 화면에서 사용되는 문자열인가요?
그렇다면 앞에 `eventdetail_` 접두사를 붙여주세요 : )

2023-09-17 09:04 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultRecruitmentRepository.kt
> +            is ApiException -> ApiException(response.e)
여긴 다른 브렌치에서 작업할 예정이에요 ㅎㅎ

2023-09-17 09:09 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/values/strings.xml
>      <string name="eventdetail_apply_date">접수 기간</string>
eventInfo Fragment에서 활용되는 문자열 입니다! 따로 분리해야 겠네요!

2023-09-17 09:13 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/model/EventDetail.kt
> +    val posterImageUrl: String,
다시 생각해보니 nullable 하게 구현하는 것이 좋겠네요!

2023-09-17 09:14 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultScrappedEventRepository.kt
> +        return scrappedEventService.scrapEvent(scrappedEventCreateRequest)
좋네요! 반영할게용!

2023-09-17 09:15 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultScrappedEventRepository.kt
>                  DEFAULT_HEADER,
아주 좋아요 ~

2023-09-17 09:16 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/FetchResultUiState.kt
> +}
넵! Flow를 사용하기 전까진 저 모델을 사용하는게 어떻냐는 얘기를 토마스와 나눴었습니다~ 부나의 생각은 어떠신가요?

2023-09-17 09:18 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ChipGroupBindingAdapter.kt
> +fun ChipGroup.chips(tags: List<String>?) {
예상치 못하게 nullable 한 데이터를 화면에 입력했을 때, 앱이 터지는걸 방지하고 싶었어요! 어떻게 생각하시나요?

2023-09-17 09:18 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/EventTagChip.kt
> +class EventTagChip : AppCompatTextView {
넵... !

2023-09-17 09:47 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ChipGroupBindingAdapter.kt
> +fun ChipGroup.chips(tags: List<String>?) {
라고 생각했는데, 현재 백엔드에서 tag 없으면 emptyList 를 주는게 아니라, Null로 주고있네요... 일단은 Nullable 하게 두겠습니다.

2023-09-17 09:50 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetailInfo/EventInfoViewModel.kt
>                  else -> _isError.value = true
현재 이 뷰모델은 사용하지 않는 뷰모델이네요! 삭제하도록 하겠습니다!

2023-09-19 01:03 UTC, tmdgh1592 requested changes
리뷰 잘 반영해주셨습니다.
따로 문제가 없어서 머지하겠습니다 👍

2023-09-19 01:03 UTC, tmdgh1592 approved these changes

2023-09-19 01:03 UTC, merged