Feature/#629 데이터가 없는 리스트 화면에 뷰 보여주기
woowacourse-teams/2023-emmsale pull request #647
Opened 2023-09-25 12:38 UTC by tmdgh1592

## #️⃣연관된 이슈
>  #629 

## 📝작업 내용
> 이슈에 나타나 있는 5가지 화면에 대해, 빈 리스트 화면은 별도의 커스텀 뷰로 꽉 차 보이도록 하여 UX를 개선하였습니다.

### 스크린샷 (선택)
![Screenshot_20230925_181918](https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/bb07fa1a-195b-4f0e-b49a-aa3336d412ff)
![Screenshot_20230925_150031](https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/c31b5169-f68e-4ed2-a21c-ecb6e5111d7c)

## 예상 소요 시간 및 실제 소요 시간
> 3시간 / 2시간

## 💬리뷰 요구사항(선택)

> `NoContentView`라는 커스텀뷰를 통해 화면이 없는 경우 간단하게 UI를 구현할 수 있도록 하였습니다.
이슈와는 관련없지만, Data 모델의 프로퍼티명을 일부 바꾸었습니다.

2023-09-25 13:32 UTC, chws0508 requested changes
고생하셨습니다!!!! 사소한거 남겼는데 내일 같이 간단하게 고치고 머지하시죠

2023-09-25 13:32 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/mapper/EventDetailMapper.kt
>  }
EventDetailResponse에서 enum 형식으로 받도록 수정 해야 할 것 같네요!!

2023-09-26 07:16 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/competitionList/uiState/CompetitionUiState.kt
>  ) {
혹시 `CompetitionUiState` 클래스를 따로 만드신 이유가 있나요? `Competition`을 바로 사용해도 괜찮지 않을까요? UiState에서 데이터 모델을 곧바로 사용하는 것을 따로 리팩토링하실 계획이라면 일단은 넘어가도 좋을 것 같습니다 :)

2023-09-26 07:16 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/conferenceList/uiState/ConferenceUiState.kt
>  ) {
위와 동일한 리뷰입니다. :)

2023-09-26 07:17 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/fragment_event_recruitment.xml
> +
그냥 `ScrollView`를 사용하면 어떻게 되나요?

2023-09-26 07:17 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/fragment_post_list.xml
> +        </androidx.core.widget.NestedScrollView>
위와 같습니다 :)

2023-09-26 07:17 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_competition.xml
> +            app:eventStatus="@{event.competition.eventStatus}"
`textColor` 속성이 `eventStatus` 값에 의해 결정되니까 `textColor` 속성도 바인딩 어댑터를 사용하여 결정되도록 하면 어떨까요?

2023-09-26 07:17 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_conference.xml
> +            app:eventStatus="@{event.conference.eventStatus}"
위와 동일합니다 :)

2023-09-26 07:17 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_conference.xml
> +            android:text="@{event.conference.paymentType == PaymentType.PAID ? @string/all_paid : event.conference.paymentType == PaymentType.FREE ? @string/all_free : @string/all_paid_free}"
```suggestion
            app:paymentType="@{event.conference.paymentType}"
```
어떠신가요?

2023-09-26 07:17 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_conference.xml
> +            android:text="@{event.conference.onOfflineMode == OnOfflineMode.ONLINE ? @string/all_online : @string/all_offline}"
```suggestion
            app:onOfflineMode="@{event.conference.onOfflineMode}"
```
어떠신가요?

2023-09-26 07:28 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/uiState/EventDetailUiState.kt
> +package com.emmsale.presentation.ui.eventDetail.uistate
왜 uistate로 바뀌었을까요?

2023-09-26 08:27 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/TextViewBindingAdapter.kt
> +    if (eventStats == null) return
좋습니다!
실수로 eventRemainingDays를 입력하지 않는 가능성을 아예 배제할 수 있겠네요.
아래와 같이 변경하였습니다.
```kotlin
sealed class EventStatus {
    object IN_PROGRESS : EventStatus()
    data class UPCOMING(val remainingDays: Int) : EventStatus()
    object ENDED : EventStatus()
}
```

2023-09-26 08:54 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NoContentView.kt
> +}
context, attrs에 대한 생성자는 없기 때문에 앱이 터집니다.
제시해주신 코드의 일부는 반영하였습니다 : )

2023-09-26 08:56 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/competitionList/uiState/CompetitionUiState.kt
>  ) {
이 부분은 나중에 한 번에 리팩터링하기 위해 남겨놓았습니다.

2023-09-26 08:56 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/conferenceList/uiState/ConferenceUiState.kt
>  ) {
동일한 답변입니다.

2023-09-26 08:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/fragment_event_recruitment.xml
> +
해당 Fragment를 사용하는 곳에서 이미 스크롤 기능을 구현하고 있기 때문에 NestedScrollView로 하지 않으면 정상 스크롤되지 않습니다.

2023-09-26 09:07 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_competition.xml
> +            app:eventStatus="@{event.competition.eventStatus}"
아래와 같이 간결하게 변경하였고, UI 로직 변경시 한 코드만 변경될 수 있도록 바꾸어주었습니다.
`app:eventTextColor="@{event.competition.eventStatus}"`

2023-09-26 09:09 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_conference.xml
> +            android:text="@{event.conference.paymentType == PaymentType.PAID ? @string/all_paid : event.conference.paymentType == PaymentType.FREE ? @string/all_free : @string/all_paid_free}"
이 부분은 깜빡하고 적용하지 않았었네요!
캐치해주셔서 감사합니다 👍

2023-09-26 09:10 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/uiState/EventDetailUiState.kt
> +package com.emmsale.presentation.ui.eventDetail.uistate
저도 몰라요... 왜 계속 바뀌죠 ㅋ큐ㅠ

2023-09-26 09:11 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/uiState/EventDetailUiState.kt
> +package com.emmsale.presentation.ui.eventDetail.uistate
내일 전체 코드 리팩터링에서 한 번에 통일시키죠!

2023-09-26 09:26 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/fragment_event_recruitment.xml
> +
그렇군요!

2023-09-26 09:27 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_competition.xml
> +            app:eventStatus="@{event.competition.eventStatus}"
`eventStatus` 속성에서 색상까지 설정하도록 변경했습니다 :)

2023-09-26 09:28 UTC, ki960213 approved these changes
더 이상 리뷰할 게 없네요 👍

2023-09-26 09:30 UTC, merged