Feature/#665 사용자 프로필 이미지 업데이트
woowacourse-teams/2023-emmsale pull request #679
Opened 2023-10-02 12:40 UTC by hong-sile

## #️⃣연관된 이슈
- #665 

## 📝작업 내용
- 사용자 프로필 이미지 업데이트 하는 기능 구현

## 예상 소요 시간 및 실제 소요 시간
- 2시간 / 5시간

## 💬리뷰 요구사항(선택)
- S3Clinet의 bucket관련해서 테스트 짜는 부분이 좀 힘들었어요. 구현은 했는데, 해당 방법에 대해서 괜찮은지 한 번 봐주시면 좋을 것 같아요.

2023-10-03 07:35 UTC, amaran-th requested changes
수고하셨습니다~! 몇 가지 코멘트 남겨두었으니 확인 부탁드려요~!

2023-10-03 07:35 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/image/application/S3Client.java
> +//얘 @Component로 바꾸는 거 어떤가요? @Service보단 @Component가 더 적절한 것 같아요.
오 듣고 보니 Component가 더 적절할 것 같네요!
찬성합니다~~

2023-10-03 07:35 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/member/application/MemberUpdateService.java
> +      s3Client.deleteImages(List.of(imageName));
이 로직과 밑의 이미지를 업로드하는 로직들을 ImageService의 메서드로 구현해도 좋을 것 같아요!

2023-10-03 07:45 UTC, hyeonjerry approved these changes
기존 이미지 삭제까지 깔끔하게 잘 구현해주셨네요.
수고하셨습니다~!

2023-10-03 07:45 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/image/application/S3Client.java
> +//얘 @Component로 바꾸는 거 어떤가요? @Service보단 @Component가 더 적절한 것 같아요.
찬성합니다.

2023-10-04 09:43 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/member/application/MemberUpdateService.java
> +      s3Client.deleteImages(List.of(imageName));
이 부분도 조금 고민중이긴 합니다. 

ImageService의 범위를 어떻게 정할 지에 따라 다를 것 같아요.

현재 해당 로직에서, 별도의 Image테이블에 대한 접근은 없고, 단순히 S3에 이미지 추가 삭제만 하고 있어서,
ImageService가 아닌 S3를 직접적으로 의존하게 했어요.

ImageService는 뭔가 Image 테이블에 연관된 작업을 할 것 같아서요.

2023-10-05 08:10 UTC, java-saeng requested changes
고생하셨습니다.

궁금한 점들이 좀 있어서 RC 남깁니다요

2023-10-05 08:10 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/member/application/MemberUpdateService.java
> +      s3Client.deleteImages(List.of(imageName));
저도 동의합니다

근데 만약에 ImageService를 사용하지 않는다면 member의 이미지는 Image Table에서 관리하지 않고 자체 URL을 칼럼으로 저장하고 있는 건가요?

2023-10-05 08:19 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
> +    return !imageUrl.contains(GITHUB_PROFILE_DOMAIN);
그게 조금 더 정확하겠네요. 변경해보겠습니다.

2023-10-05 08:26 UTC, java-saeng commented on backend/emm-sale/src/main/java/com/emmsale/member/application/MemberUpdateService.java
> +      s3Client.deleteImages(List.of(imageName));
괜찮네여 이대로 진행하시죠

2023-10-05 08:27 UTC, java-saeng approved these changes

2023-10-05 08:36 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/member/application/MemberUpdateService.java
> +      s3Client.deleteImages(List.of(imageName));
말씀을 듣고 보니 구현하신 내용이 납득이 되네요!
지금 방식으로 가도 괜찮을 것 같아요.

2023-10-05 08:36 UTC, amaran-th approved these changes

2023-10-06 04:45 UTC, merged