Feature/#324 행사 검색 기능 구현
woowacourse-teams/2023-emmsale pull request #686
Opened 2023-10-05 09:13 UTC by amaran-th

## #️⃣연관된 이슈
#324

## 📝작업 내용
행사 이름을 키워드로 검색하는 기능을 구현하였습니다.

## 예상 소요 시간 및 실제 소요 시간
예상 - 10/5
실제 - 10/5

2023-10-05 10:12 UTC, hyeonjerry requested changes
수고하셨습니다!
궁금한 점이 있어서 코멘트 남겼어요.
확인 부탁드립니다 :)

2023-10-05 10:12 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
> +      @RequestParam(required = false) final String keyword) {
나중에 필터링 관련 파라미터끼리 하나의 DTO로 묶어도 좋을 것 같네요.

2023-10-05 10:12 UTC, hyeonjerry commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +    return keyword != null && !keyword.trim().isEmpty();
`keyword.isBlank()`로 표현할 수 있지 않을까요?

2023-10-05 10:12 UTC, hyeonjerry commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +      void findEvents_empty_events_search(final String keyword) {
혹시 이 테스트는 어떤 의도로 작성하신건가요?

2023-10-06 00:41 UTC, java-saeng approved these changes
꼼꼼한 테스트 잘 봤습니다 !

딱히 수정할 부분이 없어보입니다 고생하셨습니다

2023-10-06 00:57 UTC, hong-sile approved these changes
전반적으로 Specifiaction을 사용하는 방법이 유사해서, 읽기가 어렵진 않았네요.
잘 봤습니다.

의견 하나 남겨뒀는데 확인 부탁드려요. 어떻게 뺄지도 한번 고민해보면 좋을 것 같네요.
크게 수정할 부분은 없어서 approve 하겠습니다.

2023-10-06 00:57 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
>      Specification<Event> spec = Specification.where(filterByCategory(category));
Specification을 잘 활용해주신 것 같아요. 

specification을 활용하는 코드가 많은데 별도의 클래스로 분리해보는 건 어떨까요?
(이건 단순 의견입니다. 반영 안 해주셔도 괜찮을 것 같아요)

2023-10-07 08:53 UTC, amaran-th commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +      void findEvents_empty_events_search(final String keyword) {
예전에 행사 목록 조회 API를 호출할 때 DB에 Event가 비어있을 경우 예상치 못하게 버그가 발생하는 문제가 있었습니다.
그래서 그 때 event 테이블이 비어있는 경우에 대해서도 테스트를 작성했었고 이번에 새로운 로직을 추가하면서 같은 종류의 테스트를 작성해준 것입니다!
하지만 다시 생각해보니 지금은 필터링 로직들이 모두 동적 쿼리를 사용하는 것으로 수정되어서, 필터링 요소별로 행사 목록이 비어있는 케이스를 검증하지 않아도 될 것 같네요.

빈 목록을 반환하는 테스트 케이스 하나를 제외하고는 모두 불필요한 것 같아 삭제해주었습니다!

2023-10-07 09:11 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
> +      @RequestParam(required = false) final String keyword) {
말씀을 듣고 고민해봤는데 DTO 객체로 매핑시켰을 때 required=false 설정을 어떻게 적용시킬 수 있을지 방법이 떠오르지 않아서, 추후 EventService 리팩토일 작업을 할 때 고민해봐야할 것 같아요.
좋은 의견 감사합니다~!

2023-10-07 09:12 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
> +    return keyword != null && !keyword.trim().isEmpty();
반영했습니다!

2023-10-07 09:12 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
>      Specification<Event> spec = Specification.where(filterByCategory(category));
추후 EventService를 리팩토링할 때 고민해보면 좋을 것 같네요!
querydsl로 변경해주어야하기도 하구요

2023-10-08 04:58 UTC, hyeonjerry approved these changes
깔끔하게 반영해 주셨네요!!
수고하셨습니다~!

2023-10-09 10:14 UTC, merged