Feature/#673 행사 상태 문자열 변경
woowacourse-teams/2023-emmsale pull request #695
Opened 2023-10-09 11:04 UTC by ki960213

## #️⃣연관된 이슈
>  #673

## 📝작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

신청 상태와 진행 상태에 맞는 문자열을 보여주도록 변경

### 스크린샷 (선택)
<img width="285" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/784e63ad-2033-4f9f-be0b-06f2f9df079e">

## 예상 소요 시간 및 실제 소요 시간
> 이슈의 예상 소요 시간과 실제 소요된 시간을 분 or 시간 or 일 단위로 작성해주세요.
> 
> ex) 예상시간/걸린시간 => 2시간/3시간
2시간/2시간

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2023-10-09 11:46 UTC, chws0508 requested changes
마스형님 정말 고생 많으셨습니다.
오타 하나 발견해서 리뷰 남겼습니다.
`신청 마감 | 종료` -> `종료된 행사`로 고치면 바로 머지해도 될 것 같습니다.

2023-10-09 11:46 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/TextViewBindingAdapter.kt
> +    when (applicationStatue) {
Statue -> Status 로 바꿔야 할 것 같아요. 오타가 난 듯 합니다!

2023-10-09 13:34 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/apiModel/response/EventResponse.kt
> +    @SerialName("applyEndDate")
아래 applyStartDate처럼 startDate도 명확히 명명해주어야 나중에 봤을 때 헷갈리지 않을 것 같아요!

2023-10-09 14:02 UTC, tmdgh1592 requested changes
기능 구현하시느라 고생 많았습니다 토마스 🍅
몇 가지 코멘트를 남겨놓았으니 확인 부탁드립니다 : )

2023-10-10 03:15 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/apiModel/response/EventResponse.kt
> +    @SerialName("applyEndDate")
api 명세는 저렇게 나와있지만, Event 객체의 속성명에 event가 중복으로 들어갈 필요가 있을까요?

2023-10-10 03:16 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/apiModel/response/ScrappedEventResponse.kt
>      val endDate: String, // format : "2023:09:03:12:00:00",
api 명세는 저렇게 나와있지만, Event 객체의 속성명에 event가 중복으로 들어갈 필요가 있을까요?

2023-10-10 03:18 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/model/Competition.kt
> +        get() = EventApplicationStatus.create(applicationStartDate, applicationEndDate)
저 `create` 메서드 내부에는 현재 시각을 기준으로 d-day를 계산하기 때문에 `Competition` 객체 생성 시각이 아니라 `progressStatus` 조회 시각을 기준으로 d-day를 보여주도록 `get()`을 사용했습니다!

2023-10-10 03:21 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/model/Competition.kt
> +    val applicationEndDate: LocalDateTime,
아래처럼 `applyingStartDate`가 더 나아보이네요 😄

2023-10-10 03:23 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/model/EventApplicationStatus.kt
> +sealed interface EventApplicationStatus {
구현이 있으면 `sealed class`, 그렇지 않다면 `sealed interface`를 사용합니다. `interface`와 `abstract class` 사용 기준과 동일합니다 :)

2023-10-10 03:29 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/model/EventApplicationStatus.kt
> +    data class InProgress(val remainingDays: Int) : EventApplicationStatus
확실히 예정 상태엔 `remainingDays`가 무슨 뜻일지 예상 되는데, `InProgress`의 `remainingDays`는 무슨 뜻인지 직관적으로 떠오르지 않을 수 있을 것 같네요. `daysUntilStart`, `daysUntilDeadline` 이러한 네이밍은 어떠신가요? 행사 신청 상태 타입의 속성이므로 이것 또한 신청이란 말은 불필요하다고 생각합니다!

2023-10-10 03:30 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/model/EventDetail.kt
> +        get() = EventApplicationStatus.create(applicationStartDate, applicationEndDate)
저 create 메서드 내부에는 현재 시각을 기준으로 d-day를 계산하기 때문에 Competition 객체 생성 시각이 아니라 progressStatus 조회 시각을 기준으로 d-day를 보여주도록 get()을 사용했습니다!

2023-10-10 03:30 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/TextViewBindingAdapter.kt
> +            text = "신청 마감"
깜빡했네요 😓

2023-10-10 04:00 UTC, chws0508 approved these changes

2023-10-10 04:03 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/apiModel/response/EventResponse.kt
> +    @SerialName("applyEndDate")
start, end가 각각 1개라면 괜찮겠지만 2개 이상이라면 필요하다고 생각합니다.

2023-10-10 04:10 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/apiModel/response/EventResponse.kt
> +    @SerialName("applyEndDate")
행사의 시작 날짜, 행사의 신청 시작 날짜
위 두 문자열이 있을 때 두 문자열의 의미를 헷갈리는 경우가 있을까요?
두 문자열이 헷갈리지 않도록 하기 위해
행사의 행사 시작 날짜, 행사의 신청 시작 날짜
이렇게 바꾸는 게 더 나을까요 ❓

2023-10-10 04:23 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/apiModel/response/EventResponse.kt
> +    @SerialName("applyEndDate")
서버에서도 `eventEndDate` 라고 네이밍을 한 것처럼, 명확하게 작성해서 안 좋을 것은 없다고 생각합니다.
applyStartDate는 apply를 붙였지만 행사 시작은 단순히 startDate로 작성한다면,
누군가는 이 프로퍼티는 어떤 것의 시작/종료일인지 한 번 더 생각하고, 혹시 모를 상황에 대비하여 동료들에게 물어봐야 할 수도 있을 것 같네요~

2023-10-10 04:26 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/model/Competition.kt
> +        get() = EventApplicationStatus.create(applicationStartDate, applicationEndDate)
매번 호출마다 달라질 수 있는 프로퍼티였군요!

2023-10-10 04:30 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/model/EventApplicationStatus.kt
> +    data class InProgress(val remainingDays: Int) : EventApplicationStatus
> 행사 신청 상태 타입의 속성이므로 이것 또한 신청이란 말은 불필요하다고 생각합니다!
-> 좋습니다.

daysUntilStart는 행사/신청 중에 어떤 것이 신청해야 하는지 한 번 더 생각해봐야 할 것 같은데,
무엇이 시작하는지 명확히 알 수 있도록 `daysUntilEventStart` 는 어떤가요?

2023-10-10 04:33 UTC, tmdgh1592 commented
남겨주신 코멘트에 대해 답글을 남겼습니다.
크게 변경될 부분은 없어서 approve 하겠습니다.
남은 코드는 토마스의 의견을 따를게요 👍

2023-10-10 04:33 UTC, tmdgh1592 approved these changes

2023-10-10 04:53 UTC, merged