Feature/#700 사용자 프로필 사진 변경 기능
woowacourse-teams/2023-emmsale pull request #711
Opened 2023-10-11 13:50 UTC by chws0508

## #️⃣연관된 이슈
>  #700 

## 📝작업 내용
> 프로필 사진이 변경 가능하도록 수정하였습니다.

## 예상 소요 시간 및 실제 소요 시간
1시간/ 3시간

2023-10-12 03:57 UTC, tmdgh1592 requested changes
@chws0508
프로필 변경 기능 구현하시느라 고생하셨습니다!
코드를 조금 더 개선할 수 있을만한 몇 가지 피드백을 남겼으니 확인부탁드립니다!

2023-10-12 03:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/uiState/EditMyProfileUiState.kt
>          val FIRST_LOADING = EditMyProfileUiState(
외부에서 사용되지 않는 객체는 private을 지정해주세요!

2023-10-12 03:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/EditMyProfileViewModel.kt
> +                return@launch
로그인 여부는 Event로 만드는 것은 어떻게 생각하시나요?
화면에 고정적으로 보여줘야 하는 상태는 아닌 것 같다는 생각이예요.

2023-10-12 03:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/EditMyProfileViewModel.kt
> +        }
Success는 한 줄 작성이 가능하네요 : )
```
is Success -> _profile.value = profile.value.updateProfileImageUrl(result.data)
is Failure, NetworkError ->
    _errorEvents.value = EditMyProfileErrorEvent.PROFILE_IMAGE_UPDATE

is Unexpected -> throw Throwable(result.error)
```

2023-10-12 03:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/EditMyProfileActivity.kt
> +                    underTiramisuAlbumLauncher.launch(intent)
아래와 같이도 작성이 가능합니다.
`action = Intent.ACTION_PICK` 을 검색하여 프로젝트의 코드를 아래처럼 바꾸어주세요!

```kotlin
val intent = Intent(Intent.ACTION_PICK).apply {
    type = "image/*"
    putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true)
}
```

2023-10-12 03:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/EditMyProfileActivity.kt
> +                        arrayOf(android.Manifest.permission.READ_EXTERNAL_STORAGE),
`READ_EXTERNAL_STORAGE` 을 import하면 아래와 같이도 코드를 작성할 수 있겠네요!

```kotlin
when {
    isImageAccessPermissionGranted() -> {
        val intent = Intent(Intent.ACTION_PICK).apply {
            type = "image/*"
            putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true)
        }
        underTiramisuAlbumLauncher.launch(intent)
    }

    shouldShowRequestPermissionRationale(READ_EXTERNAL_STORAGE) -> {
        requestPermissions(arrayOf(READ_EXTERNAL_STORAGE), REQUEST_STORAGE)
    }

    else -> requestPermissions(arrayOf(READ_EXTERNAL_STORAGE), REQUEST_STORAGE)
            }
```

2023-10-12 03:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/EditMyProfileActivity.kt
> +                        arrayOf(android.Manifest.permission.READ_EXTERNAL_STORAGE),
API 30 이상부터는 두 번 이상 거절하면 영구 거절로 인식합니다.
따라서 사용자가 두 번 이상 거절한 경우에 requestPermissions() 메서드가 호출되지 않아요!
만약 권한이 허용되지 않았다면, 다이얼로그를 보여주고 바로 권한 설정 화면으로 이동하게끔 로직을 변경하는 것도 좋겠네요! **(ContextExt.kt, SettingFragment 참고)**

또한 API 30 이상은 PhotoPicker를 사용하기 때문에 해당 권한이 필요없음에도 호출되고 있습니다.

2023-10-12 03:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/EditMyProfileActivity.kt
> +        private const val TIRAMISU_VERSION = 33
별도의 상수화 없이도 Build.VERSION_CODES에서 접근이 가능합니다.
```kotlin
Build.VERSION_CODES.TIRAMISU
```

2023-10-12 04:41 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultMemberRepository.kt
> +        val requestFile = file.asRequestBody("image/jpeg".toMediaTypeOrNull())
백엔드 분들께서 jepg 또는 Png 파일로 달라고 하셔서, jepg 로 제한했었는데, 그럴 필요 없어보이네요. * 로 처리했습니다

2023-10-12 04:43 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/uiState/EditMyProfileUiState.kt
> +    )
토마스가 작성한 다른 모든 함수들이 저렇게 되있어서... 나중에 리팩할 때 한번에 고쳐야 할 것 같네요.

2023-10-12 04:51 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/EditMyProfileActivity.kt
> +    ) { uri ->
SdkExtenstion 은 실험해본 결과 제가 직접 지정해줄 수 없는 것 같아요. 앱이 설치된 기기의 따라 설정되는 것 같습니다.

2023-10-12 05:01 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/EditMyProfileViewModel.kt
> +                return@launch
이것도 이렇게 작성된 코드가 상당히 많습니다. 나중에 리팩할 때 한번에 고쳐야 할 것 같아요

2023-10-12 08:57 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/editMyProfile/EditMyProfileActivity.kt
> +                        arrayOf(android.Manifest.permission.READ_EXTERNAL_STORAGE),
PhotoPicker 에 더이상 시간을 쓸 수 없어서 일단은 13버젼 이상만 사용 가능하게 해놓았습니다... 나중에 시간 되면 알아봐요

2023-10-12 08:59 UTC, chws0508 commented
사실 더이상 이 코드에 집중할 수 없을 것 같아요... 버젼 대응에 시간을 너무 많이 썻고, 나중에 리팩 시간에 리팩에 더 쏟아야 할 것 같습니다. ㅠㅠ

2023-10-12 13:43 UTC, tmdgh1592 approved these changes
리팩때 조금 더 코드를 깔끔하게 변경해보면 좋을 것 같습니다.
이만 approve 하겠습니다.

2023-10-13 00:53 UTC, ki960213 approved these changes
리뷰할 게 없네요 👍

2023-10-13 00:55 UTC, merged