Feature/#768 소프트 키보드가 보여지면 채팅창 화면이 올라가는 기능
woowacourse-teams/2023-emmsale pull request #772
Opened 2023-10-22 08:29 UTC by tmdgh1592

## #️⃣ 연관된 이슈
> close : #768

## 📝 작업 내용
- 채팅창 화면에 진입했을 때 키보드가 올라가면, 채팅 화면도 위로 올라가는 기능을 추가했습니다.
- 상태바가 투명이라, 상태바 위치에도 채팅 내용이 보이는 문제를 해결했습니다.

### 스크린샷 (선택)
- 상태바에 색상을 입혀 상태바까지 채팅이 보이지 않습니다.

<img width="414" alt="스크린샷 2023-10-22 오후 5 28 25" src="https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/330deca9-6bdc-4ac7-985a-96b656e85812">

- **키보드가 보이면 채팅 화면도 올라가서 하단 채팅을 가리지 않습니다.**

<img width="409" alt="스크린샷 2023-10-22 오후 5 28 44" src="https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/fb616a48-e77f-4204-8d4c-7b80b9bf3e75">

## 예상 소요 시간 및 실제 소요 시간 (일 / 시간 / 분)
예상 소요 시간 : 1시간
실제 소요 시간 : 30분

## 💬 리뷰어 요구사항 (선택)

2023-10-22 13:51 UTC, chws0508 requested changes
고생하셨습니다! 혹시 카톡창은 키보드가 올라가도, Toolbar 는 고정이 되더라구요. 이렇게 구현은 힘들까요???

2023-10-23 04:41 UTC, ki960213 approved these changes
코드가 변한 게 거의 없네요 :)
댓글 작성창과 약간 다른 점은 제가 고치겠습니다 👍 
![image](https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/dd3a55bb-ed20-480e-9280-dd2b6958bd12)
![image](https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/1b134770-498f-40cd-ab42-6a584de1ae4d)

2023-10-24 01:39 UTC, tmdgh1592 commented
> 고생하셨습니다! 혹시 카톡창은 키보드가 올라가도, Toolbar 는 고정이 되더라구요. 이렇게 구현은 힘들까요???

가능합니다. 반영하겠습니다~

2023-10-24 01:40 UTC, tmdgh1592 commented
> 코드가 변한 게 거의 없네요 :) 댓글 작성창과 약간 다른 점은 제가 고치겠습니다 👍

스캇 리뷰를 반영하면서 함께 해결하겠습니다~

2023-10-24 01:58 UTC, tmdgh1592 commented
@chws0508 @ki960213 
말씀해주신 사항을 반영해서 구현했습니다.
크게 달라진 부분은 없습니다.
`stackFromEnd` 속성을 사용해서 채팅이 하단부터 쌓이도록 하였습니다.

2023-10-24 01:58 UTC, tmdgh1592 reviewed
@chws0508 @ki960213
말씀해주신 사항을 반영해서 구현했습니다.
크게 달라진 부분은 없습니다.
stackFromEnd 속성을 사용해서 채팅이 하단부터 쌓이도록 하였습니다.

2023-10-24 02:46 UTC, chws0508 approved these changes
고생하셨슴다!!!

2023-10-24 07:28 UTC, merged