Feature/#771 채팅창 키보드 바깥 영역을 클릭하면 키보드가 닫히는 기능
woowacourse-teams/2023-emmsale pull request #773
Opened 2023-10-22 09:10 UTC by tmdgh1592

## #️⃣ 연관된 이슈
> close : #771

## 📝 작업 내용
채팅창 키보드 바깥 영역을 클릭하면 키보드가 닫히도록 구현하였습니다.
현재 RecyclerView의 Item들이 클릭 이벤트를 처리하고 있어서, ViewHolder마다 클릭 이벤트시 어떤 로직을 처리할 것인지 콜백을 전달하도록 하였습니다.

### 스크린샷 (선택)
<img width='40%' src='https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/b5944551-a414-426e-a174-444eb0b442c6'>

## 예상 소요 시간 및 실제 소요 시간 (일 / 시간 / 분)
예상 소요 시간 : 30분
실제 소요 시간 : 30분

## 💬 리뷰어 요구사항 (선택)

2023-10-22 14:30 UTC, chws0508 requested changes
override fun dispatchTouchEvent(ev: MotionEvent?): Boolean {
        hideKeyboard()
        return false
    }
이렇게 하는것은 어떨까요?? 제임스가 헀던 수업이 생각났네요.

2023-10-23 04:53 UTC, ki960213 approved these changes
사실 메세지 뷰를 클릭했을 때 채팅창이 닫히는 게 아니라
<img width="290" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/c18561f7-e8fa-4acf-98f6-1bf1c409366f">


이 부분을 클릭했을 때 채팅창이 닫혀야 할 것 같아요

2023-10-24 02:00 UTC, tmdgh1592 commented
> 사실 메세지 뷰를 클릭했을 때 채팅창이 닫히는 게 아니라 이 부분을 클릭했을 때 채팅창이 닫혀야 할 것 같아요

메시지뷰 뿐만 아니라 채팅 화면에도 ClickListener를 걸어두었기 때문에 말씀하신 내용은 이미 적용되어 있는 상황입니다~

2023-10-24 02:21 UTC, tmdgh1592 commented
> 이렇게 하는것은 어떨까요?? 제임스가 헀던 수업이 생각났네요.

오 좋네요! 이 방법이 있었네요~
다만, 해당 코드는 touchdown과 touchup으로 인해 두 번 호출 되기 때문에 조건문을 걸어서 한 번만 키보드가 닫히도록 하였습니다.

2023-10-24 02:21 UTC, tmdgh1592 reviewed
@chws0508 @ki960213 
두 분 리뷰 모두 확인 완료하였습니다~
확실히 반영하고 나니, 기존에 걱정했던 보일러 플레이트 문제를 해결할 수 있었습니다. 👍

2023-10-24 02:23 UTC, chws0508 approved these changes
고생하셨슴다!!!

2023-10-24 05:05 UTC, ki960213 reviewed
`dispatchTouchEvent()` 메서드는 하위 뷰에 터치 이벤트를 전달할 지 말 지 결정하는 로직을 재정의할 때 override 하는 걸로 알고 있습니다.
터치 이벤트를 처리하는 로직은 `dispatchTouchEvent()` 메서드가 아니라 `setOnTouchEventListener()` 메서드를 통해 설정하는 게 의도에 맞다고 생각합니다.
나머지는 슬랙의 말을 참고해주세요!

2023-10-24 07:19 UTC, tmdgh1592 commented
저도 dispatchTouchEvent의 의미를 알기 때문에 토마스 말에 동의합니다~
하지만 슬랙에서 말씀해주신대로 RecyclerView에 터치리스너를 걸어보니 키보드가 보이는 상태에서 채팅방 스크롤을 하면 의도치않게 키보드가 닫혀버립니다.
그래서 카카오톡 처럼 스크롤하는 경우에는 키보드가 닫히지 않도록 다시 구현하였습니다.

2023-10-24 08:55 UTC, merged