Feature/#776 행사 화면 새로고침 기능
woowacourse-teams/2023-emmsale pull request #778
Opened 2023-10-23 06:51 UTC by tmdgh1592

## #️⃣ 연관된 이슈
> close : #776 

## 📝 작업 내용

### 스크린샷 (선택)
<img width="339" alt="스크린샷 2023-10-23 오후 3 46 30" src="https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/60ea7792-ef59-42a3-a610-33e2c3bb8de3">

## 예상 소요 시간 및 실제 소요 시간 (일 / 시간 / 분)
예상 소요 시간 : 30분
실제 소요 시간 : 30분

## 💬 리뷰어 요구사항 (선택)
SwipeRefreshLayout을 통해 새로고침을 구현하였습니다.
`Conference / CompetitionViewModel` 을 확인해보니, 필터 태그를 통해 불러오는 함수와, 태그 없이 불러오는 함수가 각각 존재합니다.
별도의 이슈라고 생각해서 해당 PR에서는 작업하지 않았고, 리팩터링시 개선이 필요해보입니다.

2023-10-23 07:27 UTC, ki960213 requested changes
간단한 코멘트만 몇 개 남겼습니다 😊

2023-10-23 07:27 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/competitionList/CompetitionViewModel.kt
> +        _selectedFilter.value = CompetitionSelectedFilteringUiState()
위에 보니까 
```
private val _selectedFilter = NotNullMutableLiveData(CompetitionSelectedFilteringUiState())
```
이렇게 초기 값을 설정해주셨는데 `init` 함수에서 또 초기 값을 설정하신 이유가 궁금합니다..!

2023-10-23 07:27 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/conferenceList/ConferenceViewModel.kt
> +        _selectedFilter.value = ConferenceSelectedFilteringUiState()
위에 보니까 
```
private val _selectedFilter = NotNullMutableLiveData(ConferenceSelectedFilteringUiState())
```
이렇게 초기 값을 설정해주셨는데 `init` 함수에서 또 초기 값을 설정하신 이유가 궁금합니다..!

2023-10-23 07:27 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/fragment_competition.xml
> +            tools:background="@color/white"
이 코드의 이유가 궁금합니다..!

2023-10-23 08:07 UTC, chws0508 approved these changes
고생하셨습니다, 한가지 리뷰만 반영해주시고 머지하면 될 것 같습니다

2023-10-23 08:07 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/competitionList/CompetitionViewModel.kt
> +        _selectedFilter.value = CompetitionSelectedFilteringUiState()
저도 궁금합니다

2023-10-24 02:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/competitionList/CompetitionViewModel.kt
> +        _selectedFilter.value = CompetitionSelectedFilteringUiState()
이제 해당 코드는 없어도 되겠네요~
이전에 토마스께서 onRefresh() 함수를 구현하면서 필터까지 초기화되도록 구현해두셔서, 새로고침시 필터가 모두 사라지는 문제가 있었습니다.
그래서 이 로직을 init으로 옮겨놓았는데, 말씀해주신 것처럼 이미 LiveData에 초기값을 전달해주기 때문에 필요 없어보입니다.

2023-10-24 02:24 UTC, chws0508 approved these changes
고생하셨슴다!!

2023-10-24 02:27 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/fragment_competition.xml
> +            tools:background="@color/white"
이 코드의 어떤 것이 궁금하신걸까요?
tools를 말씀하시는 거라면 필요 없어보이네요!

2023-10-24 02:28 UTC, tmdgh1592 reviewed
@chws0508 @ki960213 
리뷰 반영 완료하였습니다.
여쭤보신 부분에 대해 리뷰 남겨놓았으니 확인부탁드립니다.

2023-10-24 03:48 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/competitionList/CompetitionViewModel.kt
> +        _selectedFilter.value = CompetitionSelectedFilteringUiState()
`onRefresh()`가 아니라 `refresh()` 함수를 말씀하시는 거겠죠?
그랬었군요 😓

2023-10-24 03:50 UTC, ki960213 approved these changes
리뷰 반영하느라 고생하셨습니다.
더 이상 리뷰할 게 없네요 👍

2023-10-24 06:21 UTC, merged