Feature/#785 채팅에 시간을 표시하는 기능
woowacourse-teams/2023-emmsale pull request #788
Opened 2023-10-24 06:19 UTC by tmdgh1592

## #️⃣ 연관된 이슈
> close : #785

## 📝 작업 내용
채팅에 시간을 표시하는 기능을 구현하였습니다.

### 스크린샷 (선택)
<img width="371" alt="스크린샷 2023-10-24 오후 3 18 23" src="https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/08fe8dc4-4b49-48fe-afe8-c54a72bbe403">

## 예상 소요 시간 및 실제 소요 시간 (일 / 시간 / 분)
예상 소요 시간 : 30분
실제 소요 시간 : 1시간

## 💬 리뷰어 요구사항 (선택)

2023-10-24 06:32 UTC, chws0508 requested changes
자잘한 질문 남겼습니다~ 확인 부탁드려요~

2023-10-24 06:32 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +        app:visible="@{!message.message.isEmpty()}">
여기 visible 을 설정한 이유가 있을까요??

2023-10-24 06:32 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +            app:layout_constraintHorizontal_bias="0"
이거 필요 한걸까요??

2023-10-24 07:07 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +            app:layout_constraintHorizontal_bias="0"
채팅을 좌측에 배치해야 하기 때문에 필요합니다!

2023-10-24 07:26 UTC, tmdgh1592 reviewed
@chws0508 
bias가 필요한 이유를 포함하여, 남겨주신 리뷰에 대해 코멘트를 남겨 놓았습니다!

+) 이거, 여기라는 표현도 좋지만 코드 리뷰할 때 정확히 어떤 것을 말씀하시는지 파악하기가 힘드네요 🥲
가능하다면 어떤 것을 질문하시는지 명확히 언급해주시거나, 코드 드래깅을 해주시면 리뷰를 이해하기 훨씬 수월할 것 같아요 👍

2023-10-24 07:26 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +            app:layout_constraintHorizontal_bias="0"
채팅을 좌측에 배치해야 하기 때문에 필요합니다!

2023-10-24 07:26 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +        app:visible="@{!message.message.isEmpty()}">
메시지가 비어있는 경우는 저희 프로젝트에서 있을 수 없는 상황입니다.
그렇기 때문에 채팅을 보여줄 필요가 없을 때 (ex.메시지가 비어있는 경우) 에는 화면을 가리도록 구현하였습니다.

다만, 다시 생각해보니 isEmpty()보다 isBlank()인 상황이 더 적합하다고 생각하여, 공백을 포함하여 빈 채팅인 경우에도 가리도록 바꾸었습니다.

2023-10-24 07:47 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +        app:visible="@{!message.message.isEmpty()}">
음... 빈 메세지를 보내는 경우가 있을까 하는 생각이 드네요. 빈 메세지를 보내지 못하도록 막지 않을까요?? 개인적으로 저는 빈 메세지가 보내지는 문제를 이 코드로 인해 발견하지 못할 수 도 있다는 생각이 들어서요.

2023-10-24 07:48 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +            app:layout_constraintHorizontal_bias="0"
죄송합니다... 한줄만 선택한줄 알았는데, 여러줄이 선택되었었네요 ㅠ

2023-10-24 07:51 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +            app:layout_constraintHorizontal_bias="0"
@tmdgh1592

2023-10-24 08:10 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +        app:visible="@{!message.message.isEmpty()}">
이전에 `함께가요` 에서 다이얼로그에 메시지를 작성하는 기능을 구현할 때 공백이 보내지는 문제가 있었습니다.
그 버그를 채팅 화면이 아닌 다이얼로그 화면에서 찾기도 하였고, 사용자가 버그 화면을 보는 것을 최소한으로 하고 싶어서 위와 같이 구현하였습니다 : )

2023-10-24 08:11 UTC, tmdgh1592 reviewed
@chws0508
남겨주신 코멘트에 제 의견을 남겨놓았습니다!
확인해주시고 스캇은 어떻게 생각하시는지 말씀해주시면 좋을 것 같아요~

2023-10-24 13:18 UTC, ki960213 requested changes
점점 더 카카오톡에 가까워지고 있네요 👍 
코멘트 남겼으니 확인해주세요

2023-10-24 13:18 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_my_message.xml
> +        app:visible="@{!message.message.isBlank()}">
비어있는 메세지가 없기 때문에 저라면 처리 하지 않아도 괜찮다고 생각하지만, 만약 비어있는 메세지를 보여주지 않을 거라면 뷰모델에서 메세지가 비어있는 것을 필터링하는 것이 더 효율적이지 않을까요? 그렇게 한다면 리사이클러 뷰에 항목이 아예 생성되지 않을 것이기 때문에 더 효율적이라고 생각합니다.

2023-10-24 13:18 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +        app:visible="@{!message.message.isBlank()}">
비어있는 메세지가 없기 때문에 저라면 처리 하지 않아도 괜찮다고 생각하지만, 만약 비어있는 메세지를 보여주지 않을 거라면 뷰모델에서 메세지가 비어있는 것을 필터링하는 것이 더 효율적이지 않을까요? 그렇게 한다면 리사이클러 뷰에 항목이 아예 생성되지 않을 것이기 때문에 더 효율적이라고 생각합니다.

2023-10-24 13:18 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +            android:layout_marginEnd="20dp"
`layout_marginEnd` 속성을 20dp로 설정하신 이유는 다른 사람의 메세지 뷰는 오른쪽에 닿지 않도록 하기 위함인가요?
`item_my_message.xml`에서는 관련 속성을 설정하지 않아서 궁금합니다.

2023-10-24 13:52 UTC, tmdgh1592 reviewed
@ki960213 
말씀해주신 것처럼 ViewModel에서 공백 메시지를 필터링하는 것이 더 적합하다고 판단하여 변경하였습니다!
확인 부탁드립니다~

2023-10-24 13:52 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +        app:visible="@{!message.message.isBlank()}">
말씀하신 것처럼 ViewModel 에서 처리하는 것이 좋겠네요!

2023-10-24 13:54 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
> +            android:layout_marginEnd="20dp"
감사합니다. 간격을 RecyclerView에서 padding으로 처리하도록 바꾸었는데, 이 부분은 제가 놓친 것 같습니다.

2023-10-25 01:59 UTC, ki960213 approved these changes
더 이상 리뷰할 게 없네요 👍 
고생하셨습니다~

2023-10-25 06:04 UTC, chws0508 approved these changes
고생하셨습니다!!!!

2023-10-25 06:04 UTC, merged