Feature/#782 프로필 사진 디자인 변경
woowacourse-teams/2023-emmsale pull request #789
Opened 2023-10-24 08:47 UTC by ki960213

## #️⃣ 연관된 이슈
> close : #781, #782 

## 📝 작업 내용

활동 라벨 오른쪽에 화살표 이미지 제거
한 줄 소개 줄 제한 제거
내 프로필 화면에서 프로필 사진 틀 디자인 변경
프로필 화면에서 프로필 사진 틀 디자인 변경
프로필 수정 화면에서 프로필 사진 틀 디자인 변경 및 사진 변경 버튼 추가

### 스크린샷 (선택)

![image](https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/555a534d-a47a-4ca5-a9a9-ad3841186b3e)

<img width="316" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/bbaaae94-82f4-47d1-b803-b3a0fce59e4c">

## 예상 소요 시간 및 실제 소요 시간 (일 / 시간 / 분)
예상 소요 시간 : 1일
실제 소요 시간 : 8시간

## 💬 리뷰어 요구사항 (선택)

2023-10-24 14:49 UTC, tmdgh1592 requested changes
@ki960213 
기능 구현하시느라 고민하신 흔적이 많이 보입니다.
몇 가지 도움이 될 수 있는 코멘트를 남겨놓았으니 확인해주세요 😃

+) CI 통과를 하지 못하고 있는 것 같아요. 확인 부탁드립니다.

2023-10-25 00:47 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/layout/fragment_my_profile.xml
>                      android:text="@{viewModel.myProfile.member.description.isBlank() ? @string/profile_no_description : viewModel.myProfile.member.description }"
인정합니다

2023-10-25 00:48 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/layout/activity_edit_my_profile.xml
> +                    android:onClick="@{() -> editProfileImage.invoke()}"
저도 사진아이콘+사진을 눌러도 수정이 가능해야 한다고 생각해요.

2023-10-25 00:50 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/layout/activity_edit_my_profile.xml
> +                    android:onClick="@{() -> editProfileImage.invoke()}"
onProfileClick 과 editProfileImage 는 취향차이 + 트레이드오프 영역이라고 생각됩니다. 사실 저는 Click했을때의 행동이 드러나는 네이밍을 더 선호합니다만, 두분의 의견에 따르겠습니다.

2023-10-25 00:56 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/drawable/img_profile_edit_button.xml
> +                android:top="7.5dp" />
피그마에 나온대로 설정했습니다.

2023-10-25 00:56 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/drawable/img_profile_image_decoration.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
피그마에서 export 했는데 파일이 깨졌습니다. 이 부분은 디자이너분께 문의했고 오늘 답변 주신다고 합니다.

2023-10-25 00:56 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/fragment_my_profile.xml
>                      android:text="@{viewModel.myProfile.member.description.isBlank() ? @string/profile_no_description : viewModel.myProfile.member.description }"
디자이너분께 문의하겠습니다.

2023-10-25 00:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/activity_edit_my_profile.xml
> +                    android:onClick="@{() -> editProfileImage.invoke()}"
피드백 중에 프로필 사진만 있으면 프로필 사진을 변경할 수 있는지 알 수 없을 수 있다는 내용이 있었습니다. 그리고 피그마에도 사진 아이콘 버튼이 있습니다.
사진 아이콘이 있어도 프로필 사진을 클릭했을 때도 사진 선택기를 여는 게 좋을까요?

이벤트 처리 함수를 매개변수로 받을 때 매개변수 명을 처리 내용에 따라 정할지 이벤트 발생 내용에 따라 정할지에 대한 논의가 필요할 것 같습니다.
처리 내용에 따라 정한다면 `showPhotoPicker()`, 이벤트 발생 내용에 따라 정한다면 `onPhotoButtonClick` 이런 식으로 정해질 것 같습니다.

2023-10-25 00:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/activity_edit_my_profile.xml
>                      tools:srcCompat="@tools:sample/avatars" />
`tools:srcCompat` 속성은 디자인 툴로 이미지 뷰를 추가할 때 자동으로 추가되는 것이라 신경쓰지 않았습니다. :)

2023-10-25 00:57 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ImageViewBindingAdapter.kt
> +        .error(defaultImage ?: AppCompatResources.getDrawable(context, R.mipmap.ic_launcher))
좋네요 👍

2023-10-25 01:18 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ImageViewBindingAdapter.kt
> +        }
`also`는 반환값이 람다 함수의 반환값이 아니라 수신 객체입니다.
`transform` 함수 선언 코드를 보면
<img width="562" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/3c1acbce-46a8-4b6d-831e-5cc5bfd6da6c">
이렇게 `@CheckResult` 주석이 달려있습니다. 반환값을 사용해야 한다는 것을 의도하는 것 같습니다.
그래서 반환값을 사용하기 위해 `let`을 사용하였습니다. 뭔가 `run`은 지금 상황에 어울리지 않아서 사용하지 않았구요.
확장함수를 선언하는 것은 좋은 것 같습니다. 👍

2023-10-25 06:03 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/activity_edit_my_profile.xml
> +                    android:onClick="@{() -> editProfileImage.invoke()}"
> 프로필 사진만 있으면 프로필 사진을 변경할 수 있는지 알 수 없을 수 있다는 내용이 있었습니다.

사진 편집 아이콘이 없기 때문에 프로필 사진 변경 가능 여부를 파악하기 힘들다는 의견이었고, 제가 남긴 리뷰는 `사진아이콘 + 사진` 을 클릭해도 편집이 가능해야 한다는 의미입니다. 다른 주제입니다~

> 이벤트 처리 함수를 매개변수로 받을 때 매개변수 명을 처리 내용에 따라 정할지 이벤트 발생 내용에 따라 정할지에 대한 논의가 필요할 것 같습니다.

리사이클러뷰의 아이템뷰를 포함하여, 지금까지 모든 뷰를 이렇게 처리해왔었기에 통일성을 위해 제안드린 리뷰였습니다.
말씀해주신 것처럼 처리 내용에 따라 정해진다면, 처리 내용에 따라 XML 상의 코드도 바뀌어야 하겠죠? 🥲

2023-10-25 06:04 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/activity_edit_my_profile.xml
>                      tools:srcCompat="@tools:sample/avatars" />
참고로 srcCompat의 등장 배경은 롤리팝 이전의 호환성을 고려하기 위해서 입니다.

2023-10-25 06:08 UTC, chws0508 approved these changes

2023-10-25 06:12 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ImageViewBindingAdapter.kt
> +        }
`transform()` 내부에 `@CheckResult`라는 애노테이션이 있었군요 🧐🧐
새로운 지식을 배워갑니다~ 👍

2023-10-25 06:13 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/activity_edit_my_profile.xml
> +                    android:onClick="@{() -> editProfileImage.invoke()}"
사실 이전에 코드 중에서 처리 내용에 따라 정해진 네이밍도 있어서 이건 한 번 통일하는 게 좋을 것 같네요.
저도 이벤트 발생 내용에 따라 정하는 게 더 나을 것 같습니다. 뷰에서 처리해야 하는 상호작용 종류를 알 수 있으니 이벤트 발생 내용에 관한 네이밍이 나아보이네요. 상호작용 종류에 따라 어떤 로직을 수행할 지는 클라이언트 쪽에서 관심을 두고 뷰 쪽은 단지 받은 함수를 설정하는 게 나을 것 같네요

2023-10-25 06:16 UTC, tmdgh1592 approved these changes
@ki960213 
기능 구현하시느라 고생하셨습니다 토마스!
몇 가지 토멘트를 남겨놓았으니 확인해주세요~

+) 디자인 관련 사항 반영해주신 후에 merge 해주시면 되겠습니다.

2023-10-25 06:16 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ImageViewBindingAdapter.kt
>      imageUrl: String?,
함수 분리 👍

2023-10-25 06:26 UTC, ki960213 commented
> @ki960213 기능 구현하시느라 고생하셨습니다 토마스! 몇 가지 토멘트를 남겨놓았으니 확인해주세요~
> 
> +) 아직도 **CI 통과를 하지 못하고** 있는 것 같아요. 확인 부탁드립니다. +) 디자인 관련 사항 반영해주신 후에 merge 해주시면 되겠습니다.

디자인 관련 사항은 디자인 나오면 다음에 반영하겠습니다.

2023-10-25 06:36 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/fragment_my_profile.xml
>                      android:text="@{viewModel.myProfile.member.description.isBlank() ? @string/profile_no_description : viewModel.myProfile.member.description }"
일단은 @color/light_gray에서 @color/gray로 바꿨습니다.

2023-10-25 06:46 UTC, merged