Feature/#795 게시글 화면과 댓글 화면 ux 개선
woowacourse-teams/2023-emmsale pull request #807
Opened 2023-10-30 07:51 UTC by ki960213

## #️⃣ 연관된 이슈
> close : #795

## 📝 작업 내용

### 각종 커스텀 뷰를 만들었습니다.
* BasicTextInputWindow (댓글 작성 입력창, 채팅 입력창)
* SubtextInputWindow (댓글 수정 입력창)
* NetworkErrorView (네트워크 에러 시)

### 리사이클러 뷰를 사용할 때 공통적으로 사용될 수 있는 ItemDecoration을 common 패키지로 옮겼습니다.
* CommonRecyclerViewDivider (리사이클러 뷰 아이템 사이에(마지막은 제외) 앱 디자인 상 공통적으로 사용되는 장식(색상은 연한 회색에 높이는 0.5dp)을 쉽게 추가할 수 있도록 하는 클래스, 아마 검색 결과 목록에 사용하면 좋을 것 같습니다.)
* IntervalDecoration (리사이클러 뷰 아이템 간격을 쉽게 추가할 수 있도록 하는 클래스)

### 댓글 관련 layout xml 파일을 하나로 합쳤습니다.
원래는 item_all_comment, item_all_child_comment, item_all_deleted_comment, item_all_deleted_child_comment를 `Space`를 사용하여 item_all_comment로 합쳤습니다. 그리고 공통적인 조건에 의해 `visibility`가 결정되는 경우 `Group`을 사용하여 한 번에 설정할 수 있도록 했는데, 이게 뷰에 직접 설정하는 게 아니라서 "어, xml 코드를 보면 visibility를 설정하지 않았는데 왜 사라진거지? 아, Group에서 설정해놨구나" 하는 경우가 생길 수 있다고 생각하는데, 혹시 `Group`을 사용하여 한 번에 설정하는 것 어떻게 생각하시나요?

### SwipeRefreshLayout의 onRefresh 바인딩 어댑터 설정 시 로딩 상태를 나타내는 애니메이션이 새로고침이 끝나면 사라지도록 하는 기능 구현
이를 위해 우리는 ViewModel에 `Job`을 반환하는 메서드를 `onRefresh`에 설정해주어야 합니다.
현재는 하위 호환성을 위해 `onRefresh1`이라는 속성명을 사용합니다.

### BaseViewModel을 만들었습니다.
사용자의 요청에 대해 응답이 오기 전까지 아무 UI 변화가 없다면 사용자는 요청이 제대로 전송되었는 지 알기 힘들 수 있습니다.
따라서 모든 요청에 대해 로딩 상태로 변하도록 바꿔야 한다고 생각합니다.
또한 모든 요청은 네트워크 실패로 인해 응답을 받을 수 없으면 사용자가 원인을 쉽게 파악하게 하기 위해 네트워크 에러 화면을 보여줘야 한다고 생각합니다.
모든 요청을 했을 때 알 수 없는 에러를 만나도 처리해주어야 합니다.
새로고침 시엔 로딩 상태로 바뀌지 않아야 합니다.
> **새로고침 시 로딩 상태로 바뀌지 않아야 하는 이유**
우리는 CUD 요청 후 화면을 갱신하기 위해 새로고침을 합니다. CUD 요청할 땐 `BaseViewModel`에서 정의한 메서드를 이용해 요청할 것이기 때문에 이미 로딩 상태로 변해있습니다. 따라서 다시 로딩 상태로 바뀌도록 하는 것은 불필요합니다.
새로고침을 사용하는 또 다른 이유는 swipe하여 refresh하거나 네트워크 에러 상태일 때 재시도 하는 것입니다. swipe하여 refresh할 땐 `SwipeRefreshLayout`이 로딩 상태를 나타내기 때문에 로딩 상태로 바꿀 필요가 없습니다. 네트워크 에러 상태일 땐 네트워크 에러 상태 뷰가 깜빡거리기 때문에 로딩 상태로 바꾸지 않는 것이 좋습니다.

위의 로직을 매 요청마다 작성하는 것은 번거롭습니다.
따라서 BaseViewModel을 이용해 위의 로직을 한 번만 작성하고 모든 요청에 대해 미리 정의된 로직을 실행할 수 있도록 했습니다.

이렇게 하면 우리는 정해진 메서드를 사용하므로 로딩, 성공, 네트워크 실패, 알 수 없는 에러를 UI에 보여주는 것을 까먹지 않을 수 있습니다.
코드도 더 간결해집니다.

아쉬운 점: 현재 `handleResponse`랑 `refresh`의 차이는 로딩 상태로 바꾸냐, 바꾸지 않냐 뿐입니다. 중복 로직을 구현했을 수 있습니다. 하지만 이것은 의미가 있다고 생각합니다. 새로고침을 `handleResponse`로 처리하다가 로딩 상태로 바꾸지 않아야 한다는 것을 까먹을 수 있기 때문입니다. 그래도 중복 코드를 제거하고 싶네요.
현재는 시험삼아 `ChildCommentViewModel`에만 적용했습니다.
이것에 대해 더 나은 의견이 있다면 알려주세요.

### 댓글 화면 UX 개선
#### 구현 기능
* 이제 대댓글 알림, 내 댓글, 대댓글 알림 목록, 게시글 화면에서 특정 댓글 클릭을 통해 대댓글 화면에 들어가면 해당 댓글이 맨 위에 오도록 스크롤 되고 배경색이 변합니다. 한 번 클릭하면 배경색이 원래대로 돌아옵니다.
* 새로운 댓글 작성 시 맨 아래로 스무스하게 스크롤 됩니다.

#### `delay()`를 사용하지 않고 어떻게 정확하게 스크롤 할 수 있는가?
`RecyclerView.AdapterDataObserver`의 `onItemRangeInserted`를 구현한 객체를 어댑터에 등록하면 리사이클러 뷰의 아이템이 갱신된 후에 `onItemRangeInserted`가 호출되기 때문에 `delay()`를 사용하지 않아도 됩니다.

디자이너님은 하이라이팅할 댓글이 중간에 오시길 바라셨지만 어렵고 임팩트가 크지 않고, 수많은 댓글 중 어떤 댓글을 통해 들어왔는지 알 수 있다는 목표를 달성했기 때문에 그냥 맨 위로 위치하도록 했습니다.

### 스크린샷 (선택)

## 예상 소요 시간 및 실제 소요 시간 (일 / 시간 / 분)
예상 소요 시간 : 1일
실제 소요 시간 : 3일

## 💬 리뷰어 요구사항 (선택)

2023-10-31 09:52 UTC, chws0508 requested changes
일단 구현하느라 정말 고생많으셨습니다.
많이 고생하셨을 것 같습니다 ㄷㄷ
제가 CustomView 관련해서는 개념이 부족해서, 직접 물어보아서 해결하였습니다.
BaseViewModel 에 관해서 저의 개인적인 생각을 남겼으니 답변 부탁드립니다.

또한 Decoration을 활용하고 있지만, 저는 그냥 ItemView에 divider를 넣고있어서 이것도 통일해야 할 것 같네요.

리뷰할 것이 너무 많아서, 일단은 리팩토링 관련이 아닌 큼지막한 부분에 대해서 리뷰 남겼습니다.

2023-10-31 11:23 UTC, ki960213 commented
> 일단 구현하느라 정말 고생많으셨습니다. 많이 고생하셨을 것 같습니다 ㄷㄷ 제가 CustomView 관련해서는 개념이 부족해서, 직접 물어보아서 해결하였습니다. BaseViewModel 에 관해서 저의 개인적인 생각을 남겼으니 답변 부탁드립니다.
> 
> 또한 Decoration을 활용하고 있지만, 저는 그냥 ItemView에 divider를 넣고있어서 이것도 통일해야 할 것 같네요.
> 
> 리뷰할 것이 너무 많아서, 일단은 리팩토링 관련이 아닌 큼지막한 부분에 대해서 리뷰 남겼습니다.

ItemView에 divider를 넣으면 요구사항을 충족하지 못한다고 생각합니다. 디자이너의 요구사항은 ItemView 사이에 divider를 넣는 것이기 때문입니다.

2023-11-01 01:13 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/base/BaseViewModel.kt
> +
스캇의 말을 듣고 보니 모든 뷰모델 함수가 같은 로딩 상태 처리와 네트워크 상태 처리 하는 것은 옳지 않다고 생각하네요. UI마다 다르게 처리해야 할 수 있으니... 그래서 BaseViewModel을 그냥 없애는 게 나을 것 같다는 생각이 드네요.

2023-11-01 01:14 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/SwipeRefreshLayoutBindingAdapter.kt
> +        }
UI를 변경하는 UI 로직이기 때문입니다.

2023-11-01 06:58 UTC, chws0508 commented
> > 일단 구현하느라 정말 고생많으셨습니다. 많이 고생하셨을 것 같습니다 ㄷㄷ 제가 CustomView 관련해서는 개념이 부족해서, 직접 물어보아서 해결하였습니다. BaseViewModel 에 관해서 저의 개인적인 생각을 남겼으니 답변 부탁드립니다.
> > 또한 Decoration을 활용하고 있지만, 저는 그냥 ItemView에 divider를 넣고있어서 이것도 통일해야 할 것 같네요.
> > 리뷰할 것이 너무 많아서, 일단은 리팩토링 관련이 아닌 큼지막한 부분에 대해서 리뷰 남겼습니다.
> 
> ItemView에 divider를 넣으면 요구사항을 충족하지 못한다고 생각합니다. 디자이너의 요구사항은 ItemView 사이에 divider를 넣는 것이기 때문입니다.

ItemView 맨 아래에 Diverder를 넣으면 해결되지않을까요?

2023-11-01 07:36 UTC, tmdgh1592 requested changes
@ki960213 
많은 작업을 해주셨네요 토마스!
그만큼 리뷰한 코드가 많은 점 양해 부탁드립니다.. 🙏
코드 개선에 도움이 될만한 리뷰와 질문을 남겼으니 확인 후 답변 부탁드려요!

2023-11-01 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/values/colors.xml
> +    <color name="comment_highlight_color">#66D9D9D9</color>
개인적으로 강조된 색상이 조금 더 연해도 좋을 것 같다는 의견입니다.

2023-11-01 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/FeedDetailActivity.kt
> +            Intent(context, FeedDetailActivity::class.java).apply {
마찬가지로 한 줄로 작성해도 괜찮을 것 같아요!
또한, apply를 사용하지 않아도 됩니다.

2023-11-01 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/ChildCommentActivity.kt
>                  putExtra(KEY_FEED_ID, feedId)
다른 리뷰와 동일하게 apply를 사용하지 않고 윗 줄로 옮겨도 될 것 같아요!

2023-11-01 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
다른 Observable 코드와 비롯하여, 아래 코드와 차이가 있나요?

```kotlin
setRefreshListener(refreshListener: OnRefreshListener) {
    binidng.onRefreshListener = refreshListener
}
```

2023-11-01 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +        LayoutNetworkErrorBinding.inflate(LayoutInflater.from(context), this, false)
반환 타입을 명시해주지 않아도 될 것 같아요!

2023-11-01 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/SubTextInputWindow.kt
> +    private val binding: LayoutSubTextInputWindowBinding by lazy {
마찬가자지로 프로퍼티 타입이 없어도 괜찮을 것 같아요!

2023-11-01 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/SubTextInputWindow.kt
> +}
기존의 `app:visible` 를 사용해보는 것은 어떤가요?

2023-11-01 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/SubTextInputWindow.kt
> +    }
위와 동일하게 Observable로 해야만 하는 이유가 있는지 궁금합니다!

2023-11-01 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/SubTextInputWindow.kt
> +        elevation = 5.dp.toFloat()
위에서 제공해드린 Float을 dp로 변환하는 코드를 사용하면 toFloat이 없어져도 괜찮겠군요!

2023-11-01 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +        .toInt().dp
dropLastWhile은 어떤 함수인지 궁금합니다!
toDimen() 함수에 대해 조금 더 자세히 설명해주실 수 있을까요?

2023-11-01 07:44 UTC, ki960213 commented
> > > 일단 구현하느라 정말 고생많으셨습니다. 많이 고생하셨을 것 같습니다 ㄷㄷ 제가 CustomView 관련해서는 개념이 부족해서, 직접 물어보아서 해결하였습니다. BaseViewModel 에 관해서 저의 개인적인 생각을 남겼으니 답변 부탁드립니다.
> > > 또한 Decoration을 활용하고 있지만, 저는 그냥 ItemView에 divider를 넣고있어서 이것도 통일해야 할 것 같네요.
> > > 리뷰할 것이 너무 많아서, 일단은 리팩토링 관련이 아닌 큼지막한 부분에 대해서 리뷰 남겼습니다.
> > 
> > 
> > ItemView에 divider를 넣으면 요구사항을 충족하지 못한다고 생각합니다. 디자이너의 요구사항은 ItemView 사이에 divider를 넣는 것이기 때문입니다.
> 
> ItemView 맨 아래에 Diverder를 넣으면 해결되지않을까요?

아래에 Divider를 넣지 않는 게 디자인의 요구사항으로 알고 있습니다.

2023-11-01 07:47 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/IntervalDecoration.kt
> +class IntervalDecoration(
훨씬 낫네요 👍

2023-11-01 07:48 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/IntervalDecoration.kt
> +    private val height: Int = 0,
실수형으로 전달받는다면 더 다양한 상황을 대처할 수 있겠군요 👍

2023-11-01 07:51 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ActivityExt.kt
> +    imm.toggleSoftInput(InputMethodManager.SHOW_FORCED, InputMethodManager.HIDE_IMPLICIT_ONLY)
```kotlin
fun EditText.showKeyboard() {
    val imm = context.getSystemService(INPUT_METHOD_SERVICE) as InputMethodManager
    if (requestFocus()) imm.showSoftInput(this, InputMethodManager.SHOW_IMPLICIT)
}
```
이렇게 선언하면 되겠군요!

2023-11-01 07:52 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_all_comment.xml
> +            name="onClick"
뷰의 전체를 클릭했을 땐 `onClick`이라는 네이밍을 일관적으로 사용하고 있습니다. 혹시 더 좋은 이름이 있을까요?

2023-11-01 07:53 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/myCommentList/recyclerView/MyCommentsAdapter.kt
> +    private val onClick: (eventId: Long, parentCommentId: Long, commentId: Long) -> Unit,
뷰의 전체를 클릭했을 땐 onClick이라는 네이밍을 일관적으로 사용하고 있습니다. 혹시 더 좋은 이름이 있을까요?

2023-11-01 07:53 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/recyclerView/viewHolder/CommentViewHolder.kt
> +    onClick: (comment: Comment) -> Unit,
뷰의 전체를 클릭했을 땐 onClick이라는 네이밍을 일관적으로 사용하고 있습니다. 혹시 더 좋은 이름이 있을까요?

2023-11-01 07:55 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/recyclerView/viewHolder/CommentViewHolder.kt
> +@SuppressLint("ClickableViewAccessibility")
실수로 지우지 않았네요 😓

2023-11-01 07:56 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/values/colors.xml
> +    <color name="transparent">#00000000</color>
안드로이드에 기본적으로 있군요 👍

2023-11-01 07:56 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/values/colors.xml
> +    <color name="comment_highlight_color">#66D9D9D9</color>
넵 반영하겠습니다.

2023-11-01 07:58 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/layout_sub_text_input_window.xml
> +            type="com.emmsale.presentation.common.views.SubTextInputWindow.OnSubmitListener" />
SAM을 사용하지 않는다면 바인딩 어댑터를 사용할 때 람다 함수를 이용해 리스너를 제공할 수 없어서 따로 만들었습니다.
<img width="337" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/641c1ba8-a787-4d43-9c15-fe8ad4f697e6">

2023-11-01 08:01 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/FeedDetailActivity.kt
> +            Intent(context, FeedDetailActivity::class.java).apply {
apply를 사용하지 않는 다는 것은 이렇게 구현하기를 의도하신 걸까요?
```kotlin
fun getIntent(
    context: Context,
    feedId: Long,
    highlightCommentId: Long = INVALID_COMMENT_ID,
): Intent {
    val intent = Intent(context, FeedDetailActivity::class.java)
    intent.putExtra(KEY_FEED_ID, feedId)
    intent.putExtra(KEY_HIGHLIGHT_COMMENT_ID, highlightCommentId)
    intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)
    return intent
}
```

2023-11-01 08:03 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/uiState/ChildCommentsUiState.kt
> +        ) = ChildCommentsUiState(
저는 생성자를 사용할 땐 반환 타입을 명시하지 않는 게 좋다고 생각합니다. 어떻게 생각하시나요?

2023-11-01 08:05 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/uiState/ChildCommentsUiState.kt
> +        comments = comments.map { if (it.comment.id == commentId) it.unhighlight() else it },
특정 commentId 를 가진 댓글만 하이라이팅 상태를 변경하는 로직입니다. commentId가 일치하지 않을 때 반대의 상태로 바꾸는 것이 이해가 잘 안되네요.

2023-11-01 08:07 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/ChildCommentViewModel.kt
> +        _comments.value = _comments.value.unhighlight(commentId)
내부에서는 백킹 프로퍼티를 사용하는 게 낫지 않을까요? `comment.value`는 외부에 제공할 목적으로 만들어진 것이기 때문에 외부에 제공하는 방법이 달라지면 내부의 코드도 변경될 가능성이 있기 때문에 백킹 프로퍼티를 사용할 땐 내부에서는 백킹 프로퍼티를 사용하는 것이 좋지 않을까요?

2023-11-01 08:11 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/ChildCommentViewModel.kt
> +    fun refresh(pendingEventOnSuccess: ChildCommentsUiEvent? = null) = super.refresh(
`SwipeRefreshLayout`의 바인딩 어댑터 때문에 해당 함수의 시그니처와 반환 타입은 변경되지 않을 것 같습니다.
xml에서는 자바의 코드를 인식하기 때문에 위의 함수는 `refresh(pendingEventOnSuccess: ChildCommentsUiEvent): Job`로 인식됩니다. 하지만 xml에서 `app:onRefresh1="@{viewModel::refresh}"`이렇게 함수 참조를 하려면 `refresh(): Job`인 함수가 필요하기 때문에 `JvmOverloads`를 사용하였습니다 :)

2023-11-01 08:11 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/ChildCommentActivity.kt
>                  putExtra(KEY_FEED_ID, feedId)
위의 리뷰에 질문 남겼습니다.

2023-11-01 08:17 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
새로고침 시 수행되는 리스너를 설정하는 바인딩 어댑터와 `NetworkdErrorView` 클래스의 setter 메서드의 이름이 같아서 프로퍼티로 값을 변경하도록 하고 `observable`을 사용하였습니다 😊 
중복되지 않은 메서드를 만들기 위해 바인딩 어댑터는 `setOnRefreshListener()`, setter 메서드는 `setRefreshListener()` 이렇게 선언하는 것도 조금 이상한 것 같아서 그렇습니다.
`observable`을 사용하는 게 가독성을 낮춘다고도 생각하지 않았습니다. 혹시 어떻게 생각하시나요?

2023-11-01 08:22 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +        LayoutNetworkErrorBinding.inflate(LayoutInflater.from(context), this, false)
저는 생성자가 아닌 함수를 사용할 땐 반환 타입을 명시하는 편입니다. 팩토리 메서드는 정확히 클래스의 타입을 반환한다고 보장할 수 없기 때문입니다. 생각해보면 프로젝트를 할 때부터 이러한 기준을 정하지 않았고 코딩을 하다보니 이러한 원칙을 지키지 않은 경우도 있는 것 같네요.
[참고자료](https://onlyfor-me-blog.tistory.com/476)

2023-11-01 08:22 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/SubTextInputWindow.kt
> +    private val binding: LayoutSubTextInputWindowBinding by lazy {
저는 생성자가 아닌 함수를 사용할 땐 반환 타입을 명시하는 편입니다. 팩토리 메서드는 정확히 클래스의 타입을 반환한다고 보장할 수 없기 때문입니다. 생각해보면 프로젝트를 할 때부터 이러한 기준을 정하지 않았고 코딩을 하다보니 이러한 원칙을 지키지 않은 경우도 있는 것 같네요.
[참고자료](https://onlyfor-me-blog.tistory.com/476)

2023-11-01 08:23 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/SubTextInputWindow.kt
> +    }
[위의 리뷰](https://github.com/woowacourse-teams/2023-emmsale/pull/807#discussion_r1378507622)에 제 의견을 남겼습니당

2023-11-01 08:27 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +        .toInt().dp
`dropLastWhile` 함수는 조건에 맞지 않는 것을 뒤에서부터 지워 나가고 남은 것을 반환하는 함수입니다.
`toDimen()` 함수는 문자열을 뷰의 특정 속성에 크기로서 할당할 수 있게 바꿔주는 함수인데요, 크기를 표현한 문자열이 특정 단위를 가지고 있다면 단위에 맞는 `Int` 타입으로 변환하고 아무 단위도 없다면 곧바로 `Int` 타입으로 변환해주는 함수입니다. :)

2023-11-01 08:38 UTC, chws0508 commented on android/2023-emmsale/app/src/main/res/layout/item_all_comment.xml
> +            name="onClick"
onCLickScreen

2023-11-01 08:39 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/recyclerView/viewHolder/CommentViewHolder.kt
> +    onClick: (comment: Comment) -> Unit,
OnCommentClick 이 나아보입니당

2023-11-01 08:40 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/FeedDetailActivity.kt
> +            Intent(context, FeedDetailActivity::class.java).apply {
저는 여태까지 apply로 써와서, apply를선호합니당

2023-11-01 08:41 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/uiState/ChildCommentsUiState.kt
> +        ) = ChildCommentsUiState(
저는 무적권 반환타입을 명시하는 편이긴 합니다 ㅎㅎ

2023-11-01 08:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
사람에 따라 다르겠지만, 저는 조금 다르게 Observable을 사용하면 자연스럽게 코드가 길어지다보니 가독성이 낮아보인다고 느꼈습니다.
Observable을 사용하지 않고 개선할 수 있는 방법이 있다면 적용해봐도 좋을 것 같습니다!

2023-11-01 08:45 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/base/BaseViewModel.kt
> +
위의 의견을 반영하여 다시 한 번 리팩토링 후 푸시하겠습니다.

2023-11-01 08:45 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +        LayoutNetworkErrorBinding.inflate(LayoutInflater.from(context), this, false)
DataBinding의 inflate() 팩터리 메서드는 클래스의 객체를 반환하는 메서드이지 않나요?

2023-11-01 08:46 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_all_comment.xml
> +            name="onClick"
스캇과 동일합니다.
또는 `onBodyClick` 도 있겠네요!

2023-11-01 08:47 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/myCommentList/recyclerView/MyCommentsAdapter.kt
> +    private val onClick: (eventId: Long, parentCommentId: Long, commentId: Long) -> Unit,
아래 스캇과 저의 리뷰를 참고해주세요 : )

2023-11-01 08:47 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
사실 저도 익숙한 코드는 부나가 제안한 코드입니다. 실제로 Delegatates.observable 을 많이 봐오지 못해서 토마스의 코드를 이해하는데에 시간이 조금 필요했습니다.

2023-11-01 08:48 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +        LayoutNetworkErrorBinding.inflate(LayoutInflater.from(context), this, false)
저는 무조건 반환타입을 명시하는 편입니다.

2023-11-01 08:48 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/recyclerView/viewHolder/CommentViewHolder.kt
> +    onClick: (comment: Comment) -> Unit,
저는 그렇다고 생각해요!

2023-11-01 08:50 UTC, chws0508 commented
> 아래에 Divider를 넣지 않는 게 디자인의 요구사항으로 알고 있습니다.

Diveder와 Decorater의 차이를 알고싶네용...

2023-11-01 08:50 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/FeedDetailActivity.kt
> +            Intent(context, FeedDetailActivity::class.java).apply {
아래 코드를 참고해주세요 : )
```kotlin
fun getIntent(
    context: Context,
    feedId: Long,
    highlightCommentId: Long = INVALID_COMMENT_ID,
): Intent = Intent(context, FeedDetailActivity::class.java)
    .putExtra(KEY_FEED_ID, feedId)
    .putExtra(KEY_HIGHLIGHT_COMMENT_ID, highlightCommentId)
    .addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)
```

2023-11-01 08:52 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/uiState/ChildCommentsUiState.kt
> +        comments = comments.map { if (it.comment.id == commentId) it.unhighlight() else it },
제가 기능과 로직을 잘못 이해했네요!
이 리뷰는 skip하셔도 좋습니다.

2023-11-01 08:56 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/uiState/ChildCommentsUiState.kt
> +        ) = ChildCommentsUiState(
통일성을 지키기 위해 남긴 리뷰였습니다.
Activity의 `Intent` 를 생성하기 위한 정적 팩터리 메서드들도 반환 타입을 명시해주고 있으니까요 : )

2023-11-01 08:57 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/ChildCommentViewModel.kt
> +        _comments.value = _comments.value.unhighlight(commentId)
충분히 일리있다고 생각합니다.
다만, 그런 상황이 흔치 않다고 생각하기도 하는 입장입니다!
외부에 제공되는 코드가 변경된다면 그 때에는 LiveData가 아닌 Flow를 사용하겠구나 라는 상황밖에 연상되지 않습니다.

2023-11-01 08:58 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/SubTextInputWindow.kt
> +    private val binding: LayoutSubTextInputWindowBinding by lazy {
위에 남긴 답글과 동일합니다.

2023-11-01 09:20 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/ChildCommentViewModel.kt
> +    fun refresh(pendingEventOnSuccess: ChildCommentsUiEvent? = null) = super.refresh(
아하! 그러면 인자가 0개 또는 1개 있는 메서드를 xml에서 사용할 수 있다는 의미인거죠?

2023-11-01 09:20 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/ChildCommentViewModel.kt
> +    fun refresh(pendingEventOnSuccess: ChildCommentsUiEvent? = null) = super.refresh(
늦게 확인했는데, 반환 타입을 명시해주면 좋을 것 같습니다.

2023-11-01 09:28 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +        .toInt().dp
설명을 듣고 다시 살펴보니 이해가 되네요.
`12dp`같은 문자열을 숫자만 남을 때까지 제거하고 dp 크기로 변환하는 기능이군요 👍
혹시 모를 상황에 대비하여 String.trim() 함수를 추가하는 것은 어떤가요?

2023-11-01 09:29 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/layout_sub_text_input_window.xml
> +            type="com.emmsale.presentation.common.views.SubTextInputWindow.OnSubmitListener" />
궁금해서 그러는데 왜 람다 함수를 전달할 수 없는 건가요?

2023-11-01 14:01 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/IntervalDecoration.kt
> +    private val height: Int = 0,
보니까 실수형으로 전달받아도 무조건 정수형으로 변환해야 하네요. 따라서 실수형으로 받을 이유가 없는 것 같습니다.
<img width="335" alt="image" src="https://github.com/woowacourse-teams/2023-emmsale/assets/123928686/4498d187-92da-431d-b7ff-246d81ee2b30">

2023-11-01 14:38 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/myCommentList/recyclerView/MyCommentsAdapter.kt
> +    private val onClick: (eventId: Long, parentCommentId: Long, commentId: Long) -> Unit,
https://github.com/woowacourse-teams/2023-emmsale/pull/807#discussion_r1378884532

2023-11-01 14:38 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/recyclerView/viewHolder/CommentViewHolder.kt
> +    onClick: (comment: Comment) -> Unit,
https://github.com/woowacourse-teams/2023-emmsale/pull/807#discussion_r1378884532

2023-11-01 14:39 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/layout_sub_text_input_window.xml
> +            type="com.emmsale.presentation.common.views.SubTextInputWindow.OnSubmitListener" />
자바에는 함수 타입이 없기 때문입니다.

2023-11-01 14:40 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/uiState/ChildCommentsUiState.kt
> +        ) = ChildCommentsUiState(
그것도 컨벤션을 맞춰야 할 것 같네요.

2023-11-01 14:46 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/FeedDetailActivity.kt
> +            Intent(context, FeedDetailActivity::class.java).apply {
`Intent` 타입을 반환하는 지 몰랐네요!

2023-11-01 14:49 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/ChildCommentViewModel.kt
> +        _comments.value = _comments.value.unhighlight(commentId)
`comments.value` 이것을 사용하는 것이 가독성이 늘어난다고 생각하지 않습니다. 따라서 단점은 있지만 장점은 보이지 않네요...

2023-11-01 14:50 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/ChildCommentViewModel.kt
> +    fun refresh(pendingEventOnSuccess: ChildCommentsUiEvent? = null) = super.refresh(
https://github.com/woowacourse-teams/2023-emmsale/pull/807#discussion_r1378561970
네 맞습니다.

2023-11-01 14:55 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
코드가 길어지는지 잘 모르겠네요. 차이점은 단지 setter 함수를 observable에 넣은 것이니까요.
observable을 처음봐서 이해하는 게 힘들 수 있지만 `Delegates`가 익숙해진다면 유용할 거라고 생각합니다.
코틀린 언어 자체에서 제공하는 api니까요..

2023-11-01 14:59 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +        LayoutNetworkErrorBinding.inflate(LayoutInflater.from(context), this, false)
`inflate`나 `bind`는 안드로이드에서 제공하는 팩토리 메서드이기 때문에 이러한 메서드는 무조건 같은 클래스를 반환한다는 것을 기억한다면 타입을 명시해줄 필요가 없긴 하네요. 그렇다면 팩토리 메서드가 무엇인지에 따라 반환 타입을 명시할지 말지 결정해야 합니다.
저는 차라리 모든 팩토리 메서드는 반환타입을 명시하는 게 좋다고 생각하는 데 어떻게 생각하시나요?
예전엔 팩토리 메서드가 자식 타입을 반환하고 팩토리 메서드 반환 타입이 부모 타입이길 바랄 때만 반환 타입을 명시했는데, 이펙티브 코틀린 책에 나온 내용을 보니 부모 타입을 반환하더라도 자식 타입을 반환하도록 변경될 수 있으므로 타입을 명시하는 게 더 나아보이네요. 어떻게 생각하시나요?

2023-11-01 15:00 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +        LayoutNetworkErrorBinding.inflate(LayoutInflater.from(context), this, false)
그러네요. `inflate` 메서드를 알고 있다면 굳이 타입을 명시할 필요가 없네요.

2023-11-01 15:02 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +        LayoutNetworkErrorBinding.inflate(LayoutInflater.from(context), this, false)
막상 타입을 지우고 보니 타입을 명시하는 게 더 타입을 파악하기 쉬워 보이네용. 어떻게 생각하시나요?

2023-11-01 15:05 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +        .toInt().dp
문자열의 양 끝에 공백이 들어가도 컴파일 에러가 나지 않게 하는 의견 좋습니다.
하지만 공백이 들어갔다는 것은 오타라고 생각합니다. 오타를 컴파일 타임에 잡는 것이 낫지 않을까요?

2023-11-01 15:06 UTC, ki960213 commented
> der와 Decorater의 차이를 알고싶

2023-11-01 15:09 UTC, ki960213 commented
> > 아래에 Divider를 넣지 않는 게 디자인의 요구사항으로 알고 있습니다.
> 
> Diveder와 Decorater의 차이를 알고싶네용...

아래에 Divider를 넣으면 리사이클러 뷰 맨 마지막 항목의 아래 부분에 선이 생깁니다. 하지만 디자인 요구사항은 아이템 사이에 선이 생기는 것입니다.

2023-11-01 15:14 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/layout_sub_text_input_window.xml
> +            type="com.emmsale.presentation.common.views.SubTextInputWindow.OnSubmitListener" />
애노테이션 프로세서에 의해 바인딩 어댑터 클래스가 생기는데 이 때 생기는 코드는 자바 언어입니다. :)

2023-11-01 15:20 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ActivityExt.kt
> +    imm.toggleSoftInput(InputMethodManager.SHOW_FORCED, InputMethodManager.HIDE_IMPLICIT_ONLY)
위의 코드대로 구현하면 소프트 키보드가 안보이네요. 그래서 Deprecated 된 api를 사용했었구요.. 깜빡했네요.
그래서 `postDelay`를 이용해 소프트 키보드를 보여주도록 했습니다.

2023-11-01 23:46 UTC, tmdgh1592 commented
> 서버에서 데이터를 불러오는 데 실패하거나 알 수 없는 에러 발생 시에도 성공 상태로 변하게 하나요?

> 네. 왜냐하면 뷰모델에서 설정하는 UI 상태는 비즈니스 로직과 상관없이 UI를 변경시키는 것이기 때문입니다. 우리는 성공 상태를 로딩 바가 보여지지 않고 네트워크 에러 화면이 보여지지 않는 상태를 FetchResult의 SUCCESS라고 정의했습니다. xml에서 데이터 바인딩을 사용해서 로딩 바와 네트워크 에러 화면의 visibility를 gone으로 설정하고 있죠. 만약 우리가 알 수 없는 에러 발생 시 알 수 없는 에러가 발생했다는 화면을 네트워크 에러 화면처럼 보여주는 것으로 디자인이 변경된다면 알 수 없는 에러 발생 시 성공 상태가 아니라 알 수 없는 에러 상태로 변경해야 합니다.

이 말은 지금은 에러가 발생해도 일단 SUCCESS로 구현할 거지만 나중에 알 수 없는 에러 화면을 보여줘야 하는 요구사항이 추가되면 그 때에는 에러 상태를 추가하겠다는 의미인가요?

사실 그냥 봤을 땐 실팬데 왜 성공으로 취급하지라는 생각밖에 들지 않습니다 😢

2023-11-01 23:49 UTC, tmdgh1592 commented
> delay()를 사용하지 않고 어떻게 정확하게 스크롤 할 수 있는가?

이보다 더 간단하게 submitList를 사용하고 콜백을 사용해볼 수도 있을 것 같습니다.

2023-11-01 23:59 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/myCommentList/recyclerView/MyCommentsAdapter.kt
> +    private val onClick: (eventId: Long, parentCommentId: Long, commentId: Long) -> Unit,
뷰 그룹안에 많은요소들이 있는게, onClick 하나만 있으묜 조금 당황할 것 같아요.

2023-11-02 00:31 UTC, tmdgh1592 requested changes
제 의견과 코멘트를 추가했습니다!
확인 부탁드립니다~

2023-11-02 00:31 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_all_comment.xml
> +            name="onClick"
무슨 말인지 잘 이해하지 못했습니다..
다시 한 번 설명해주세용

2023-11-02 00:31 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/IntervalDecoration.kt
> +    private val height: Int = 0,
RectF를 사용해주세요.

2023-11-02 00:31 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/FeedDetailActivity.kt
> +            Intent(context, FeedDetailActivity::class.java).apply {
Intent는 전반적으로 apply를 사용하지 않아도 되는 경우가 많습니다.
두 분 다 참고해주시면 도움될 것 같아요~

2023-11-02 00:31 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/layout_sub_text_input_window.xml
> +            type="com.emmsale.presentation.common.views.SubTextInputWindow.OnSubmitListener" />
자바라는 것은 알고 있지만 람다가 Function으로 변환되지는 않나요?
사실 말씀해주신 부분과 코드가 아직 잘 이해되지 않습니다.
관련해서 참고할만한 링크가 있을까요?

2023-11-02 00:31 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childCommentList/ChildCommentViewModel.kt
> +        _comments.value = _comments.value.unhighlight(commentId)
저는 크게 단점도 보이지도 않아요.
개인차인 것 같아서 resolve 하겠습니다.

2023-11-02 00:31 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
Observable은 이미 이전 미션에서도 사용해봤습니다 😅
미션에서 구현하면서 느낀 점을 말씀드린 거였어요~
그리고 말씀하신 것처럼 Observable이 생소한 팀원이 있을 수도 있다는 단점도 존재합니다.

2023-11-02 00:31 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +        .toInt().dp
심각한 오타가 아닌데 잡지 않을 이유가 있을까요?
오히려 유연한 함수가 된다고 생각해요.

2023-11-02 02:07 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_all_comment.xml
> +            name="onClick"
여러 UI를 포함하고 있는 `ViewGroup`의 `onClick` 메서드를 보면 무엇을 클릭하는 것인지 명확하게 알 수 없는지 궁금합니다.

2023-11-02 04:09 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/layout_sub_text_input_window.xml
> +            type="com.emmsale.presentation.common.views.SubTextInputWindow.OnSubmitListener" />
아 생각해보니 `Function` 타입으로 변경되긴 하는군요!
링크는 기억이 안나고 예전에 바인딩 어댑터에서 함수 타입을 매개변수로 선언할 수 없는 이유에 대해 읽었던 글을 번역해놓은 기록이 있습니다. 큰 도움이 될 진 모르겠지만 한 번 공유해 봅니다 😊 

> 실제로 데이터 바인딩 문서에서는 코틀린 람다 유형이 데이터 바인딩 리스너 또는 메서드 참조로 작동한다는 것을 언급하지 않았습니다. 아마도 이러한 람다 유형이 코틀린의 `Function1`, `Function2`로 번역되기 때문일 것입니다... 이들은 제네릭이며, 따라서 일부 타입 정보는 실행 파일에 도달하지 못하므로 런타임에 사용할 수 없습니다.

2023-11-02 04:13 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
저도 처음 프로젝트 할 때 데이터 바인딩이 생소했습니다. 제가 데이터 바인딩이 생소하단 이유로 팀원 모두 뷰 바인딩을 사용한다면 좋지 않다고 생각합니다. 이와 마찬가지로 코틀린 공식 api인 `Observable`을 사용하지 말아야 하는 이유가 팀원이 생소하게 느껴서 라는 건 조금 아쉬운 것 같네요.
즉, 단점이 생소한 팀원이 존재할 수 있다는 것 말고는 모르겠네요...

2023-11-02 04:20 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +        LayoutNetworkErrorBinding.inflate(LayoutInflater.from(context), this, false)
좋습니다. 👍

2023-11-02 04:22 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +        .toInt().dp
이 오타는 ktlint로 찾아낼 수 없고 아마 코드 리뷰 하다가 다른 사람이 불필요한 공백을 작성한 것을 발견한다면, 저는 변경 요청을 할 것 같습니다. 변경 요청 후 번거롭게 코드를 고치고 다시 푸시하는 것 보단 컴파일 에러가 발생하여 빠르게 문제를 발견할 수 있는 게 낫지 않을까요?

2023-11-02 04:28 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/IntervalDecoration.kt
> +    private val height: Int = 0,
그렇게 하려면 `getItemOffsets`가 아니라 `onDraw`를 재정의 해야 겠네요. 그런데 `getItemOffsets`가 아이템 간격을 추가하는 의도로 설계된 거라고 생각합니다. 따라서 지금은 의도대로 구현하고 만약 필요하다면 그때 `onDraw`를 재정의하는 방식으로 구현하는 게 낫지 않을까요? 근데 제 생각엔 그런 경우가 없을 것 같네요.

2023-11-02 05:03 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/EditTextExt.kt
> +    postDelayed(
찾아봤는데 포커스가 되어 있지 않아서도 아니라서 정확한 이유는 저도 잘 모르겠네요 😓

2023-11-02 05:04 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/SpaceItemDecoration.kt
> +    private val height: Int = 0,
https://github.com/woowacourse-teams/2023-emmsale/pull/807#discussion_r1379575871

2023-11-02 05:08 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/SpaceItemDecoration.kt
> +        if (position > 0) outRect.top = height
아이템 간의 간격을 설정하기 위한 용도입니다. 첫번째 아이템은 offset를 적용하지 않고 있습니다. 만약 bottom이나 right에 간격을 추가하고 싶다면 다른 클래스를 만드는 것이 나아보이네요. 그러한 목적으로 주 생성자의 인자 명이 `left`나 `top`이 아닌 `width`와 `height`입니다.
그리고 모든 상황을 고려하려고 한다면 끝이 없다고 생각합니다. 지금도 저희는 커스텀 다이얼로그를 만들었지만 다이얼로그를 설정할 수 있는 모든 방법을 노출하지 않았습니다. 필요하면 그 때 만드는 게 어떤가요?

2023-11-02 07:44 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_all_comment.xml
> +            name="onClick"
넵 한 번 더 생각해야만 하는 코드라는 생각이 드네요.

2023-11-02 07:45 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/layout_sub_text_input_window.xml
> +            type="com.emmsale.presentation.common.views.SubTextInputWindow.OnSubmitListener" />
정확히는 `Generic` 이 컴파일 타임에 소거되기 때문이겠군요 👍

2023-11-02 07:50 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
잘못 이해하신 것 같아서 부가적인 설명을 남깁니다.
데이터바인딩을 사용했을 때에는 장점이 명확하지만, Observable을 사용했을 때에는 그만한 장점이 있다고 생각하지 않기 때문이에요.
개인적인 생각이지만, 위에 남긴 코멘트처럼 가독성도 좋지 않다고 생각하구요.
팀에 Compose를 추가하고 `xml보다 좋으니 Compose를 사용해야 합니다.` 라고 말하는 것과 비슷한 맥락으로 보이네요.
새로운 기술은 무조건 배척해야 한다는 의미가 아닙니다.

2023-11-02 07:56 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +        .toInt().dp
말씀하신 것처럼 저도 오타가 있다면 코드 리뷰 과정에서 캐치해줄 것 같습니다.

다만, 토마스가 만든 코드를 라이브러리 관점에서 생각해보면 좋을 것 같아서 남긴 리뷰였습니다.
`12dp` 로 작성하나 ` 12dp` 로 작성하나 12dp라는 결괏값에는 차이가 없기 때문에, 조금 더 유연한 함수를 제공했으면 하는 마음에 남긴 의견이었습니다.
만약 `o12dp` 와 같은 오타이면 당연히 에러를 잡아야 하겠지만요 ㅋㅋ

2023-11-02 08:03 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/SpaceItemDecoration.kt
> +        if (position > 0) outRect.top = height
`Space` 는 공간을 의미하는 것이 아닌가요?
width와 height을 인자로 전달받는데 왜 left와 top에만 적용하는지는 아직도 이해하지 못하겠습니다 🧐

> 그리고 모든 상황을 고려하려고 한다면 끝이 없다고 생각합니다.

저는 `SpaceItemDecoration` 이라는 클래스를 이름에 맞게 정의하고 싶은 겁니다.
left와 top에만 적용할거라면 애초에 클래스명이 이렇게 추상적이면 안 되지 않을까요?

2023-11-02 08:08 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/IntervalDecoration.kt
> +    private val height: Int = 0,
토마스 말대로라면, 커디 프로젝트의 offset은 반드시 정수형이어야만 하겠군요.
`getItemOffsets()` 메서드가 정수만 전달받는다고 해서 프로젝트가 정수형만 써야 하는 이유는 없다고 생각합니다.

2023-11-02 08:11 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
단지 setter를 `observable`에 넣은 것인데 가독성이 감소하는 이유를 알려주세요 😢 
setter 함수는 외부에서 사용하라고 만든 메서드이지, 내부에서는 프로퍼티를 곧바로 변경할 것입니다. 만약 `NetworkErrorView` 클래스에서 외부에서 setter 함수를 이용해 프로퍼티를 변경하는 게 아니라 다른 이유로 내부에서 프로퍼티를 변경한다면 데이터 바인딩이 적용되지 않을 것입니다. 제가 선언한 프로퍼티의 목적은 프로퍼티가 뷰가 어떻게 그려지는 지 결정하는 역할인데 말이죠. 정확히 말해서 **외부에서 setter 함수를 이용해 객체의 상태를 변경할 때마다 데이터 바인딩을 적용하는 게 아니라 프로퍼티에 값이 할당될 때마다 데이터 바인딩을 적용하기 위해** `observable`을 사용하였습니다. 즉, setter 함수는 제가 의도한 기능이 아닙니다.
사실 다른 방식으로도 위의 문제를 해결할 수 있습니다.
혹시
```kotlin
    var onSubmitListener: OnSubmitListener = OnSubmitListener { }
        set(value) {
            field = value
            binding.onSubmitListener = value
        }
```
이 코드는 가독성이 어떤가요?
저는 개인적으로 값이 변경된 이후 특정 로직을 수행하기 위한 목적으로는 `observable`이 가장 어울린다고 생각해서 `observable`을 사용했습니다.

2023-11-02 08:13 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +        .toInt().dp
저는 좋지 않은 코드를 작성할 가능성을 최대한 줄이는 게 좋다고 생각해서 부나와 생각이 다르네요 😢

2023-11-02 08:16 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/SpaceItemDecoration.kt
> +        if (position > 0) outRect.top = height
부나가 생각한 것과 제가 생각한 것이 달랐네요. 부나의 말대로 아이템 사이의 Space가 아니라 아이템의 특정 위치의 Space라면 그건 ItemDecoration을 사용할 필요가 없지 않을까요? 그냥 layout 만들 때 구현할 것 같네요. 그래서 `SpaceItemDecoration` 보단 `IntervalItemDecoration`이 더 어울리는 것 같네요.

2023-11-02 08:18 UTC, tmdgh1592 requested changes
@ki960213 
제 의견과 코드 개선에 대한 리뷰를 남겼습니다.
확인 후 코멘트 부탁드려요 🙌

2023-11-02 08:18 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +private const val DIMEN_UNIT_DP = "dp"
DIMEN이라는 prefix가 필요할까요?
dp가 DIMEN에 국한된 개념이 아니기에 `DP_UNIT` 라고만 작성해줘도 충분하다고 생각합니다.

2023-11-02 08:18 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +@BindingAdapter("app:layout_marginTop")
Github에는 안 보여서 이제 확인했는데, 해당 코드 위에 `@BindingAdapter("app:layoutMarginTop")` 라는 바인딩어댑터가 정의되어 있네요.
사용하는 입장에서 `layout_marginTop` 와 `layoutMarginTop` 을 구분하기 힘들어하지 않을까요?

2023-11-02 08:18 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +private fun String.toDimen(): Int = if (endsWith(DIMEN_UNIT_DP)) {
toDimen() 보다는 Float이나 Int를 DP로 변환할 때처럼,
`String.dp` 같은 확장 프로퍼티를 사용하거나, 네이밍을 변경해보는 것은 어떤가요?

2023-11-02 08:18 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +        .toInt().dp
개인적으로 조금 읽기 어렵네요.. 🥲
아래와 같이 작성해볼 수 있을 것 같습니다.

`private fun String.toDimen(): Int = removeSuffix(".$DIMEN_UNIT_DP").toInt().dp`

2023-11-02 08:22 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/IntervalDecoration.kt
> +    private val height: Int = 0,
offset을 실수형으로 받으면 어떠한 장점이 있는지 궁금합니다. 😕

2023-11-02 08:25 UTC, ki960213 commented on android/2023-emmsale/app/src/main/res/layout/item_all_comment.xml
> +            name="onClick"
저는 `onClick`을 보면 전체를 클릭했을 때 실행되어야 할 콜백 함수로 생각이 드는데...
그렇다면 전체를 클릭했을 때 실행되어야 할 콜백 함수의 이름이 모든 뷰 홀더마다 다른 게 좋다고 생각하시나요?

2023-11-02 08:29 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +@BindingAdapter("app:layout_marginTop")
최대한 안드로이드에서 제공하는 공식 api를 따라가려고 했습니다. 
사실 위에 정의된 `@BindingAdapter("app:layoutMarginTop")`도 `@BindingAdapter("app:layout_marginTop")`으로 바꾸고 싶었는데 이거 바꾸면 다른 코드도 바꿔야 하기 때문에 일단은 변경하지 않았습니다.
사용하는 입장에서는 최대한 같은 이름이 사용되는 게 좋다고 생각합니다. 결과적으로 동일한 속성을 변경하기 위한 바인딩 어댑터들이니까요.

2023-11-02 08:30 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +        .toInt().dp
`removeSuffix`라는 api도 있었군요! 👍

2023-11-02 08:35 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +private fun String.toDimen(): Int = if (endsWith(DIMEN_UNIT_DP)) {
사실 이 코드는 xml에서 크기를 바인딩 어댑터에 넘겨줄 때 사용하기 위해 만든 함수입니다.
```kotlin
@BindingAdapter("app:layout_marginTop")
fun View.setLayoutMarginTop(margin: Int) {
    updateLayoutParams<ViewGroup.MarginLayoutParams> {
        topMargin = margin
    }
}
```
이렇게 만들까도 생각했지만 바인딩 어댑터를 사용하는 곳에서 dp인지 픽셀인지 선택할 수 없어서 문자열을 받도록 구현했습니다. 그래서 `String.dp` 확장 프로퍼티가 필요한 지 모르겠네요.

2023-11-02 10:13 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
장점
1. 바인딩 어댑터 함수명과 클래스의 setter 함수명이 겹치지 않는다.
2. 프로그래매틱 방식으로 구현하면 함수가 아니라 프로퍼티에 할당하는 방식으로 사용할 수 있다.
ex) `basicTextInputWindow.setIsSubmitEnabled(true)` -> `basicTextInputWindow.isSubmitEnabled = true`
이러한 장점이 있다고 생각합니다.

애초에 언어 자체에서 공식적으로 제공하기도 하고 코드가 크게 늘어나지 않는데 팀원이 생소할 수 있다는 게 단점이라고 말하는 게 이해가 되지 않습니다 😢 
부나가 말하는 가독성이 좋지 않은 이유는 `observable`이라는 api가 생소하기 때문이 아니라 다른 이유가 있는지 궁금합니다.

2023-11-02 11:55 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/myCommentList/recyclerView/MyCommentsAdapter.kt
> +    private val onClick: (eventId: Long, parentCommentId: Long, commentId: Long) -> Unit,
https://github.com/woowacourse-teams/2023-emmsale/pull/807#discussion_r1379742106

2023-11-02 11:55 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/recyclerView/viewHolder/CommentViewHolder.kt
> +    onClick: (comment: Comment) -> Unit,
https://github.com/woowacourse-teams/2023-emmsale/pull/807#discussion_r1379742106

2023-11-02 11:59 UTC, ki960213 commented
> > 서버에서 데이터를 불러오는 데 실패하거나 알 수 없는 에러 발생 시에도 성공 상태로 변하게 하나요?
> 
> > 네. 왜냐하면 뷰모델에서 설정하는 UI 상태는 비즈니스 로직과 상관없이 UI를 변경시키는 것이기 때문입니다. 우리는 성공 상태를 로딩 바가 보여지지 않고 네트워크 에러 화면이 보여지지 않는 상태를 FetchResult의 SUCCESS라고 정의했습니다. xml에서 데이터 바인딩을 사용해서 로딩 바와 네트워크 에러 화면의 visibility를 gone으로 설정하고 있죠. 만약 우리가 알 수 없는 에러 발생 시 알 수 없는 에러가 발생했다는 화면을 네트워크 에러 화면처럼 보여주는 것으로 디자인이 변경된다면 알 수 없는 에러 발생 시 성공 상태가 아니라 알 수 없는 에러 상태로 변경해야 합니다.
> 
> 이 말은 지금은 에러가 발생해도 일단 SUCCESS로 구현할 거지만 나중에 알 수 없는 에러 화면을 보여줘야 하는 요구사항이 추가되면 그 때에는 에러 상태를 추가하겠다는 의미인가요?
> 
> 사실 그냥 봤을 땐 실팬데 왜 성공으로 취급하지라는 생각밖에 들지 않습니다 😢

확실히 이름이 `FetchResult`라서 요청 결과라고 오해할 수 있네요. 사실은 화면의 상태를 추상화한 것인데 말이죠..
그래서 화면의 상태를 나타내는 새로운 클래스를 만들었습니다.
```
enum class ScreenUiState {
    NONE, LOADING, NETWORK_ERROR
}
```
어떠신가요?

2023-11-02 12:34 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +@BindingAdapter("app:layout_marginTop")
토마스가 왜 다르게 속성명을 정의했을까 궁금했습니다.
위 바인딩 어댑터를 사용하는 곳이 많지는 않아서 통일시켜도 좋을 것 같습니다.

2023-11-02 12:38 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +private fun String.toDimen(): Int = if (endsWith(DIMEN_UNIT_DP)) {
확장 프로퍼티를 사용하거나, 확장 함수를 사용하용하되 메서드명을 변경해달라는 의미였습니다.
(String.dp 확장 프로퍼티가 왜 필요한지 모르신다면 확장 함수의 존재 자체도 모순이 되겠군요)
토마스의 코드는 dp만 변환이 가능한 형태 아닌가요?

2023-11-02 12:41 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/recyclerView/IntervalDecoration.kt
> +    private val height: Int = 0,
디자인을 정밀하게 적용할 수 있습니다.
ex) 1.5dp

지금 당장 필요한 부분은 아니라 resolve 하지만, 그럴 일이 없다는 추측성 멘트는 조심해주시면 좋을 것 같습니다 🙂

2023-11-02 12:42 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_all_comment.xml
> +            name="onClick"
왜 전체를 클릭하는 것이 onClick 이라는 네이밍이어야 할까요? 🤔
전체라는 것을 의미하는 어떠한 인자명도 없는데 말이죠

2023-11-02 12:48 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/NetworkErrorView.kt
> +    }
해당 리뷰 상단에서 제안한 형식의 메서드를 사용하는  코드와 Observable을 사용하는 코드를 비교해보면 좋을 것 같습니다.
저는 전자가 더 명확하고 읽기 쉽다고 느껴집니다.

2023-11-02 12:51 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/res/layout/item_all_comment.xml
> +            name="onClick"
그리고 클릭 콜백명이나 함수명은 이미 무엇을 클릭해야 하는지 컨벤션을 정해놓은 것으로 알고 있는데, 제가 잘못 이해하고 있는 걸까요?

2023-11-03 01:42 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +@BindingAdapter("app:layout_marginTop")
넵. 다음부터는 안드로이드에서 기본적으로 제공하는 속성을 변경할 땐 그 속성의 이름과 같게 네이밍 해주시면 좋을 것 같아요 😊

2023-11-03 01:59 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +private fun String.toDimen(): Int = if (endsWith(DIMEN_UNIT_DP)) {
dp 단위로 설정할 땐 dp를 붙어야 하고, dp를 붙이지 않는다면 픽셀 단위로 설정합니다. 
어떤 것의 크기를 나타내는 것은 숫자형이 어울린다고 생각합니다. 따라서 문자열에 dp 확장 프로퍼티를 선언하는 것은 조금 위험할 것 같네요.
위 바인딩 어댑터의 목적은 xml에서 
app:layout_marginTop="@{uiState.comment.deleted ? \`18dp\` : \`22dp\`}"
이렇게 결합 표현식에서 dp 단위의 크기를 설정하기 위함입니다.

2023-11-03 07:15 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ViewBindingAdapter.kt
> +private fun String.toDimen(): Int = if (endsWith(DIMEN_UNIT_DP)) {
아 이제 코드의 의도를 이해했습니다.

2023-11-03 07:49 UTC, tmdgh1592 requested changes
@ki960213 
몇 가지 도움이 될만한 코멘트를 남겼습니다.
확인해주세요~

2023-11-03 07:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/base/BaseViewModel.kt
> +    protected val _screenUiState = NotNullMutableLiveData(ScreenUiState.NONE)
BaseViewModel은 해당 PR에서는 우선 제거하는 것이 좋아 보입니다.

2023-11-03 07:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/FeedDetailActivity.kt
>  class FeedDetailActivity : AppCompatActivity() {
해당 액티비티에도 Deprecated된 imm 메서드를 사용하고 있습니다.

2023-11-03 07:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/EditTextExt.kt
> +    postDelayed(
해당 코드를 사용해보시는 것을 추천드립니다.

```suggestion
fun Activity.showKeyboard() {
    val imm = getSystemService(AppCompatActivity.INPUT_METHOD_SERVICE) as InputMethodManager
    currentFocus?.postDelayed({
        imm.showSoftInput(currentFocus, InputMethodManager.SHOW_IMPLICIT)
    }, 100)
}

2023-11-03 07:49 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/SwipeRefreshLayoutBindingAdapter.kt
> +    }
다음 코드를 제안해봅니다~

```suggestion
setOnRefreshListener {
        val refreshJob = onRefreshListener.onRefresh()
        if (!refreshJob.isCancelled) return@setOnRefreshListener

        MainScope().launch {
            refreshJob.join()
            isRefreshing = false
        }
    }
```

2023-11-03 11:39 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/base/BaseViewModel.kt
> +    protected val _screenUiState = NotNullMutableLiveData(ScreenUiState.NONE)
넵. 알겠습니다. 논의 후 추가할 지 말 지 결정하는 게 좋겠네용

2023-11-03 11:39 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/FeedDetailActivity.kt
>  class FeedDetailActivity : AppCompatActivity() {
FeadDetail과 ChildCommen의 코드와 비슷하기 때문에 ChildComment의 코드부터 리뷰를 받고 리뷰에 맞게 반영하기 위해 리뷰어 요구사항에 `FeadDetailActivity` 관련 코드는 일단 넘어가달라는 요청을 했지만 우선 반영하겠습니다. 😊

2023-11-03 11:39 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/EditTextExt.kt
> +    postDelayed(
와우! `currentFocus`라는 게 있군요. 그리고 저희는 사실 포커스 된 뷰에 텍스트를 편집하기 위해 소프트 키보드를 보여주는 것이므로 제안하신 코드가 훨씬 좋은 것 같네요! 👍

2023-11-03 11:40 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/SwipeRefreshLayoutBindingAdapter.kt
> +    }
early return을 깜빡했군요 😢 
`MainScope()`라는 새로운 api도 알아가서 좋네요 👍

2023-11-05 13:22 UTC, tmdgh1592 approved these changes

2023-11-08 01:40 UTC, chws0508 approved these changes

2023-11-08 01:47 UTC, merged