Refactor/#803 행사 및 함께해요 관련 api 명세 수정
woowacourse-teams/2023-emmsale pull request #808
Opened 2023-10-30 12:29 UTC by amaran-th

## #️⃣ 연관된 이슈
> close : #803 

## 📝 작업 내용
행사 및 함께해요 조회 API 명세 수정 및 자잘한 변경사항 반영
- API 명세 순서 수정
- Event Service 리팩토링

## 예상 소요 시간 및 실제 소요 시간 (일 / 시간 / 분)
예상 소요 시간 : 10/30
실제 소요 시간 : 10/30

2023-10-31 05:00 UTC, hong-sile requested changes
일단 간단하게 한 번 훑어봤어요 RC 날릴겡

2023-10-31 08:36 UTC, amaran-th reviewed
@hong-sile 
리뷰 반영했습니당~~

2023-10-31 08:36 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventQueryService.java
>      return EventDetailResponse.from(event, thumbnailImageUrl, informationImageUrls);
좋은 아이디어 감사합니다~~ 반영했습니다!

2023-10-31 08:36 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/scrap/application/ScrapQueryService.java
> +    Map<Long, AllImagesOfContent> imageUrlsPerEventId = new HashMap<>();
전에 어디선가 코드리뷰 받으면서 알게된 건데 stream.forEach()로 원소를 순회하게 되면, 도중에 예외가 발생했을 때 순회가 중단되지 않고 순회를 마친 후 예외가 던져진다고 하더라구요. 
그래서 저는 반복문 내에 레파지토리를 조회하는 로직이 포함된 경우 for문으로 풀어서 작성하고 있습니다.

2023-10-31 08:36 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/scrap/application/ScrapQueryService.java
> +    Map<Long, AllImagesOfContent> imageUrlsPerEventId = new HashMap<>();
반영했습니다!

2023-10-31 08:38 UTC, amaran-th reviewed
@hong-sile

2023-10-31 08:42 UTC, amaran-th reviewed
@hong-sile

2023-11-02 04:57 UTC, hong-sile approved these changes
일단 이번 목표는 명세를 수정하는 거니, 더 리팩터링 관련해선 리뷰를 안 남길게요. 수고했슴다

2023-11-02 04:57 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/scrap/application/ScrapQueryService.java
> +    Map<Long, AllImagesOfContent> imageUrlsPerEventId = new HashMap<>();
> 그 stream.forEach()로 원소순회 시 예외 발생하면 순회를 마친 후 예외가 던져진다.
는 아마 내가 알려줬던 것 같은데, 기억하고 있네 

나는 반복문 내에 Repository에서 조회 로직이 필요하도록 짰다면 다른 방식을 한번 고민해볼것 같아. 
지금 그러면 쿼리가 event 수만큼 나가고 있는 거잖아.
내 생각엔 findAllByEventIds(eventIds)를 하고, 그 다음에 grouping을 할 수도 있을 것 같은데, 어떻게 생각해?
그러면 쿼리가 훨씬 줄 것 같아서

2023-11-02 04:57 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventCommandService.java
> +    return tags.stream()
여기 작업하는 부분이 아니긴 하지만, 이런 것도 엄청 쿼리가 많이 나가는 부분이잖아 In절 쿼리로 한번에 조회하도록 할 수있을 것 같은데?

tagRepository.findByNames(tagNames)

2023-11-02 04:57 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventCommandService.java
> +    return EventResponse.from(event, savedImages);
코드리뷰 해줬던 부분을 반영하고, 하나의 커밋으로 합쳐서 커밋했네.
앞으로는 쪼개서 커밋해보도록 하자

2023-11-02 06:28 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventCommandService.java
> +    return tags.stream()
반영했어~~!

2023-11-02 06:30 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/scrap/application/ScrapQueryService.java
> +    Map<Long, AllImagesOfContent> imageUrlsPerEventId = new HashMap<>();
아아 그런 방법이 있었네
바로 반영했어
하는김에 중복 코드들을 ImageQueryService를 만들어서 옮겼습니당

2023-11-02 06:42 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/EventCommandService.java
> +    return EventResponse.from(event, savedImages);
넵...!👀

2023-11-02 06:45 UTC, merged