Feature/#85 컨퍼런스 상세 정보 조회 기능추가
woowacourse-teams/2023-emmsale pull request #94
Opened 2023-07-25 11:22 UTC by hong-sile

## #️⃣연관된 이슈
- #85 

## 📝작업 내용
- id기준으로 event를 조회하는 기능 추가

close #85

2023-07-25 11:27 UTC, java-saeng commented
현장 리뷰 완료요~

2023-07-25 11:27 UTC, java-saeng approved these changes

2023-07-26 02:19 UTC, amaran-th approved these changes
수고하셨습니다~!!

2023-07-26 02:19 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventResponse.java
>  public class EventResponse {
행사 **목록** 조회 API에서 만든 EventResponse랑 같은 이름을 사용하고 있어서 조율이 필요할 것 같습니다!

2023-07-26 02:19 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/event/exception/EventException.java
> +    return null;
null 대신 eventExceptionType을 반환하도록 해야 할 것 같습니다!

2023-07-26 02:24 UTC, amaran-th requested changes
리뷰할 때 놓친 게 있었네요...!😥
index.adoc이 업데이트가 안된 것 같습니다!
작성해주세요~~!

2023-07-26 02:24 UTC, Hyeonjae-K approved these changes
크게 수정할 점은 보이지 않네요!
수고하셨습니다~

2023-07-26 02:24 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
> +  private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern(
혹시 이 상수는 어디서 사용하는걸까요?

2023-07-26 02:24 UTC, Hyeonjae-K commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +  @Nested
저는 Nested를 성격이 다른 테스트가 한 테스트 파일에 있을 때 같은 성격의 테스트끼리 그룹화하기 위해 사용하는데 여기서는 굳이 필요해 보이지 않습니다.
혹시 Nested를 사용하신 이유나 기준이 있으신가요?

2023-07-26 02:36 UTC, java-saeng commented
추가로 .http 테스트 만들기로 했었어서 그것까지 부탁드려요~

2023-07-26 04:35 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
> +  @Nested
저는 Nested를 묶는 기준이 하나의 메서드에 대한 테스트일 때 묶습니다.

이 경우에는 findEvent에 대한 테스트끼리 묶었다고 볼 수 있죠.

지금 저 테스트들만 있는데 묶은 이유는 추후 EventService에서 많은 테스트들이 생기기 때문에 미리 묶어둔 겁니당.

2023-07-26 04:35 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
> +  private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern(
정적팩터리 메서드에서 LocaldTateTIme을 String으로 바꾸는데 사용했습니댜.

근데, 지금은 @JsonProperty를 이용하여 포맷팅하도록 리팩터링 했습니다.

2023-07-26 04:36 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/exception/EventException.java
> +    return null;
이 부분은 실수했네요 반영하겠습니다.

2023-07-26 04:36 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventResponse.java
>  public class EventResponse {
detailResponse로 변경하였습니다.

2023-07-26 04:38 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
> +  private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern(
이제 사용하지 않는다면 지워도 되지 않을까요?

2023-07-26 05:06 UTC, amaran-th approved these changes
수고하셨습니다~!

2023-07-26 05:06 UTC, hong-sile commented on backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
> +  private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern(
지웠습니당

2023-07-26 05:07 UTC, merged