Feature/#74 사용자 등록 기능
woowacourse-teams/2023-emmsale pull request #95
Opened 2023-07-25 11:41 UTC by tmdgh1592

## #️⃣연관된 이슈
>  ex) #74

## 📝작업 내용
> 온보딩 화면에서 활동 내용과, 서버

### 스크린샷 (선택)
<img width="341" alt="스크린샷 2023-07-25 오후 8 39 37" src="https://github.com/woowacourse-teams/2023-emmsale/assets/56534241/ba037839-0518-4c20-868f-649869914014">

## 예상 소요 시간 및 실제 소요 시간
> 이슈의 예상 소요 시간과 실제 소요된 시간을 분 or 시간 or 일 단위로 작성해주세요.
> 
> ex) 예상시간/걸린시간 => 2시간/3시간

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2023-07-26 02:29 UTC, ki960213 reviewed
xml 쪽은 리뷰하지 않았습니다.

2023-07-26 02:29 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingViewModel.kt
> +        when (val activitiesApiModel = activityRepository.getActivities()) {
리포지터리에서 ApiModel을 반환하나요?

2023-07-26 02:29 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/uistate/ActivityUiState.kt
> +        fun from(activities: List<Activity>): List<ActivityUiState> =
위의 정적 팩토리 메서드 리뷰와 동일합니다.

2023-07-26 02:29 UTC, ki960213 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/uistate/ActivitiesUiState.kt
> +        fun from(tags: List<Activities>): List<ActivitiesUiState> = tags.map(::from)
위의 정적 팩토리 메서드와 동일합니다.

2023-07-26 06:36 UTC, tmdgh1592 reviewed
리뷰 테스트

2023-07-26 12:19 UTC, chws0508 requested changes

2023-07-26 12:19 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingJobFragment.kt
> +    override fun onClick(view: View) {
그냥 buttonClickListener 에 한번에 구현하는 것이 개인적으로 가독성이 좋아보여요

2023-07-26 12:19 UTC, chws0508 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingViewModel.kt
> +    val nameUiState: MutableLiveData<String> = MutableLiveData()
이 변수는 naeUiState 로 하고, 나머지는 UiState 안붙인게 통일성에 안맞는 것 같아요. 이것도 그냥 name 으로 하는것이 좋을 것 같네요.

2023-07-27 03:54 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/activity/Activities.kt
> +        fun from(activitiesApiModels: List<ActivitiesApiModel>): List<Activities> =
정리해서 데이터 모델(이후에 도메인으로 사용될 클래스)의 변경을 최소화하자는 것으로 이해하고 리뷰 반영하겠습니다.

2023-07-27 06:53 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/activity/Activities.kt
> +        fun from(activitiesApiModel: List<ActivityApiModel>): List<Activity> =
동일하게 반영 완료하였습니다 : )

2023-07-27 07:09 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingViewModel.kt
> +        when (val activitiesApiModel = activityRepository.getActivities()) {
apiResult를 apiModel로 잘못 작성하였네요..!
`activitiesResult`로 변경하였습니다.

2023-07-27 07:17 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/uistate/ActivityUiState.kt
> +        fun from(activities: List<Activity>): List<ActivityUiState> =
List<T>는 T가 아니기 때문에 적절한 정적 팩토리 메서드 패턴이 아니라는 의미로 이해했습니다.
코드 수정 완료하였습니다.

2023-07-27 07:24 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingJobFragment.kt
> +    override fun onClick(view: View) {
현재 클릭할 뷰가 하나이므로, 스캇 말씀처럼 View.OnClickListener를 구현하는 것보다 바로 setOnClickListener에 구현하는 것이 가독성이 좋아 보입니다!
수정 완료하였습니다 : )

2023-07-27 07:36 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/data/token/TokenRepositoryImpl.kt
> +        context.getSharedPreferences("kerdy", Context.MODE_PRIVATE)
SharedPreferenceContainer를 만들어서 주입받도록 변경하였습니다.
앞으로는 다른 곳에서도 Preference를 공통으로 사용할 수 있습니다.

2023-07-27 07:39 UTC, tmdgh1592 commented on android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingViewModel.kt
> +    val nameUiState: MutableLiveData<String> = MutableLiveData()
감사합니다! nameUiState는 깜빡하고 프리픽스를 제거하지 않았었네요 😭
수정 완료하였습니다~

2023-07-27 07:40 UTC, chws0508 approved these changes
^^

2023-07-27 07:41 UTC, merged