Feature/#83 댓글 대댓글 crud api 구현
woowacourse-teams/2023-emmsale pull request #97
Opened 2023-07-25 15:10 UTC by java-saeng

## #️⃣연관된 이슈
- #83 

## 📝작업 내용

댓글 관련 CRUD API 를 구현해습니다.

## 예상 소요 시간 및 실제 소요 시간

예상 시간 : 수요일 오후 6시
실제 소요 시간 : 수요일 오전 12시

## 💬리뷰 요구사항

코드 잘 읽히시는지, 제대로 작성된 것 같은지 확인 부탁드립니다.

2023-07-26 04:32 UTC, hong-sile requested changes
전체적으로 통일성이 있어서 확인하긴 편했습니다.

몇몇 커멘트 남겼으니 확인해주세요.

2023-07-26 04:32 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
> +    final Member 댓글_작성자 = memberRepository.findById(1L).get();
댓글 작성자를 모든 테스트에서 쓴다면 필드 변수로 빼보는 건 어떨까요?

2023-07-26 04:32 UTC, hong-sile commented on backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentRepositoryTest.java
> +    final long eventId = 2L;
나중에 event 관련된 테스트가 생기면 auto_increment 때문에 터질 것 같아요.
event의 getId로 eventId를 세팅하면 어떨까요?

2023-07-26 04:34 UTC, Hyeonjae-K approved these changes
수고하셨습니다!
크게 수정할 점은 보이지 않습니다.

2023-07-26 04:34 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentModifyRequest.java
> +  private CommentModifyRequest() {
혹시 이게 왜 필요한지 알 수 있을까요?
없으면 테스트가 터지는데 다른 Request DTO들은 없어도 되는데 이 친구만 특별하게 있어야 하는 이유가 궁금합니다!

2023-07-26 04:34 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentResponse.java
> +  private static final String DELETE_COMMENT_CONTENT = "삭제된 댓글입니다.";
이 상수가 사용되고 있는 곳을 찾을 수 없는데 혹시 어디서 사용하는 건가요?
`isDeleted`를 통해 `true`일 경우 이 값으로 대체하는 로직이 빠진걸까요?

2023-07-26 04:34 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/comment/exception/CommentExceptionType.java
> +  CAN_NOT_DELETE_COMMENT(
이건 개인적인 의견인데 갑자기 생각이 나서 코멘트 달아둡니다.
혹시 NOT_FOUND처럼 FORBIDDEN으로 http 상태 메시지로 통일하는건 어떠신가요?

2023-07-26 04:34 UTC, Hyeonjae-K commented on backend/emm-sale/src/main/java/com/emmsale/comment/exception/CommentExceptionType.java
> +      HttpStatus.FORBIDDEN,
이건 인가의 문제가 아니라 클라이언트의 잘못된 요청이므로 BAD_REQUEST가 더 좋을 것 같은데 우르는 어떻게 생각하시나요?

2023-07-26 04:34 UTC, Hyeonjae-K commented on backend/emm-sale/src/test/java/com/emmsale/member/domain/MemberActivityRepositoryTest.java
> +    System.out.println("memberCareerIds.size() = " + memberCareerIds.size());
혹시 콘솔 출력을 추가하신 이유가 있으신가요?

2023-07-26 04:38 UTC, amaran-th requested changes
수고하셨습니다!
코멘트 몇 개 남겼으니 확인해주시면 감사하겠습니다~

2023-07-26 04:38 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentCommandService.java
> +    validateSameWriter(loginMember, comment, CAN_NOT_DELETE_COMMENT);
혹시 `CAN_NOT_DELETE_COMMENT` 예외 타입을 `validateSameWriter()` 메서드에서 직접 사용하지 않고 매개변수로 넘겨주신 이유가 있나요??
조금 불필요한 작업으로 느껴져서요

2023-07-26 04:38 UTC, amaran-th commented on backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentResponse.java
> +  private static final String DELETE_COMMENT_CONTENT = "삭제된 댓글입니다.";
이제 사용되고 있지 않은 상수인 것 같으니 지워줘도 될 것 같습니다!

2023-07-27 03:46 UTC, hong-sile approved these changes

2023-07-27 03:46 UTC, amaran-th approved these changes

2023-07-27 03:46 UTC, java-saeng commented
현장 리뷰 완료

2023-07-27 03:47 UTC, merged